### ISSUE TITLE
Possible to filter for multiple categories in a single query?

### ISSUE THREAD

**Issue by denitto** [WP-API/WP-API#1004]
Forgive me (and please point me in the right direction if this is a duplicate), but I didn't see this anywhere else.

With type, it's obvious why this works:

>The type parameter specifies the post type to retrieve. This can either be a string or an array of types.
>Note that arrays are specified using the [] URL syntax. e.g.
>GET /posts?type[]=post&type[]=page
>Default is “post”. (string)
>http://wp-api.org/

But I am unable to query with multiple categories similarly with, for example:

GET /posts?filter[category_name][]=video&filter[category_name[]=featured

Is is possible to query for more than one category at a time with the API?

Thanks! 
Nick

**Comment by danielbachhuber** [comment]
> Is is possible to query for more than one category at a time with the API?

Probably not at this time. We'll make sure to consider this as a part of #924

**Comment by equatorapps** [comment]
If this is not currently possible from the base query, what are the alternatives?

**Comment by danielbachhuber** [comment]
> If this is not currently possible from the base query, what are the alternatives?

You'll need to implement a workaround using filters.

**Comment by equatorapps** [comment]
Hi Daniel, I am not sure if this is what you mean but I have tried:

../?filter[product_cat]=one&filter[product_cat]=two

All that does is narrows down the results to items that are in both filters.

I am looking for how to get a result that returns ALL items from BOTH filters.

Thanks.

**Comment by nharlow89** [comment]
In case anyone else stumbles upon this I came up with a solution using the rest_{post-type}_query hook to modify the query. You can now query for posts that exist in BOTH categories using the AND operator instead of OR.

Full explanation is here: [WP API Multiple Taxonomy Query](http://y-designs.com/blog/wp-api-multiple-taxonomy-query/).

**Comment by indikatordesign** [comment]
If you're working with custom routes, here is a simple workaround:

All cat-id's are positive ints. So you can implode your wanted cats for example with '-' to get a string like  
this: 4-5-8-34-78-89

Now you can create a query like this: cats=4-5-8-34-78-89

To validate this is simple:

```
$this->args['cats'] = array(
    'validate_callback' => function($param, $request, $key)
    {
        if ( empty( $param ) ) return false;

        $cats = array_map( 'intval', explode( '-', $param ) );

        foreach ( $cats as $key => $value )
        {
            if ( $value === 0 ) return false;
        }

        return true;
    }
);
```

A query like this works fine: /wp-json/ra_custom_endpoints/v1/posts?cats=4-5-8-34-78-89&per_page=10

A query like this: /wp-json/ra_custom_endpoints/v1/posts?cats=4-5-8-34-78-89-script

fails, because anything other than an positive integer will be converted into 0.

**Comment by comitzuu** [comment]
A query like this: /wp-json/ra_custom_endpoints/v1/posts?cats=4-5-8-34-78-89-<script> fails, because anything other than a positive integer will be converted into 0.
