### ISSUE TITLE
Establish criteria for when data should be nested in sub-objects on resources

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1022]
I'd still like to keep an issue open on #955 for discussion. The pull request changes:

```
{
    "author": "admin",
    "author_email": "admin@example.com",
    "author_url": ""
}
```

Into:

```
{
    "author": {
        "name": "admin",
        "email": "admin@example.com",
        "url": ""
    } 
}
```

I'd argue for the former, as it's less code to write for create and update requests, and the latter implies some form of consistent structured object. @rmccue [argues for the latter because it's in v1](https://wordpress.slack.com/archives/core-restapi/p1427325812000068), although it's not clear why it made into v1 in the first place. According to @rmccue, [Backbone is one place where destructured data is better](https://wordpress.slack.com/archives/core-restapi/p1427325682000055).

More broadly speaking, though, we should establish some criteria for when we put data in sub-objects on a resource, and when we don't. If we don't have such criteria, then we will introduce inconsistencies to our API. Inconsistent behaviors, arguments, and formats are one reason developers don't like working with WordPress (and PHP). WP-API provides us the opportunity to provide a new, consistent, durable interface to WordPress, let it be through JSON REST, PHP, CLI, or other usage implementations.

#848 would be impacted by this criteria.

**Comment by danielbachhuber** [comment]
For the former, CLI interface would be:

```
wp comment update --author_url=http://wordpress.org
```

CLI doesn't currently support nested objects. It may need to look like this:

```
wp comment update --author[url]=http://wordpress.org
```

I don't know whether brackets work on CLI off the top of my head though.

**Comment by kadamwhite** [comment]
We've been working heavily with the [JSON API](http://jsonapi.org/) project (invoking @tkellen for more information), which I feel also favors destructured. In that case though author would be a separate resource and a post would only have the reference, so it may not be relevant.

**Comment by tkellen** [comment]
The original version of the JSON API spec had data in type-named buckets like this and it worked well for many use-cases. It falls over pretty hard when you get into polymorphic relations though (where the type name can change per-item). I'm not super familiar with the Wordpress database these days, but if you have polymorphic relations, or want to support extensions which have them, I would caution against this format.

That said, is it correct to assume this project is in an early enough stage to consider rather drastic changes (guessing here based on the fact that you're bikeshedding the request/response format)? If yes, I would **strongly** recommend checking out the [JSON API spec](http://jsonapi.org/) (we're close to marking 1.0 and we are **very** committed to backwards compatibility). It would be amazing to have ya'll using this emerging standard and I would be happy to be a resource if you decide to explore the possibility.

**Comment by danielbachhuber** [comment]
@tkellen Could you provide a tl;dr; summary, or point us to one, as to why the JSON API spec isn't another flavor of [Swagger or RAML](https://wordpress.slack.com/archives/core-restapi/p1427464959000180)?

Also, if you have a bit of extra bandwidth over the next few weeks, we would love, love, love to get your input on some of the [remaining architectural decisions](https://docs.google.com/a/handbuilt.co/document/d/1tyTK8w6A4OBxrmm2rPBRdKOF6Jst7YyPc0AsTyodaQw/edit) in our chats, on these issues, etc. We're `#core-restapi` in the Making WordPress Slack and, if you want to email me on the address listed on my GH profile, I'll sync you up with the conversation scheduling.

**Comment by kadamwhite** [comment]
@tkellen context for the above link, in case you haven't made an account for WP's Slack to see the archives (I'm told they're working on getting those non-login-gated, fingers crossed): this recap of an API panel http://blog.runscope.com/posts/what-you-thought-you-knew-about-api-trends-api-leaders-tell-all-at-sxsw indicated that none of the participants used any sort of external schema specification like Swagger, an observation which @rmccue had also made at API Craft. The lack of adoption made Swagger and RAML much less appealing.

**Comment by steveklabnik** [comment]
Hey, another co-author of the JSON API spec here.

> Could you provide a tl;dr; summary, or point us to one, as to why the JSON API spec isn't another flavor of Swagger or RAML?

They're fundamentally different. Swagger and RAML are both description languages, meaning that you first download the description file, then do something, either generating a client, or whatever. This is the approach taken by SOAP, historically.

JSON API is more in the tradition of media types: JSON itself, ATOM and ATOMpub, and HTML. JSON API's specification describes what a response can look like, but it's up to the server to provide a specific kind of response, and use the affordances in the type (like links, for Atom, HTML, and JSON API's case) to provide the next step in processing. This means you use a more  generic client, rather than generating a specific one. Think about how you use an Atom or RSS library to access an RSS feed on various different domains.

> The lack of adoption made Swagger and RAML much less appealing.

While JSON API isn't specific to Ember, it's going to be the out-of-the-box default for Ember data as of it's 1.0 release in June.

I'd be happy to answer any more questions you might have.

**Comment by rachelbaker** [comment]
Last week, @rmccue, @apokalyptik, and I had a discussion surrounding structured vs destructed data.  In summary, arguments can be made for or against structured responses depending on the client language or framework being used.   

We did all agree that the structure of v2 responses **should** match v1 responses _unless there is a compelling reason_ to deviate.  

With v1.x of this API the comment author response was structured data.  Example:

```json
"author": {
    "ID": 1,
    "name": "Rachel Baker",
    "URL": "http://www.rachelbaker.me",
    "avatar": "http://0.gravatar.com/avatar/634b37a53babc18a5bda19722d5b41a3?s=96",
}
```

This was the critera I used for merging #955, and (unless I hear otherwise) the guideline we should use for future related discussions.

**Comment by danielbachhuber** [comment]
> In summary, arguments can be made for or against structured responses depending on the client language or framework being used.

What are the ones _for_ structured responses? I haven't seen any yet, other than @rmccue thinks it's nice you can "[share code for comment authors and users](https://wordpress.slack.com/archives/core-restapi/p1427325716000060)" and "[looks cleaner](https://wordpress.slack.com/archives/core-restapi/p1427325792000065)". These justifications are likely why v1 ended up the way it did.

My arguments against at this point are:

1. It's more code to write for create and update requests. More code means more complexity. Therefore, it's simpler for clients and interfaces to manipulate resources without nested sub-objects.
1. It implies some structured resource when it actually isn't.

Furthermore, it's inconsistent with our other resources, which pushes me to _underscore_ this point:

_More broadly speaking, though, we should establish some criteria for when we put data in sub-objects on a resource, and when we don't. If we don't have such criteria, then we will introduce inconsistencies to our API. Inconsistent behaviors, arguments, and formats are one reason developers don't like working with WordPress (and PHP). WP-API provides us the opportunity to provide a new, consistent, durable interface to WordPress, let it be through JSON REST, PHP, CLI, or other usage implementations._

It's not that I feel so strongly for my first two points I'm not open to being convinced otherwise, but rather the rationale seems to be some combination of "this is how we did it before" and "it's a bike-shedding argument". Neither of these are the reasons for API v2. The reason for API v2 is to strongly (re)consider all of our design decisions, challenge assumptions, and produce a clear, consistent foundation of ideals that we won't hate in a year.

> unless there is a compelling reason to deviate.

Right, that's what we're discussing.

**Comment by tkellen** [comment]
@danielbachhuber looks like @steveklabnik got to this before I could (thanks Steve!).

RE your google doc (I have not read the slack conversations, so apologies if these comments are redundant):

**1** Trashing is fine.  From [rfc 7231](https://tools.ietf.org/html/rfc7231#section-4.3.5):

>   The DELETE method requests that the origin server remove the
   association between the target resource and its current
   functionality.  In effect, this method is similar to the rm command
   in UNIX: it expresses a deletion operation on the URI mapping of the
   origin server rather than an expectation that the previously
   associated information be deleted.

>   **If the target resource has one or more current representations, they
   might or might not be destroyed by the origin server, and the
   associated storage might or might not be reclaimed, depending
   entirely on the nature of the resource and its implementation by the
   origin server (which are beyond the scope of this specification).**

**2** Resources in an API are representations of the underlying data, not the data itself. Put more plainly, I would not feel compelled to make the API mirror the representation in the database. In fact, I would patently avoid this tight coupling and focus on providing data in the best possible format for consumers. This will obviously make your server code a bit more complex, but I would argue that your server should support this sort of thing from the ground up, period. Failing to do this means you expose the internal implementation details of your database to end users and make it difficult to iterate internally.

**3** I would follow whatever the database constraints are and, to whatever extent possible, use something like [json-schema](http://spacetelescope.github.io/understanding-json-schema/UnderstandingJSONSchema.pdf) to confirm compliance with incoming payloads.

**4** No comment, I lack the Wordpress-specific context to speak meaningfully.

**5** Perhaps reference the json-api specification for this? It has rich support for displaying information graphs.

**6** If I understand this correctly, json-api can also deal with this effectively because it has first-class support for polymorphism. I'd be happy to go into more detail here, but I think realtime communication of some kind would be warranted.

**7** No comment, I lack the Wordpress-specific context to speak meaningfully.

I'm not entirely sure any of these answers will be helpful to you, but I will say that if you consider using JSON-API, a lot of these decisions will be made for you. Of course, this requires that you feel the decisions made by JSON-API hold enough weight to follow. I'm biased, but I think the specification is very solid, having taken into account an incredible amount of bike-shedding by many people over the last few years.

**Comment by joehoyle** [comment]
My, very short 2c in direct response: keep embedded objects for just that - embedded API _objects_. Anything that isn't it's own object (i.e. can `GET` at its own URL) should be destructured / flat. Seems predictable to me.
