### ISSUE TITLE
Remove password-protected posts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1055]
Setting and unsetting a cookie within a RESTful API is quite ugly. We should probably internalize core's logic if core isn't going to. 475e041ff865ffe2f0102156d29f2d3e0cdfc3f1

Also, we should show password-protected posts with "Protected: `<title>`"

Previously #313

**Comment by danielbachhuber** [comment]
Looks like Ryan started this in #939

**Comment by danielbachhuber** [comment]
Some conversation from today's hangout:

* Core's cookie handling is per `COOKIE_HASH`, not post, so viewing a second password-protected post nullifies the first.
* We can't pass the password as a `GET parameter because it could expose the password in the logs.
* WordPress.com accepts the password as a `GET` parameter. This is likely an unacceptable risk for core.
* Ryan suggested authorization headers instead of parameters.
* Another open question: what fields are expected to be password-protected?
* We should err on the side of less data (e.g. not in the loop)

**Comment by rmccue** [comment]
> We can't pass the password as a `GET parameter because it could expose the password in the logs.

One thing I forgot to mention here too: not just full server admins but also admins on a multisite network might have access to these.

**Comment by mnelson4** [comment]
>Ryan suggested authorization headers instead of parameters.
Authorization headers seems like quite a natural RESTy way provide the password.

>what fields are expected to be password-protected?
Given how much data is shown on the archives page for password-protected posts, I think its almost better to consider what fields are expected to NOT be password-protected? In twenty-fourteen theme, I can only see the event's author, date, post_name, post_title, and categories (and kindof infer the post_type) in the archives page.

re #1100: should authorized users be able to access password-protected posts without providing the password? (eg a user who has the "read_private_posts" can access posts without providing a password in the WP admin, but on the posts archive page they DO need to provide a password). 
It seems that generally the API should display whatever the current user can access from either the frontend or backend, so if they can view the post without providing a password in the admin, the API should do the same. Agreed?

**Comment by nschoenholtz** [comment]
I'm curious what the thinking behind the current handling is, because it seems a little bit backward to me -- it keeps password protected posts out of queries, but reveals all of the content if requested directly (vs in core, the posts would be included in the query but the content would be hidden).

I definitely support the authorization header approach -- would a pull request be welcome here, or is there a larger approach already in the works?

**Comment by danielbachhuber** [comment]
More discussion: https://wordpress.slack.com/archives/core-restapi/p1449533485001559

**Comment by danielbachhuber** [comment]
Password-protected posts are plugin territory, and won't be supported by the REST API. We'll be making password-protected posts completely invisible in the REST API.

**Comment by timmyc** [comment]
Some related logic from Jetpack: https://github.com/Automattic/jetpack/blob/master/json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php#L112-L114 - basically sets `has_password` on the query [#](https://core.trac.wordpress.org/changeset/27395) to `false` if the user is not logged in, thus removes password protected posts from the response.

> It seems that generally the API should display whatever the current user can access from either the frontend or backend, so if they can view the post without providing a password in the admin, the API should do the same. Agreed?

I kind of like this approach of if it is an authenticated request and the user has access to the posts, return password protected posts.

> WordPress.com accepts the password as a GET parameter. This is likely an unacceptable risk for core.

@danielbachhuber I tried to track down where this might be happening but failed to do so.  In the calypso post editor, all updates to posts are POST'ed, and looking at the JP endpoint above I don't see where this is happening either ( though I could have missed it ).

Also I wanted to verify that this issue is to remove all password posts from being retrieved/viewed via the API but being able to update/save a post with a password will still be supported?

**Comment by danielbachhuber** [comment]
> I tried to track down where this might be happening but failed to do so. In the calypso post editor, all updates to posts are POST'ed, and looking at the JP endpoint above I don't see where this is happening either ( though I could have missed it ).

Given the comment was from a year ago, things might have changed. However, "accepts the password as a GET parameter" was referring to _viewing_ a password-protected post, not edit one. I don't see any [query params](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post_ID/) for it though.

> Also I wanted to verify that this issue is to remove all password posts from being retrieved/viewed via the API but being able to update/save a post with a password will still be supported?

I don't know now :( I think we need to discuss with a Hangout of interested parties again, because I need to spend about 10 minutes wrapping my head around the specifics again (to be able to communicate them precisely).

**Comment by nylen** [comment]
> It seems that generally the API should display whatever the current user can access from either the frontend or backend, so if they can view the post without providing a password in the admin, the API should do the same.

I agree with this.

Since unauthenticated users are able to see password-protected posts in listing pages, we should show them in the API too (excluding the content or excerpt, and any other fields that are deemed sensitive).  This would be a big win over any existing API that I'm aware of.

What are the potential issues with removing [this check](https://github.com/WP-API/WP-API/blob/d07bf57/lib/endpoints/class-wp-rest-posts-controller.php#L953-L955) to enable listing passworded posts?  I'd imagine we'll want a whitelist of fields that can be exposed in this situation, and lots of tests.

> We can't pass the password as a `GET` parameter because it could expose the password in the logs.

I'm not convinced that this is a huge problem:  the password is already stored in plaintext in the database and in cookies.  Still, supporting a couple of options (`GET`, a custom header, `POST` for applicable endpoints) makes sense to me.

**Comment by danielbachhuber** [comment]
@nylen Again, there are many nuances to the overall problem which aren't well-captured in this issue. On a whole, we can't unilaterally decide to begin exposing data which was formerly private — and we need to make quadruply sure we don't accidentally do so.

**Comment by nylen** [comment]
From my (admittedly very limited) knowledge and testing, the fact that passworded posts exist, their data such as titles, authors, etc. is already exposed through listing pages.  I'm aware that display of these posts can vary by theme.  Are there situations where this information isn't available at all?

**Comment by nylen** [comment]
Quoting @danielbachhuber and @rmccue from [Slack discussion](https://wordpress.slack.com/archives/core-restapi/p1455059814002176)

---

Some of the ugly nuances of this issue that we'd need to solve:
- core's password-protected posts implementation is cookie-based. there's one cookie, which means you can only ever view one password-protected post at a time
- which fields should be accessible when the password isn't present?  core is ambiguous in this regard, meaning we'd need to come to some secure decision on our own
- users who can edit a passworded post sometimes have access to read it, and sometimes don't

From an implementation standpoint in WP-API, this could work parallel to the normal capabilities system.

Ideally, if we truly want password-protected posts, someone should design a better implementation (that includes a way to specify multiple post passwords at once while listing posts).  A parallel is token-based post previews / draft sharing.

**Comment by danielbachhuber** [comment]
Closing in favor of #2701. Password protected posts will live on.
