### ISSUE TITLE
Fix request argument validation

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1068]
From https://github.com/WP-API/WP-API/pull/1066/files#r27848382

Need to make sure we have test coverage for request argument validation against each of our controllers.

**Comment by danielbachhuber** [comment]
Related #871, #943

**Comment by joehoyle** [comment]
I think rather than somehow testing for request arg validation (which we don't currently have) - we should decide whether superglobals (GET and POST) are passed as `$args` to the callback function. Currently we do, which is how we were able to break the args registration and everything still work - because you don't _need_ an `arg` option for the callback to receive it.

I saw we should only pass args to the callback that have been registered via `args` in `register_json_route`

**Comment by danielbachhuber** [comment]
> I say we should only pass args to the callback that have been registered via args in register_json_route

This makes sense to me.

**Comment by rachelbaker** [comment]
Still needed after the merge of #989 

 - [ ] Posts
  - [ ] Comments
  - [ ] Users
  - [ ] Taxonomies
  - [ ] Post Types

**Comment by joehoyle** [comment]
I've added the remaining endpoints mentioned @rachelbaker above in https://github.com/WP-API/WP-API/pull/1129. Closing out.
