### ISSUE TITLE
The properties in the Revisions Controller should be accessible via a sub-class

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1127]
We should give the properties in the Revisions Controller `protected` visibility so they are accessible in a sub-class.

```
	private $parent_post_type;
	private $parent_controller;
	private $parent_base;
```

should become:

```
	protected $parent_post_type;
	protected $parent_controller;
	protected $parent_base;
```

**Comment by danielbachhuber** [comment]
> We should give the properties in the Revisions Controller protected visibility so they are accessible in a sub-class.

Why? From #1063:

> We have a variety of protected controller methods. Once we release WP-API to the wild, we're committing to keeping those methods around forever.

Class variables apply too.

**Comment by rachelbaker** [comment]
Closing this, I don't care enough to push this forward.

**Comment by GhislainPhu** [comment]
Hi,

I tried to add some routes for a custom post type, but the `rest_base` I chose was quite generic and I wanted to namespace it to avoid possible conflicts. So, I created a custom controller extending `WP_REST_Posts_Controller`.

Something like that:

``` php
class My_CPT_Controller extends WP_REST_Posts_Controller {
    public function __construct( $post_type ) {
        parent::__construct( $post_type );
        $this->namespace = 'my-namespace/v1';
    }
}
```

``` php
register_post_type( 'my_cpt', array(
    'label'                 => __( 'My CPT' ),
    'public'                => true,
    'supports'              => array( 'title', 'editor', 'revisions' ),
    'show_in_rest'          => true,
    'rest_base'             => 'generic_name',
    'rest_controller_class' => My_CPT_Controller::class,
) );
```

The namespace is hardcoded in `WP_REST_Revisions_Controller::__construct()`, so I removed the default endpoints using the [rest_endpoints](https://developer.wordpress.org/reference/hooks/rest_endpoints/) filter hook and I registered my own revisions controller :

``` php
class My_CPT_Revisions_Controller extends WP_REST_Revisions_Controller {
    public function __construct( $parent_post_type ) {
        parent::__construct( $parent_post_type );
        $this->namespace = 'my-namespace/v1';
        $this->rest_base = 'revisions';
    }
}
```

If you don't call `WP_REST_Revisions_Controller::__construct()` in the child class, you get a fatal error because of `$this->parent_controller->get_item_schema()` ([line 317](https://github.com/WP-API/WP-API/blob/09eac80fd3bcadf4aac36952ee0fc66b5c71acd8/lib/endpoints/class-wp-rest-revisions-controller.php#L317)). If you do, you can't use your own class as `WP_REST_Revisions_Controller::$parent_controller`. The only way I found to solve this issue was to use the [ReflectionClass](http://php.net/manual/en/class.reflectionclass.php).

I don't know if the properties should become protected or if we should add a hook somewhere, I just wanted to share that use case :wink:
