### ISSUE TITLE
Bring back descriptive errors for permissions failures

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#1146]
When we merged the permissions callbacks, we lost some of the finer grained error codes and messages. We should typically have each `false` return from a permissions callback actually returning a `WP_Error` object.

**Comment by rmccue** [comment]
Essentially: `json_forbidden` doesn't tell us much, since it's really just duplicating the 403 that you get already. The code is instead meant to be a machine-readable version of the plain-text message you get to allow checking fine-grained errors in clients.

(You can still do coarse checks via HTTP status codes, of course.)

**Comment by joehoyle** [comment]
PR merged, closing
