### ISSUE TITLE
Add support for content multiplexing in requests

### ISSUE THREAD

**Issue by eduardoboucas** [WP-API/WP-API#1152]
I've been using WordPress in an API-first environment, using the CMS to create and manage content and an API to deliver it to the various end-systems, which have any technologies and languages in their stack as long as they can speak JSON. I've written about it with more detail in [this article on CSS-Tricks](https://css-tricks.com/thoughts-on-an-api-first-wordpress/).

I needed some features that were not available in the WP-API, which led me to create my custom solution. However, I've been migrating my features to individual plugins that extend the WP-API as it's a much more mature product.

The main feature that I built is the ability to multiplex different sets of data in a single request. Because this API-first approach needs the API to fetch any data required from the back-end, it may mean sending multiple requests to it in order to render a single page. Merging entries resulting from different filters in a single request can help with that:

**Request:**
http://api-url/postgroups?**one**:filter[category_name]=foo&**one**:filter[author_name]=bar&**two**:filter[s]=baz&**three**:filter[tag]=foobarbaz

**Result:**
```json
{
	"one": [
		{
			"id": 1
			(...)
		},
		{
			"id": 2
			(...)
		}
	],
	"two": [
		{
			"id": 10
			(...)
		}
	],
	"three": [
		{
			"id": 20
			(...)
		},
		{
			"id": 30
			(...)
		}
	]
}
```
Here is the plugin that extends WP-API with the ability to multiplex requests: [wp-api-post-groups](https://github.com/eduardoboucas/wp-api-post-groups).

What I propose is that you consider adding this functionality to the API core as it's such a simple implementation that can mean so much in terms of optimization and it's still inline with the REST philosophy followed by the project.

Thanks!

**Comment by rmccue** [comment]
We want to support this in a nice generic way across all of our endpoints, and we've been exploring this over on #561.

Adding support for multiple queries at once is nice, but often you want to get different types of data. For example, you might want to get the latest posts and the latest comments in one request so that you can display both the main content and the sidebar. There's other use cases for this too, such as getting a post and the associated author user, which we've successfully handled as part of #570.

Thanks for the plugin, we'll take the approach into consideration when we loop back to sorting out batch requests! :)
