### ISSUE TITLE
WP-API and polylang multilanguage support needed

### ISSUE THREAD

**Issue by vpadhariya** [WP-API/WP-API#1156]
Hi.

I tried this plugin and its awesome!

Since the site is in Multi-Language (en, ar) I want the result to be in multi language, but this gives result always in default language.

Same issues raised by another user here : https://wordpress.org/support/topic/polylang-plugin-1

Please help how to achieve this?

I am using polylang plugin for multi language.

**Comment by Rask** [comment]
+1

**Comment by danielbachhuber** [comment]
> but this gives result always in default language.

Can you be more clear about your expectation? I'm not following the request.

**Comment by rmccue** [comment]
Thanks for filing this issue! Multilingual support isn't built in to WordPress core, but rather is implemented on top of it by multilingual plugins like Polylang. This project is intended to be part of WP core, so adding support for this needs to be done in the multilingual plugin rather than here.

As to why it returns the default language, I suspect that's how the plugin works internally. :)
