### ISSUE TITLE
HTML entities are not decoded

### ISSUE THREAD

**Issue by axettone** [WP-API/WP-API#1227]
I'll suggest to evaluate a decoding of html entities. E.g. I have a category in Wordpress whose name is "> something". The '>' char is stored on the db by Wordpress as '&gt;' and when I query the plugin, I still get '&gt;'. However JSON is not HTML, and probably the use of HTML entities is not good. I suggest to use html_entity_decode() on category names, slugs and so on.

**Comment by danielbachhuber** [comment]
Good suggestion. We'll flag this for discussion.

**Comment by danielbachhuber** [comment]
Some discussion in Slack: https://wordpress.slack.com/archives/core-restapi/p1453763817000092

**Comment by danielbachhuber** [comment]
**Issue:** WordPress supports HTML in fields that developers wouldn’t typically expect HTML in (e.g. post title). The REST API returns HTML (including HTML entities) in the response body for these fields.

**Resolution:** Teach developers to expect HTML in these fields (e.g. include in schema description), and ensure their clients can safely handle returned HTML.

**Comment by danielbachhuber** [comment]
:hammer:

**Comment by nylen** [comment]
For the fields that contain HTML, the warning is a good addition and there's nothing else that can or should be done.

IMO this is more of an issue for fields that can't contain HTML but have entities encoded anyway, such as term names.  For those cases, "teach developers to expect HTML" isn't really a resolution.

For example, when we pass tag names to React for rendering, we have to decode HTML entities first, otherwise they end up double-encoded.  The alternative is to `dangerouslySetInnerHTML` which is worse.  Either way this is not really a sane pattern to have to follow.

A pretty minor issue in the scheme of things, but it would be a win for application developers if the API could smooth over this annoyance and decode fields for us.

**Comment by pratham2003** [comment]
Even if we add html_entities_decode on the returned values (PHP) in our extended endpoints the API (plugin) still encodes them internally at a later stage. Teaching developers to handle html entities isn't a decent solution. There should have be an option to turn the encoding off if the default is on.

Using this API with something like Typeahead for auto complete based on an API that shows post titles should have been pretty straight forward but instead we need to execute something like this in Javascript `$("<div/>").html(encodedStr).text();` before passing each item in a result array to Typeahead.

**Comment by codewithfeeling** [comment]
This is pretty hideous when trying to handle a REST response to populate the options of a built in `<SelectControl>` in Gutenberg. There's no way to `dangerouslySetInnerHTML` for the individual options, so I'm completely at a loss to work out how to do this without considerable work. I am surprised that the only option for the title is the `rendered` version.

**Comment by codewithfeeling** [comment]
Just figured out that you can solve this in React (for Gutenberg blocks) by using:

    const { decodeEntities } = wp.htmlEntities;

Then in your code:

    const someString = decodeEntities( someStringWithEntities );

Nice.
