### ISSUE TITLE
Disambiguate between trashed and permanently deleted Posts and Comments

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1260]
In `develop`, a client making a `DELETE` request to Posts or Comments has no way of distinguishing between whether the request trashed the resource or permanently deleted it. We should provide this detail.

From #1224

Also, 2x `DELETE wp/v2/comments/<id>` will permanently delete a comment, but 2x `DELETE wp/v2/posts/<id>` will return some `rest_already_deleted` error (2d5cf2ca2987353bcaac17b25e4650250119d7f5, #959). We should make sure these are consistent.

**Comment by rmccue** [comment]
#1271 should help out with this for now, but we want to also wrap the data in an object with a `trashed`/`deleted` key. This **intentionally** won't match the data itself, since we're not returning the resource as-it-currently-is, but rather as-it-was-before-the-call-executed.

Let's bump to b3 though, as we might want to be semi-consistent with #1196 (e.g. use `data` in both)?

**Comment by rachelbaker** [comment]
Punted to Beta 4

**Comment by danielbachhuber** [comment]
After a little bit of discussion, we're going to return the original resource instead of wrapping it in a `data` object.

**Comment by danielbachhuber** [comment]
:ship: :ship:
