### ISSUE TITLE
Post Meta error during post creation

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/WP-API#1294]
Hi!

I'm trying to create a new post of a cpt via api, but I get an error about post metas. Actually, the new post is been published but I get

```json
[
{
"code": "json_meta_post_mismatch",
"message": "Meta does not belong to this object"
}
]
```

I try to post a json like this:

```json
{
    "title": "Hello World!",
    "content_raw": "blablabla",
    "excerpt_raw": "blabla",
    "type": "mycustomtype",
    "status": "private",
    "post_meta": [
        {
            "key": "firstmeta",
            "value": "value1"
        },
        {
            "key": "secondmeta",
            "value": "value2"
        }
    ]
}
```

When I check on the backend, I see the first post meta of the array correctly posted, I tried with 4, 3 and 2 post metas and still happens. Changing the order of the metas still populates only the first post represented within the array.

I'm on 1.2.2.

Ideas?

**Comment by enricodeleo** [comment]
** Update **
I still have problems with post_meta. Even if I use just one post_meta like so

```json
{
    "title": "device name",
    "content_raw": "Random text",
    "excerpt_raw": "Random excerpt",
    "type": "registered_device",
    "status": "private",
    "post_meta": [{
        "key": "token",
        "value": "7y98q29ieqowhadh"
    }]
}
```

I still get the error above AND I noticed that the action `json_insert_post` isn't triggered even if the post is actually created in WordPress.

Will it be fixed or do I have to upgrade to 2.0? I tried but my custom endpoints didn't work and I don't know how to update them to the new api (can you please point me to an example or a documentation?).

Thank you in advance!

**Comment by cgrymala** [comment]
In my experience, I've found that I have to run a separate API query to update the meta; it doesn't seem to work with the post insert/update process (I'm not sure if that's intentional or not).

What I've had to do is insert the post, retrieve the ID of that new post, then run a separate meta request for each meta I want to insert with the post.

So, in answer to your question, I'd say that the (temporary at least) solution is to run separate API requests for the post insertion/update, and for each of the meta fields you're trying to insert/update.

However, I'd also like to add that I am certainly able to reproduce this issue (no custom meta data I send will get inserted/updated if I try to do so through the actual post insertion/update process).

**Comment by adalberth** [comment]
Me neither. I can't seem to update post meta (using the syntax above).

**Comment by oliviercardoen** [comment]
Me neither. After debugging for a bit, it seems to me that $id and $mid are the same (at https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-meta.php#L131), which cause the problem we are experiencing.

Sorry if I'm wrong and misleading anyone ;-)

**Comment by oliviercardoen** [comment]
Is anyone using Pods Framework? Or some plugin using the 'add_post_metadata' filter?
My problem has been solved when disabling the plugin returning a non-null value through this filter. I can create my post meta without any returned error from the API.

I hope this might help.

**Comment by enricodeleo** [comment]
@oliviercardoen yes I'm using pods framework. I'll try asap without this plugin and let you know!

**Comment by oliviercardoen** [comment]
@enricodeleo OK then. It solved the issue for me and I switched to ACF + Custom Post Type UI.

**Comment by cgrymala** [comment]
In my case, I am not running PODS, but I am running Types on some of my sites. It's remotely possible that that's interfering with the process somewhere along the line.

**Comment by oliviercardoen** [comment]
@cgrymala I don't think the problem is coming specifically from Pods but from the use of the filter 'add_post_metadata', which is fired each time a post meta is added.

Types might cause the same issue as Pods, by adding some treatment at this point in the process. All plugin managing custom post types and custom fields might cause that kind of error.

However, ACF seems to work just fine.

**Comment by oliviercardoen** [comment]
Note: More on the 'add_post_metadata' filter: http://hookr.io/filters/add_post_metadata/

**Comment by pglewis** [comment]
Anyone having integration issues with Pods: it helps to report your issues with us.  

https://github.com/pods-framework/pods/issues
https://github.com/pods-framework/pods/issues/3362
