### ISSUE TITLE
post_meta not updated... but have another entry

### ISSUE THREAD

**Issue by eduplessis** [WP-API/WP-API#1339]
When creating a post, I put some post_meta 

here is the code for the creation edition and deletion of a post
https://gist.github.com/eduplessis/dc530523f0b98ae233dc

and here is the result of the post_meta when it's created

     Array(
    
    [time_client_email] => Array
        (
            [0] => email@client..com
        )

    [time_client_website] => Array
        (
            [0] => clientwebsite.com
        )
    )

When I update it here is the result

    Array(
    [time_client_email] => Array
        (
            [0] => email@client..com
            [1] => email@client..com
        )

    [time_client_website] => Array
        (
            [0] => clientwebsite.com
            [1] => clientwebsite.com
        )
    )

My question is : 

is it because of the revision....

or something is wrong....

because I think the desirable result would be ... if exist and the same value "do nothing" .... if exist and not the same value "replace"

**Comment by cgrymala** [comment]
The problem is, it's perfectly valid for the same key to be used to reference multiple values when you're talking about post meta. The `add_post_meta()` function accepts an optional fourth parameter telling WordPress whether the key/value pair you're sending to the database should be "unique" or not; if the `unique` parameter is set to `true`, and that key already exists in the database, `add_post_meta()` returns `false` without changing anything; if `add_post_meta()` is used in its default manner, it will simply add another value with a duplicate key.

So, all that to say that the issue you're experiencing is actually a valid use-case within WordPress.

I'm not sure if there's a better way to solve this problem (it would be nice if there was a simple way to tell the API that you want to update an existing key/value pair, rather than adding a new key/value pair), but the way I've solved it is to run a query to retrieve the post meta before I try to update it.

That looks something like:

```php
<?php
// First, retrieve the meta data that already exists for the post we're updating
// Assume that $url is in the format of: http://example.org/wp-json/wp/v2/posts/{post_id}/meta
$original = wp_remote_get( $url, array( 'headers' => $headers, 'body' => '' ) );
$original = @json_decode( wp_remote_retrieve_body( $original ) );

// Loop through a list of the metadata we're updating
foreach ( $meta as $m ) {
	// Assume that the $url variable is set to the appropriate URL to add/update meta on this post
	// That URL structure might look like: http://example.org/wp-json/wp/v2/posts/{post_id}/meta
	$u = $url;
	
	// Now, loop through each of the meta data fields that already exist for the post we're updating
	foreach ( $original as $o ) {
		// If the key for this piece of meta doesn't match the key for the piece of meta we're updating, skip to the next key
		if ( $o->key != $m->key )
			continue;
		
		// If the keys do match, add a slash, followed by the meta ID to the end of the URL
		// The URL format now looks like: http://example.org/wp-json/wp/v2/posts/{post_id}/meta/{meta_id}
		if ( $o->key == $m->key ) {
			$u .= '/' . $o->id;
			$m->id = $o->id;
		}
	}
	
	// Add query args for the meta key and the meta value to the URL
	// The URL now looks like: http://example.org/wp-json/wp/v2/posts/{post_id}/meta/{meta_id}?key={meta-key}&value={meta-value}
	$u = add_query_arg( array( 'key' => urlencode( $m->key ), 'value' => urlencode( $m->value ) ), $u );
	// This is possibly superfluous, as we are sending the meta ID as part of the URL itself, but I'm doing this just in case
	if ( property_exists( $m, 'id' ) ) {
		$u = add_query_arg( 'id', intval( $m->id ), $u );
	}
	
	// Assume the $headers array contains all of the appropriate headers to be sent in a meta update POST request
	$args = array( 'method' => 'PUT', 'headers' => $headers, 'body' => '' );
	// Submit the request to update the meta data
	$tmp = wp_remote_request( $u, $args );
}
?>
```

**Comment by eduplessis** [comment]
Perfect thanks @cgrymala

**Comment by cgrymala** [comment]
Just noticed 1 minor issue in my original code.

If the meta key doesn't exist, the API won't do anything with it, as the API _requires_ a `POST` request when adding new meta, and _prefers_ a `PUT` request when updating meta. 

Therefore, near the end, the following line:

```php
$args = array( 'method' => 'PUT', 'headers' => $headers, 'body' => '' );
```

Should be more like:

```php
$args = array( 'method' => ( property_exists( $m, 'id' ) ? 'PUT' : 'POST' ), 'headers' => $headers, 'body' => '' );
```

That causes the script to use a `POST` request if the meta key *doesn't* already exist for the content you're trying to update, but it will use a `PUT` request if the meta key *does* already exist.
