### ISSUE TITLE
try to query posts by post meta and custom post type

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#1352]
hi everyone, i try to get post by post meta and custom post type, does anyone can solve this problem?

**Comment by nareshbhatia** [comment]
I am running into the same issue. I have a CPT, with slug named `news_item`. What is the correct way to query for this CPT in v2? I tried the following:

    http://vagrant.local/wp-json/wp/v2/posts?type[]=news_item

What I get back is posts of type `post`, not `news_item`.

**Comment by joneslloyd** [comment]
Hey guys,

Using my Custom Post Type of "the_event", I did this on the V2 API to query custom post types:

    add_action( 'init', 'add_events_to_json_api', 30 );
    function add_events_to_json_api(){
		
		global $wp_post_types;
		$wp_post_types['the_event']->show_in_rest = true;
		$wp_post_types['the_event']->rest_base = 'the_event';
		$wp_post_types['the_event']->rest_controller_class = 'WP_REST_Posts_Controller';
	}

**Comment by nareshbhatia** [comment]
Does this mean that Custom Post Types are not yet supported by the v2 API or will we always have to do it this way? Reading v1 documents, it seems that it was possible.

P.S. I am new to WP and the JSON API, so apologize for asking obvious questions.

**Comment by joneslloyd** [comment]
I believe (from what I've asked the developers here) they're not 'natively' supported - so workarounds like above are needed.

You can make it automatic though, just by getting all custom post types into an array, and looping through them and foreach one, take this part:

    global $wp_post_types;
    $wp_post_types['the_event']->show_in_rest = true;
    $wp_post_types['the_event']->rest_base = 'the_event';
    $wp_post_types['the_event']->rest_controller_class = 'WP_REST_Posts_Controller';

And just insert the custom post type name variable instead of 'the_event'.

**Comment by nareshbhatia** [comment]
Thanks @joneslloyd. Where exactly would this code go? Will it become part of the plugin, i.e. will I need to modify the plugin itself?

**Comment by joneslloyd** [comment]
In functions.php of your theme, or your own plugin :)

**Comment by nareshbhatia** [comment]
Awesome! Thanks.

**Comment by Lenewtype** [comment]
This solution -doesn't- show custom field values though, correct? I'm using the Advanced Custom Fields plugin and am not seeing anything outside of the generic post metadata in my response json.

**Comment by joneslloyd** [comment]
I've written a post about how to get the meta data:
https://bay-a.co.uk/wordpress-tips/wp-api-v2-tips/

You'd obviously replace the meta you want with the ACF meta.

**Comment by phamdacloc** [comment]
This worked out of the box for me without any modification to my theme or requiring new plugin:
/wp-json/wp/v2/posts?filter[category_name]=<category_slug>

**Comment by monecchi** [comment]
My WordPress site makes use of a `food_menu` custom post type, for which two custom taxonomies `food_menu_categories` and  `food_tag` are assigned (registered). So in order to get/query the posts from the custom post type, I've tried the following with a successful response:

**My use case scenario:**

`food_menu` = custom post type
`food_menu_categories` = custom taxonomy registered for `food_menu`post type (acts like categories)
`food_tags` = custom taxonomy registered for `food_menu`post type (acts like tags)

All the above was set up with `'show_in_rest' => true,` so that the custom post type and taxonomies could be exposed to the WP REST API

--//--

Get all posts of type **food_menu** - no filtering

```
http://example.com/wp-json/wp/v2/food_menu
```

Get all posts of type **food_menu** from a specific category (taxonomy), which for this specific use case scenario would be pulled from **food_menu_categories**

```
http://example.com/wp-json/wp/v2/food_menu?filter[food_menu_categories]=dinner
```

Under the registered `food_menu_categories` taxonomy I created a few categories, such as breakfast,  lunch, dinner etc. The example above allows me to get everything that belongs to the specified category.

Get all posts of type **food_menu** from a specific tag (taxonomy),which for this specific use case scenario would be pulled from **food_tag**

```
http://example.com/wp-json/wp/v2/food_menu?filter[food_tag]=barbecue-sauce
```

Under the registered `food_tag` taxonomy I created a few tags, such as tomato sauce, bacon, barbecue sauce etc. The example above allows me to get posts of type `food_menu` that belongs to the specified tag.

I've tried the above examples on the V2 API with no extra functions needed to make it work.

**Comment by Shobby** [comment]
API not showing Posts from Post Type even i have defined in the parameter as follows
   
       <?php

     // Get the JSON
     $json = file_get_contents('http://coralgableschamber.org/wp-json/posts?filter[posts_per_page]=1&filter[post_type]=events');
     // Convert the JSON to an array of posts
     $posts = json_decode($json);
    foreach ($posts as $p) {
      echo '<p>Title: ' . $p->title . '</p>';
      echo '<p>Date:  ' . date('F jS', strtotime($p->date)) . '</p>';
    // Output the featured image (if there is one)
      echo $p->featured_image ? '<amp-img src="' . $p->featured_image->guid . '" width="150" height="110"></amp-img>' : '';

      echo '<p>Content: ' . $p->content. '</p>';    

        }
