### ISSUE TITLE
v1: getting multiple posts by id

### ISSUE THREAD

**Issue by oskarrough** [WP-API/WP-API#1368]
Hi, how do you query multiple posts of a certain type by ID? I tried:

`/posts?type=myposttype&filter[page_id]=1&filter[page_id]=2`

which doesn't work. There are also some non-working examples here https://wordpress.org/support/topic/get-multiple-postsmedia-by-id - any help would be appreciated, thanks.

**Comment by awojtczyk** [comment]
Hi there,
try this:
GET /wp-json/posts?filter[p]=490,899&type[]=case&type[]=change

type is optional if it is not a custom post type.

Please, let me know if that helped.

**Comment by oskarrough** [comment]
Hey, thanks but it only returns the first ID specified.

**Comment by danielbachhuber** [comment]
You can use the `filter[post__in]` (which authenticated) to get specific posts.

**Comment by abobwhite** [comment]
@danielbachhuber Neither of the above solutions using `filter[p]` nor `filter[post__in]` is working to retrieve multiple posts by id.

**Comment by ErickaGonzalez** [comment]
@abobwhite do you have the solution?

**Comment by kadamwhite** [comment]
With V2 you should pass an `?include[]=1&include[]=2` parameter _e.g._ to get posts with IDs 1 & 2

**Comment by ErickaGonzalez** [comment]
Thanks @kadamwhite it works!

Example V2:
http://demo.wp-api.org/wp-json/wp/v2/posts?include[]=496&include[]=503

**Comment by dmsdesignz** [comment]
this is not working anymore?

**Comment by kadenmclaws** [comment]
@dmsdesignz Well.... sort of works. 

http://demo.wp-api.org/wp-json/wp/v2/posts?include[]=496&include[]=503
doesn't work because those posts don't exist. Only 1 post exists.

For example:
http://demo.wp-api.org/wp-json/wp/v2/posts?include[]=1 //Gets post 1
http://demo.wp-api.org/wp-json/wp/v2/posts?include[]=2 //Returns empty
http://demo.wp-api.org/wp-json/wp/v2/posts?include[]=1&include[]=2 //Gets post 1 only

**Comment by Tecdoc** [comment]
Think it works - because there are post ids 1 and 35, it may be due to the original example posts being deleted.  You may need to search http://demo.wp-api.org/wp-json/wp/v2/posts and see what post ids are available.  

Example both 1 and 35 exists within http://demo.wp-api.org/wp-json/wp/v2/posts:
http://demo.wp-api.org/wp-json/wp/v2/posts?include[]=1&include[]=35 gets both posts
