### ISSUE TITLE
Getting Big Json Responses with AngularJS

### ISSUE THREAD

**Issue by fclaussen** [WP-API/WP-API#1369]
I'm working on a site that have 520 speakers. On the header of the site there is a button that display all the speakers, filtered by the last name first letter.

Example with A clicked: A B C D ... Andrea Angela Andre ...

The problem is that I'm getting all the speakers with my json call and it's 520 speakers! It is taking as long as 20 seconds to get them all on my localhost.

I'm using WP-API to fetch the result. I imagine WP-API is making a WP_Query to the database with my request but since it is too big it is taking too long. The development server crashes when I try this. Probably a memory issue.

Any Ideas?

```javascript
app.controller('NavigationController', ['$scope', 'SpeakersService', function($scope, SpeakersService){
    SpeakersService.success(function(data){
        $scope.speakers = data;
    });
}]);

app.factory('SpeakersService', ['$http', function($http){
    return $http.get(SSL.home_url + 'wp-json/posts?filter[posts_per_page]=-1&type[]=speakers').success(function(data){
        return data;
    });
}])
```

**Comment by royboy789** [comment]
why don't you only call those with a search so add a filter for search and search for the letter, should minimize some of it.

You could also tap into `json_prepare_post` filter and get rid of posts that don't start with the letter you pass so the JSON return object is smaller.

**Comment by kadamwhite** [comment]
`filter[posts_per_page]=-1` is another part of the problem: you may save a little bit of time if you chunk that out into multiple smaller requests. That will be much easier for the server, as well. This code may not work out of the box with the newer versions of the API, and it certainly isn't native angular, but I wrote a JS example of how to assemble a full collection from multiple pages of response here: https://github.com/kadamwhite/wordpress-rest-api#working-with-paged-response-data

Another option to consider, if you just need the names & some other data, would be to make a custom endpoint. You could see whether it's possible to get them all in one go (moving less data around *might* improve things, but it's still a very heavy query: that's why `-1` is often advised against), or make an endpoint that you could query for batches, e.g. by letter or by other signifier, so that you can manually assemble a list from multiple requests.

**Comment by kadamwhite** [comment]
@fclaussen Have you made any progress on the workarounds suggested? Are you still encountering this issue?

**Comment by fclaussen** [comment]
HI @kadamwhite . I'm sorry I missed your response.

I managed to extend the API to get the information I needed in chunks.

I created a custom endpoint for the speakers. So I can call /speakers/a and get everyone that have a Lastname starting with A.

On my angular code I have a foreach running through the alphabet and loading the current letter.

It is working perfectly and it's pretty fast.

Thank you for your assistance.
