### ISSUE TITLE
Taxonomies not discoverable due to "rest_base" prefix

### ISSUE THREAD

**Issue by jdolan** [WP-API/WP-API#1381]
Some taxonomies are treated specially in the API, such that they have a `rest_base` endpoint prefix that is never published via the `taxonomies` endpoint. Example: Tags.

The `taxonomies` response for Tags looks like this:

    {
    "name": "Tags",
    "slug": "post_tag",
    "description": "",
    "labels": {
        "name": "Tags",
        "singular_name": "Tag",
        "search_items": "Search Tags",
        "popular_items": "Popular Tags",
        "all_items": "All Tags",
        "parent_item": null,
        "parent_item_colon": null,
        "edit_item": "Edit Tag",
        "view_item": "View Tag",
        "update_item": "Update Tag",
        "add_new_item": "Add New Tag",
        "new_item_name": "New Tag Name",
        "separate_items_with_commas": "Separate tags with commas",
        "add_or_remove_items": "Add or remove tags",
        "choose_from_most_used": "Choose from the most used tags",
        "not_found": "No tags found.",
        "menu_name": "Tags",
        "name_admin_bar": "post_tag"
    },
    "types": [
        "post"
    ],
    "show_cloud": true,
    "hierarchical": false
    }

An intelligent guess might use the `slug` as the Tags endpoint prefix, but alas, Tags use a hard-coded `rest_base` property ("tag") instead. Category also has a `rest_base`, but through sheer luck it is the taxonomy's slug ("category").

This means there's literally no way to logically map the Tags taxonomy to the Tags endpoints. Yes, the routes are published at the API index, but that's simply a flat listing of "here's a bunch of URLs that probably have some data." There's absolutely no logical association between the Taxonomy and its endpoint URLs.

The `rest_base` property should either be included in the Taxonomy response, or it should be dropped in favor of simply using the slug -- since that's precisely what slugs are for. I'm not sure what `rest_base` is accomplishing besides breaking the alignment of data.

**Comment by jdolan** [comment]
In addition, the post-terms endpoints _DO_ use the taxonomy `slug`:

`POST` -> `/wp/v2/posts/${post_id}/terms/post_tag/${term_id}`

This is just more motivation to do away with `rest_base` if you ask me.

**Comment by rachelbaker** [comment]
@jdolan Thank you for the feedback on the `rest_base` oddities.

@danielbachhuber Any objection to including the `rest_base` in the Taxonomy response?  I know how you dislike the `post_tag` slug :)

**Comment by danielbachhuber** [comment]
> Any objection to including the rest_base in the Taxonomy response?

:+1: from me

**Comment by jdolan** [comment]
I get that "post_tag" is odd looking, but inventing a property just to mask that interpretation of the data smells wrong. Slug is _for_ URLs. That's literally its purpose. Why reinvent the wheel? Also, the taxonomy slug is in use in other routes. It should be all or nothing, and personally, I don't know if `rest_base` has a very strong case.

**Comment by danielbachhuber** [comment]
> Why reinvent the wheel?

Because custom taxonomy and custom post type slugs can conflict in the REST API. `rest_base` allows you to avoid collisions specifically within REST API scope.

**Comment by jdolan** [comment]
`/terms/{taxonomy_slug}` -> Terms in a Taxonomy
`/posts/{post_id}/terms/{taxonomy_slug}` -> Terms in a Taxonomy for a given Post.

How would they collide? Genuinely asking.

**Comment by danielbachhuber** [comment]
> How would they collide? Genuinely asking.

Hm... my memory serves incorrectly then. They don't conflict, as the endpoints are currently registered.

I think there are two issues you're bringing up:

1. Is it worthwhile to have a `rest_base` registration argument?
1. Should we rename `post_tag` to `tag` for the REST API?

I spent ~10 min looking for the Github issue with this discussion for the first, but couldn't find it. `json_base` was introduced in #820.

For the second, there's a couple examples of prior art:

1. WordPress core defaults to `domain.com/tag/apple` in permalinks, not `domain.com/tag/post_tag`
1. Across the board with the REST API, we've taken a liberal, deliberate approach to renaming attributes, etc. For example, `post_title` is now `title`, and `user_nicename` is now `slug`.

Generally, we've approached the problem as "what is a clean, sensible abstraction?" instead of "what database design decisions do we need to propagate through the API?"

To reply to original question:

> I get that "post_tag" is odd looking, but inventing a property just to mask that interpretation of the data smells wrong. Slug is for URLs. That's literally its purpose. Why reinvent the wheel?

We aren't inventing a property solely for "mask[ing] that interpretation of the data"

**Comment by jdolan** [comment]
But, if users want "post_tag" to be "tag", they should change the Taxonomy's slug in their Settings:

<img width="1241" alt="screen shot 2015-07-06 at 11 14 04 am" src="https://cloud.githubusercontent.com/assets/643118/8525643/2af5a474-23d0-11e5-9393-02b4f42f9bd9.png">

And then it would be consistent in the API and the frontend of the site (assuming the API just used "slug" everywhere).

The issues I really meant to raise with this ticket are:

1. `rest_base` is never exposed to consumers of the API, leaving them with no way to find Terms.
2. `rest_base` is only used on one endpoint, everywhere else uses `slug`.
3. `slug` is for URLs, and they are inherently unique. Why use anything else?

**Comment by jdolan** [comment]
Btw, aliasing properties for usability is one thing (`post_title`). Introducing [superfluous?] ones and using them in some spots but not others probably isn't. That's all I'm saying.

**Comment by rmccue** [comment]
@joehoyle has started on this, so assigning to him, but bumping from B4 as it's not ready yet.

> aliasing properties for usability is one thing

In lots of places, tags are referred to as tags. All user-facing documentation calls them "tags". The internal name is `post_tag`, but part of what we're doing with the API is papering over these internal implementation details to end up with a more consistent developer experience. You shouldn't need to know that the internal stuff is called `post_tag`.

(As for WP devs who *do* know that, they already need to deal with inconsistency. The WP Query params are `tag`, `tag_id`, `tag__in`, `tag__not_in`, `tag__and`, `tag_slug__and` and `tag_slug__in`. I didn't even realise that the taxonomy slug happened to be `post_tag` until I started working on this.)

As for the points above:
> `rest_base` is never exposed to consumers of the API, leaving them with no way to find Terms.

They definitely should be via links, and we need to link from the taxonomy details to the terms.

> `rest_base` is only used on one endpoint, everywhere else uses `slug`.

This should now be fixed with #1447 and #1430. If you see any other spots where we use it, let us know.

> `slug` is for URLs, and they are inherently unique. Why use anything else?

The `slug` is for publicly-facing URLs, which are controlled by the site owner/maintainer. If you want to make your URLs look nice and pretty, you can set them to whatever you want to fit with your site's branding.

The API on the other hand is meant to be consistent for developers interacting with the site. That's why we work with pretty permalinks off, as well as all sorts of other crazy stuff, yet we keep it pretty consistent regardless. As a client developer, I shouldn't need to care if the site owner calls categories `sections` instead (although by looking up `/taxonomies`, I might be able to adjust my UI wording).

Thanks for raising these issues. Let's get them fixed. :)
