### ISSUE TITLE
The request was redirected to 'DOMAIN/wp-json/users/2', which is disallowed for cross-origin requests that require preflight.

### ISSUE THREAD

**Issue by PhilippSchreiber** [WP-API/WP-API#1394]
Hey there,

we are using WP-API as Backend for a hybrid app. We managed to add all the headers related to CORS and it finally works. One Problem still exists: When calling /wp-json/users/me with correct authentication the request gets redirected to /wp-json/users/ID. This is disallowed for cross-origin requests that require preflight.

We can easily fix it by removing the Location header from "get_current_user" in "class-wp-json-users.php". 

What is the reason for this redirect? I've seen that this causes another issue (#1365). Perhaps it is possible to remove the redirect completely?

Cheers and thank you
Philipp

**Comment by rmccue** [comment]
The `Location` header indicates that the canonical location for the current user is at a different URL, and that the current URL is only an alias for that. If you're in a context where you can't get the response back without following redirects, you can instead use enveloping to get back the headers in the body; just add `?_envelope` to the URL.

CORS headers should be handled natively by the latest versions (1.2+) of the REST API, and are also handled in v2, so you shouldn't need to add those manually. If you run into any problems with those, please file an issue, since that's a bug. :)
