### ISSUE TITLE
Allow Cross-domain requests

### ISSUE THREAD

**Issue by austincondiff** [WP-API/WP-API#144]
I am unable to make a request from a separate domain. Is this supported by this plugin? I am developing an AngularJS app locally and I am having trouble requesting data from my live Wordpress site.

**Comment by krewmarco** [comment]
BTW, if using application passwords and  angular, you set $httpProvier.defaults.withCredentials = true, you might find your user is being set to 0 if you did not send a nonce.   That's because youre telling the API youre using cookie-auth which requires a nonce (Check rest-api.php rest_cookie_check_errors() ).  Remove withCredentials and it does what you expect.  Save someone some hours...

**Comment by krewmarco** [comment]
Since 4.4.0, I believe the right way to enable CORS is
add_filter('http_origin', function() { return "http://your domain";});
see wp-includes/rest_api.php rest_send_cors_headers() .  Seems to work fine.

**Comment by createbuildship** [comment]
where do you add add_filters?

**Comment by kadamwhite** [comment]
@frontr-uk in your theme or plugin code.
