### ISSUE TITLE
Return Fields Parameter in API

### ISSUE THREAD

**Issue by stonetip** [WP-API/WP-API#1564]
The Return Fields Parameter section of http://codex.wordpress.org/Class_Reference/WP_Query#Post_.26_Page_Parameters would suggest this is possible. I can't, however, get that to work or find any examples when using the API. So I assume this is not yet a feature. It would sure be great if it was. For example, in one request using a post ID the only return value needed is the slug. It's a lot of unnecessary load on the client/server/network to also return an entire post's content.

(If this is not the right avenue for this request please let me know what is).

Thanks,
Jon

**Comment by rachelbaker** [comment]
@stonetip You are correct, we do not support the `fields` param for WP_Query.  Even if we did, that wouldn't allow you to return just the `slug` for a given `ID`, since `post_name` (aka `slug`) isn't a supported Returned Fields param: http://codex.wordpress.org/Class_Reference/WP_Query#Return_Fields_Parameter

To limit a response, per your example, while reducing the server load would require a custom endpoint.  We do offer a filter to modify the response data, but that would only reduce the API response not the server/database load: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L1095
