### ISSUE TITLE
Draft posts not showing on posts endpoint for logged in user

### ISSUE THREAD

**Issue by itibook** [WP-API/WP-API#1620]
Hello,

please correct me if I am wrong, but I would expect that in the posts endpoint all posts should show up for an authenticated user (admin in this case) regardless of their draft/publish status.

Right now I get only the published posts and if I want the draft ones I need to add the filter[post_status]=draft.

This is not consistent in my opinion with the behaviour of the WP dashboard where the admin gets to see all the posts and can then filter based on the status.

ciao

Luca

**Comment by joehoyle** [comment]
@itibook this is by design, the `/posts` has a `status` param with a default value of `publish`. We don't typically change the default parameters based off what permissions you have. Those are typically statically declared.

The behaviour is not meant to be consistent with the admin interface, but rather internally consistent and with REST principle and practices in general.
