### ISSUE TITLE
Incorrect results for /users/me endpoint

### ISSUE THREAD

**Issue by phamdacloc** [WP-API/WP-API#1640]
I'm encountering inconsistent data returned from `/wp-json/wp/v2/users/me` endpoint when extending the response.  The `get_current_user_id()` always return 0 (which is an invalid user).

Here's how I coded the response extension:

```php
add_action( 'rest_api_init', 'user_register_meta' );
function user_register_meta() {
    register_api_field( 'user',
        'userData',
        array(
            'get_callback'    => 'get_user_meta_info',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}

function get_user_meta_info( $object, $field_name, $request ) {
	$currentID = get_current_user_id(); // This ALWAYS returned 0
	return get_userdata($currentID)->data;
}
```

Prior to calling this endpoint, I had already logged-in and passed the accessToken when invoking `/wp-json/wp/v2/users/me` endpoint.

This is the result response which I got back:
```php
{
    "_links" =     {
        collection =         (
                        {
                href = "http://ninsutu.com/wp-json/wp/v2/users";
            }
        );
        self =         (
                        {
                href = "http://ninsutu.com/wp-json/wp/v2/users/1";
            }
        );
    };
    "avatar_urls" =     {
        24 = "http://2.gravatar.com/avatar/29b3ef85f13fedb43f84e6cb4a634e73?s=24&d=mm&r=g";
        48 = "http://2.gravatar.com/avatar/29b3ef85f13fedb43f84e6cb4a634e73?s=48&d=mm&r=g";
        96 = "http://2.gravatar.com/avatar/29b3ef85f13fedb43f84e6cb4a634e73?s=96&d=mm&r=g";
    };
    description = "Just a typical developer";
    id = 1;
    link = "http://ninsutu.com/author/admin/";
    name = "Ninsutu Staff";
    url = "http://nguoibanxu.com";
    userData = "<null>";
}
```

The user id which returned in the response is 1, but `get_current_user_id()` returns 0.

I did not have this problem when registering other object types such as 'post': 
`register_api_field('post', $attribute, $arg)`

**Comment by joehoyle** [comment]
@phamdacloc that's very odd - I tried just doing the same thing (copied your code) and it worked fine. I'm using the Basic Auth plugin however. It's odd though because `/me` will only work if `get_current_user_id` returns the user, so the user must be set in WordPress.

The only way I can see this is that something else is unsetting the current user before your `get_user_meta_info` is called. This might be a case of debugging in the code until you narrow down where the current user is being unset.

**Comment by phamdacloc** [comment]
`something else is unsetting the current user before your get_user_meta_info is called'
That could be a possibility, but the response still came back with the correct `id = 1`.

I'm using "WP OAuth Server" plugin by Justin Greer which supports OAuth 2.0 and enabled "User Credentials" Grant Type. My application first login using username/password then subsequently access the site using accessToken thereafter. It seems like only `users/me` endpoint is having this problem, none other object type has this problem which is really troubling.

**Comment by ryanjkelly** [comment]
I was getting the same limited result using the `users/me` endpoint with cURL. What fixed it for me was adding `context=view` to my query string.

**Comment by phamdacloc** [comment]
Unfortunately, the added `context=view` made no difference on my system.

**Comment by joehoyle** [comment]
@phamdacloc ahh that may explain it, as far as I know "WP OAuth Server" isn't going to grant you correct permissions to the REST API (these two projects are not related), however I'll let @rmccue clarify that.

**Comment by ryanjkelly** [comment]
@phamdacloc sorry, ya I was using basic authentication.

I just added OAuth authentication to my setup. I'm using 3-legged OAuth and get my tokens just fine, but I seem to be having a hard time making authenticated requests.

I get the "rest_not_logged_in" notice when I perform an HTTP GET request to `/wp-json/wp/v2/users/me`.

This is my "Authorization" header field. I've changed some values to mask the real keys/tokens.

```
Authorization: OAuth realm="", oauth_consumer_key="icbI6uQSvQCt", oauth_nonce="3a6ced9078a09daac453a661b9c4859c", oauth_signature="SxH39uVyrJ7IOhMQzC95ZqHvhHs%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1446018663", oauth_token="X3EDZEnuXlwrAqjxq945OW6c", oauth_version="1.0"
```

I guess my question is... should I keep troubleshooting, or is there a known permissions issue between the WP OAuth system and the REST API and I should wait for a fix?

**Comment by equatorapps** [comment]
Definitely something to do with /v2/users/me. If I use /v2/users/{id} then it works as expected. I am also using oAuth 2.0 "client_credentials" or "password" grant_type via the WP OAuth Server plugin.

**Comment by conorw** [comment]
FWIW, I am having the same issue as well using JWT Authentication for WP REST API i.e. when making a request to /users/me with an authorization token I can only get the 'embed' data back (even if I specify context=view). It will however give me back the 'view' data if I call /users/{id}.

**Comment by rmccue** [comment]
The errors most of you are experiencing are likely due to the redirection that happens on `/users/me`. `me` isn't a real resource, it's just a pointer to the real user, so it issues a 302 redirect with a Location header back. Some clients don't resign the request when redirecting, and this will cause an error.

Two solutions to this:
1. Change your OAuth client to resign requests on redirections
2. Add `?_envelope` to envelope the request, which gives you a 200 OK with the real status, headers, and data in the body.

Note however that we don't official support OAuth 2.0 or the WP OAuth Server plugin, we only support the [OAuth 1.0a](https://github.com/WP-API/OAuth1) plugin.

**Comment by cyga** [comment]
I faced similar problem:
* get_current_user_id returned 0
* wp_get_current_user returned null

It was after after standard web login and load of the page:
/wp-json/wp/v2/users/me

Following code helped me:
get_current_user_id() || apply_filters( 'determine_current_user', false );

I wrapped it in separate function and call it from 2 other places of WP-API plugin. Because while debugging  I saw get_current_user_id() == 0 at permissions check. For route /wp-json/wp/v2/users/ID (ID = 1 in my case).

I quickly checked parts of the wp_get_current_user code (of the latest version). Will try to check version on my server and start with get_current_user_id

**Comment by kish2011** [comment]
I am still facing this in Rest API v2 get_current_user_id() = 0 even after doing a login using rest api.

**Comment by origamid** [comment]
That worked for me:

Set the variable **outside your function**.
`$user = get_current_user_id();`

Inside the function to register the api, call it as a global variable
`global $user;`

Thats in case you gonna register a custom Endpoint
