### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by mocheaz** [WP-API/WP-API#1673]
I'm trying to get 30 or so posts by categories like this:
http:/example.com/wp-json/posts/?filter[posts_per_page]=30&filter[order]=desc&filter[category_name]=category%20name&type[]=post

this is working but it's sooooo slow (more than 20 seconds).

What i'm doing wrong? Ot is there any way to get it faster?

**Comment by danielbachhuber** [comment]
> What i'm doing wrong?

There's likely some slow code execution on your server as it fetches posts.

>  Ot is there any way to get it faster?

Try disabling your plugins one by one to see if it's caused by a plugin. Alternatively, switch to one of the default WordPress themes to see if it's caused by your theme.

The slowness is most likely coming from code unrelated to the API.
