### ISSUE TITLE
last-modified Header

### ISSUE THREAD

**Issue by storynory** [WP-API/WP-API#1730]
Is there a way to add a last-modified header to the json response?  It would be useful for caching on a remote server.  Thanks.

**Comment by rmccue** [comment]
We used to have Last-Modified headers, but unfortunately, we can't accurately make assertions about the modified time of the post. This is due to meta fields, terms, etc, which usually doesn't bump the modification time of the post. We decided it's better to send no headers than to send inaccurate ones.

Thanks for the feedback!

See also #566.
