### ISSUE TITLE
Extending contexts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1797]
Are we supporting custom contexts? If so, what are the corresponding best practices?

Related #1796

**Comment by danielbachhuber** [comment]
After discussion, we'be decided our core controllers will only support embed, view, and edit, and will validate to ensure context is set to one of those values.

**Comment by kadamwhite** [comment]
We also have `context=help` as well; that may make more sense long-term to move away from context in favor of a standalone parameter, but that's a separate discussion. What is relevant to this issue is to ensure that help information (schema) is still available following the changes discussed here.

**Comment by danielbachhuber** [comment]
We've added validation for the `context` param in #2180, which suits the need I opened the issue for originally.

Custom plugins can have whatever contexts they want in their routes. `wp/v2` will only have `embed`, `view`, and `edit`.

**Comment by psalz** [comment]
Has the official stance on this changed? Because the [current implementation](https://github.com/WP-API/WP-API/blob/bb690484495e3b502e4a20c55da7d311b67091ef/lib/endpoints/class-wp-rest-controller.php#L295) allows to set arbitrary contexts on custom fields (no matter the route).

Edit: Nevermind, I was toying with this after filing #2694, where I still had the `rest_api_init` hook on `-1` priority - which I assume is an antipattern.
