### ISSUE TITLE
How do I retrieve users with a custom taxonomy associated to them?

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#1902]
I have a custom taxonomy set up and registered in the rest api. 

I can confirm this by going to mysite.dev/wp-json/wp/v2/custom_tax

However, this taxonomy is only registered on the user object. When I try the /users/custom_tax=term

It retrieves all users even though only one user has that term. 

How can I expose the custom taxonomies on the users endpoint?

Happy holidays, btw. I love what you guys are doing.

**Comment by danielbachhuber** [comment]
> It retrieves all users even though only one user has that term.

Right — the REST API doesn't support user taxonomies because core doesn't formally support them. Here's a Trac ticket with relevant details: https://core.trac.wordpress.org/ticket/31383

You can look at `WP_REST_Posts_Terms_Controller` for an example of how you might write something similar for users.

**Comment by rafasashi** [comment]
I did post a work around here:
http://wordpress.stackexchange.com/a/246148/37412
