### ISSUE TITLE
Update Users::get_item_permissions_check() to respect publish count for all REST API-visible post types

### ISSUE THREAD

**Issue by rajesh-h** [WP-API/WP-API#2128]
Hi,

This may not be a issue I might be missing some thing here.

I want to get access to user avatar. In my site i get 401 error, but in other site it is fetched successfully. am i supposed to change some setting on my side? or is it a Security matter where we need to authenticate the person who is viewing the app

http://totest-cscom.rhcloud.com/wp-json/wp/v2/users/1  -- 401 error wpAPi V2 betaV11

http://dev.julienrenaux.fr/wp-json/wp/v2/users/1  -- Output generated  successfully wpAPi V2 betaV9

Please help me to get the Author avatar on my post list.

Thanks,
Raj

**Comment by danielbachhuber** [comment]
Users are only publicly exposed when they have at least one published post. If they don't have a published post, then you'll need authorization to view the user.

**Comment by rajesh-h** [comment]
Thank you @danielbachhuber for your response.

Please note all my posts are custom post type which is 'recipe'

Author for all these posts are users/2   even users/2 also is not accessible.

Proof to say user 2 has published recipe/post  
http://totest-cscom.rhcloud.com/wp-json/wp/v2/recipes/4959

Unable to access this user
http://totest-cscom.rhcloud.com/wp-json/wp/v2/users/2

Does it boil down to the fact that only the author who has published *_normal post *_visible without any authentication?

Thanks,
Raj

**Comment by danielbachhuber** [comment]
> Does it boil down to the fact that only the author who has published *normal post *visible without any authentication?

Yes, it currently does because we're checking `count_user_posts( $id )` which defaults to the Post post type.

I'll flag this as a bug to fix in the next release, because we need to:
- [ ] Call `count_user_posts()` with an array of all REST API-visible post types, instead of limiting to just posts.
- [ ] Add tests to ensure a user who has published a Page, but not a Post, is accessible in the API.

**Comment by rajesh-h** [comment]
@danielbachhuber  thank you very much.

So for now i have created a dummy normal post so the author is visible without authentication. Thanks a lot for your response.

**Comment by iamchrissmith** [comment]
https://github.com/WP-API/WP-API/pull/2152 adds an array of visible post types to `get_item_permissions_check()`.  My initial tests show that a user with just pages is visible now. Hopefully that leaves:
- [x] Call `count_user_posts()` with an array of all REST API-visible post types, instead of limiting to just posts.
- [ ] Add tests to ensure a user who has published a Page, but not a Post, is accessible in the API.
