### ISSUE TITLE
Support for date queries with `GET /wp/v2/posts`

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2144]
It would be nice if we had top-level support for date queries with `GET /wp/v2/posts`.

`WP_Query` currently supports a ton of date filters:

![image](https://cloud.githubusercontent.com/assets/36432/12675466/5a190996-c63f-11e5-9969-df25e278a38b.png)

We should pick which fields would be sensible to support, and add them to `GET /wp/v2/posts`

Related #924

**Comment by kadamwhite** [comment]
Anecdotally, I have most often leveraged `year`, `month`, `day`, `before` and `after`.

**Comment by bjork** [comment]
To me it would make sense to expose the whole `date_query` but not the shorthand (root level) parameters to avoid having too many ways to do the same thing. The only disadvantage is that encoding arrays within arrays as HTTP query parameters is not the most intuitive thing and is specific to PHP. But, expressing complex structures as a single string is always going to be at least somewhat complex.

**Comment by rmccue** [comment]
Agreed with @bjork, although I'd also be happy to support both `before` and `after` as top-level and support ISO8601 dates for them. You can implement year/month/date/etc on top of this pretty easily, i.e. `year => 2015` maps directly to `before=2016-01-01T00:00:00Z&after=2015-01-01T00:00:00Z`.

**Comment by bponghneng** [comment]
Wow, literally just registered at wordpress.org then logged in here to ask whether this is supported, or am I missing something in the WP_REST_Post_Types_Controller class. Glad to see it's on the list for coming soon. Queries using before and after would do very nicely, IMO.

Looks fairly trivial, but I just took a whack at it and couldn't get it to work in an hour of flogging. I did manage to get `year` and `monthnum` queries working with half a dozen edited lines of code in a subclass of WP_REST_Post_Types_Controller. So I think I'm missing something simple. My first guess is the missing piece is somewhere in REST API allowed query vars since `before` and `after` aren't in the WP allowed vars.

Anyway, I'd be delighted to contribute in this small area if someone wouldn't mind fielding some questions from a WP newbie.

**Comment by wesm87** [comment]
@bpongvh I just started looking at the `tax_query` issue and I think you're on the right track, you'll probably want to start by adding `before` and `after` to the `$rest_valid` array in `WP_REST_Posts_Controller::get_allowed_query_vars()` and then look at `WP_REST_Posts_Controller::get_items()`. I could be way off track, though.

**Comment by bponghneng** [comment]
@wesm87 Yeah, went through those. Tried `before` and `after` and `date_query` (which is the arg I figure is the correct one to add to `WP_Query`). I've been lazy, though, and working without Xdebug. I'll hook it up and get into it proper to see where I've gone astray. Thanks for the vote of confidence, and I'll be back in a bit with a solution.

**Comment by bponghneng** [comment]
Before and after turned out quite easy (once I got xdebug going and saw my typo). I'm dragging my feet now because I figured I'd try to submit tests at the same time, and I'm still tooling up on that. Like I said, a while since I've worked in PHP.

But as I've been thinking about this, I realize that right now the API just dumps posts via a GET on the /posts endpoint, including future-dated posts. That's actually what brought me here looking for date range query params. Is it worth my trying to put together something like a before=now default on /posts queries using the view context?

**Comment by rmccue** [comment]
> Is it worth my trying to put together something like a before=now default on /posts queries using the view context?

`before=now` will cause problems with caches, better for clients to be specific.

Future-dated posts should be `status: future` I think, and shouldn't be shown? Are you sure this is not a timezone-related issue?

**Comment by bponghneng** [comment]
Ryan, now I see what I did wrong to get future posts. WP newbie mistake (again). Yes, verified `status: future` posts only on edit context. Submitted pull request for adding `date_query` arg (to support before and after params).

I'm still working on the test setup, so I'll try to followup with that. I'm interested to continue contributing to this project if you can tolerate more newbie questions. Is there a better place for me to post them? Slack channel?

**Comment by wesm87** [comment]
@bpongvh Request a Slack invite here if you haven't done so already:

https://make.wordpress.org/chat/

Then you'll want to join the `#core-restapi` channel.

**Comment by danielbachhuber** [comment]
@BE-Webdesign after #2266 lands, would you want to take on adding the same support to comments?

**Comment by BE-Webdesign** [comment]
@danielbachhuber Certainly, I will get on that soon.  Maybe before #2266 lands!

**Comment by danielbachhuber** [comment]
:ship:

**Comment by danielbachhuber** [comment]
@WP-API/amigos Do we want to have top-level support for picking between `date` and `date_gmt` as comparison value for `before` and `after` ?

**Comment by BE-Webdesign** [comment]
@danielbachhuber Not sure I follow wouldn't specifying the date string in before or after do that? Like if you wanted to check against gmt times use Zulu time and if you wanted EST do like
2016-02-23T:00:00:00-5:00UTC? I am le confused.

**Comment by BE-Webdesign** [comment]
Aren't date and date_gmt the same time just a different representation or do I not understand date times at all?

**Comment by joehoyle** [comment]
@BE-Webdesign one would intuitively think that, however if it were the case, we probably wouldn't even bother having `date` and `date_gmt`. These two values are not actually the same data, there are numerous situations where `date` and `date_gmt` are "out of sync" (i.e. not just the timezone offset apart). for example, switching timezones on old data. They essentially need to be treating as two totally separate dates.

@danielbachhuber Good point. Maybe `date_before` and `date_gmt_before` might have been better naming? Or - on the other hand, I'd be tempted to just favour `date` over `date_gmt`, so date querying are always against `date` (the client can do offset calculation). `date_gmt` is there for the database value, but would then not have much other meaning / use.

**Comment by danielbachhuber** [comment]
Eh, I think we should favor `date` over `date_gmt`. But, `WP_Query` supports a `column` argument for date queries to change from `post_date` to `post_date_gmt` (or another date column). I was thinking we might want to support an equivalent.

**Comment by BE-Webdesign** [comment]
@danielbachhuber, @joehoyle what do you want to name the parameter?

**Comment by danielbachhuber** [comment]
Punting on top-level support for specifying column for now. This is an easy enhancement to add later.
