### ISSUE TITLE
Support taxonomy queries

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2145]
It would be nice if we had top-level support for tax queries with `GET /wp/v2/posts`.

Here's `WP_Query` currently supports:

![image](https://cloud.githubusercontent.com/assets/36432/12675613/5f311076-c640-11e5-958a-7079d19e8f1b.png)

Related #924

**Comment by bjork** [comment]
See [my comment on #2144](https://github.com/WP-API/WP-API/issues/2144#issuecomment-176990148). Like `date_query`, exposing `tax_query` would be very straightforward.

**Comment by kadamwhite** [comment]
Re-purposing this issue to serve as a general TODO list for taxonomy handling, because the current interface is inconsistent at best and unworkable in many situations.

I took a crack at coming up with some stories for taxonomy querying in general: **As an API consumer, I...**
- Should be able to request records that are associated with a specific taxonomy term
- Should be able to request records that are associated with multiple terms of a single taxonomy (AND)
- Should be able to request records that are associated with any of several terms of a single taxonomy (OR)
- Should be able to request records that are associated with specific terms of multiple taxonomies
- Should be able to request records that are associated with multiple terms of multiple taxonomies (AND)
- Should be able to request records that are associated with any of several terms of multiple taxonomies (OR)
- Should be able to request records that are NOT associated with a specific taxonomy term
- Should be able to request records that are NOT associated with multiple terms of a single taxonomy
- Should be able to request records that are NOT associated with any of several terms of multiple taxonomies
- Should be able to request records that are NOT associated with any of several terms of multiple taxonomies
- Should get an empty collection back if no records match the provided conditions

(This list assumes the queried taxonomies are marked to be shown in the REST API.)

I would like to see the taxonomy query interface hit the above points (or at least the first four!) in as terse a query syntax as is feasible.

**Comment by kadamwhite** [comment]
I also believe we should strive for consistency and make this apply to CPTs and any resource for which a taxonomy is registered, not just posts.

**Comment by kadamwhite** [comment]
An assumption of the above list is that the interface would look the same or similar regardless of the taxonomy. So these would satisfy:

```
?terms[]=catID1&terms[]=tagID&terms[]=catID2
?tax[category][]=catID1&tax[category][]=catID2&tax[tag][]=tagID
```

but these would not:

```
?filter[tag]=tagSlug&filter[cat]=catID&tax[custom_tax]=termId
```

**Comment by kadamwhite** [comment]
cross-link to #2273

**Comment by kadamwhite** [comment]
Revisiting this list in light of `?{taxonomy}[]=` and `?{taxonomy}_exclude[]=`,

As an API consumer, I...
- [x] Should be able to request records that are associated with a specific taxonomy term
- [ ] Should be able to request records that are associated with multiple terms of a single taxonomy (AND)
- [x] Should be able to request records that are associated with any of several terms of a single taxonomy (OR)
- [x] Should be able to request records that are associated with specific terms of multiple taxonomies
- [ ] Should be able to request records that are associated with multiple terms of multiple taxonomies (AND)
- [x] Should be able to request records that are associated with any of several terms of multiple taxonomies (OR)
- [x] Should be able to request records that are NOT associated with a specific taxonomy term
- [x] Should be able to request records that are NOT associated with multiple terms of a single taxonomy
- [x] Should be able to request records that are NOT associated with any of several terms of multiple taxonomies
- [x] Should be able to request records that are NOT associated with any of several terms of multiple taxonomies
- [x] Should get an empty collection back if no records match the provided conditions

AND handling is the only missing piece, and after in-person & slack discussion in dev meeting on 2016-10-06 including tax_query in its entirety is not a satisfying way to support AND, and no simpler solution has been proposed; I am declaring taxonomy handling with OR and NOT IN sufficient for now and we will re-purpose this issue again for supporting AND handling down the road.

**Comment by kadamwhite** [comment]
Actually splitting the AND piece off into a new issue because the majority of the use-cases we established should now be supported!
