### ISSUE TITLE
Support `menu_order` param for `GET /wp/v2/pages`

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2187]
Because it's a property of Pages, we should support the `menu_order` param for `GET /wp/v2/pages`.

From #924

**Comment by pinkasey** [comment]
I'm just a noop to WP and WP API, so maybe what i'm about to ask won't make sense.

Can 'menu_order' also be supported for Posts?
There are many 'custom post order' plugins out there, and i suspect they all set 'menu_order' for posts.
In the application that I'm building, controlling post order in queries is crucial, and I thought a plugin such as 'simple post order' would be perfect for that.

**Comment by rmccue** [comment]
@pinkasey Technically speaking, all post types can have a `menu_order` value, but it only affects pages in core. Plugins using the menu order on other post types would need to also add this to the API themselves.

**Comment by kadamwhite** [comment]
I agree with @rmccue, this is plugin territory—any plugin that adds handling for `menu_order` on posts ought to also add support for that ordering to the API.

**Comment by pinkasey** [comment]
Thanks for the very quick response, guys!
I thought I would have to wait weeks for someone to notice this 👍 

I think I understand your answer. I will look it up - how to amend one of those plugins, so that it adds "page-attributes" to a post-type (or all post-types maybe).
Any advice on how to do this (what method to call, etc) would be greatly appreciated, but I don't want to waste you time, as you said it's not wp api scope.

**Comment by pinkasey** [comment]
I've arbitrarily chose "intuitive-custom-post-order" plugin, and added the code I needed in order for it to work well with WP-API orderby.
Here's the [pull request](https://github.com/hijiriworld/intuitive-custom-post-order/pull/14), if anyone is interested.
I recon this can be done on most if not all other 'custom post order' plugins.

Thanks again for the help!
