### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by thomasboulongne** [WP-API/WP-API#2259]
Hi,

It's the first time I'm using this very good API, but I can't make the filters to work. Even if I try to filter using  /wp-json/wp/v2/posts?slug=an-awesome-slug or /wp-json/wp/v2/posts?filter[name]=an-awesome-slug, the result remains the whole list of my posts (no matter the filter I use). Am I missing something?
(Beta 11-12)

Thomas

**Comment by mensch** [comment]
Just tested this on beta12 and both filters appear to work on my setup. The only time I get the whole list of (public) posts is when I use an invalid filter name, like `filter[slug]` or when requesting content which can only retrieved using authentication. The request below will only return relevant data when authenticated, otherwise all public posts are returned:

`http://my-api-server.dev/wp-json/wp/v2/posts/?filter[post_status]=public&page=1&per_page=5
`
Not sure if I'm of much help, but is the `post_status` of the entry with the post_name "an-awesome-slug" set to _public_?

**Comment by kadamwhite** [comment]
@thomasboulongne Do the posts you want to see show up in any page of results without the filter? Do other filters work, such as `per_page=1`?

What type of server are you using -- do you know if your server uses Nginx or Apache?

**Comment by thomasboulongne** [comment]
All my posts are public and appear in the list retrieved without filter (and in my case even with slug filter).
The filter per_page works indeed.
I'm using Nginx (it's a dedicated server). Do you think it can affect the behaviour of the API?

**Comment by kadamwhite** [comment]
@thomasboulongne I had issues with filtering in Nginx due to a typo in my try files directive ([issue and fix described here](https://github.com/WP-API/WP-API/issues/1926#issuecomment-168090756)), but that would prohibit _all_ filters from working. I've not encountered a scenario where only specific query parameters do not function correctly, sorry I couldn't be more help.

Do you have other plugins running, or any custom code that could be affecting the list of permitted query variables?

**Comment by thomasboulongne** [comment]
My bad, I checked again and even the per_page wasn't working either, so I applied your fix in my Nginx conf file, and it's now good ! Thank you very much

**Comment by kadamwhite** [comment]
:+1: Glad you got yourself sorted!
