### ISSUE TITLE
Correct API request for POST Category

### ISSUE THREAD

**Issue by mingyena** [WP-API/WP-API#2301]
Hi, I asked a category question in here - https://github.com/WP-API/WP-API/issues/2290
But since the post is closed, so I think you guys are not able to see my question any more... 
So I just created another one - 
May I ask the right request to send a POST?
I tried POST blog-name/wp-json/wp/v2/categories?post=10102&id=categoryID
AND
POST blog-name/wp-json/wp/v2/categories?post=10102, array(id, count,name)
But they seems not be correct paths...

**Comment by danielbachhuber** [comment]
To assign a category to a post, you'll want to `POST blog-name/wp-json/wp/v2/post/10102` and include `categories = [ cat_id ]` in the request body.

**Comment by kosso** [comment]
This doesn't appear to be working for me on Wordpress nightlies `4.5-beta2-36859`, `WP-API 2.0-beta12` and `OAuth1 0.2.1`  

I am using `blog-name/wp-json/wp/v2/posts/10102`   ('posts')

It can update a post title or add an excerpt, for example, but it seems to ignore the category id array that I'm sending. (I've tried one or two category ids in the array).

update: I'm trying to do this via an OAuth request. And it's occurred to me that my base string isn't dealing with the array correctly.

**Comment by mingyena** [comment]
Yes, same here, category = [id] still doesn't work for me.

**Comment by kosso** [comment]
I think this is due to the plugin incorrectly parsing the array parameter when generating the base string for signature generation. 

According to the spec here : http://oauth.net/core/1.0a/#signing_process  (9.1.1)

_Parameters are sorted by name, using lexicographical byte value ordering. If two or more parameters share the same name, they are sorted by their value. For example:_ 

```
a=1, c=hi%20there, f=25, f=50, f=a, z=p, z=t
```

However, maybe it shouldn't be part of the signature at all? And sent as JSON? (ie: Not application/x-www-form-urlencoded, which is a requirement for being part of the base string.)

**Comment by kosso** [comment]
Hi. I got it working.  

You need to POST the data as `Content-Type: application/json` 

I've also updated my [test PHP script](https://gist.github.com/kosso/71c957e30a40116e5f98).
