### ISSUE TITLE
Comments end Point  Using beta 12  status=approved does not fetch results

### ISSUE THREAD

**Issue by rajesh-h** [WP-API/WP-API#2322]
Hi,

Below is the end point for comments in one of the existing frame work i am using. 
I am using beta12 of wp-api2

http://totest-cscom.rhcloud.com/wp-json/wp/v2/comments?order=asc&orderby=date&per_page=50&post=4832&status=approved&type=comment

This returns with 401 unauthorised 
`{
  "code": "rest_forbidden_param",
  "message": "Query parameter not permitted: status",
  "data": {
    "status": 401
  }
}`

If the end point is modified to remove `status=approved`  it is retuning comments (all comments are approved).

http://totest-cscom.rhcloud.com/wp-json/wp/v2/comments?order=asc&orderby=date&per_page=50&post=4832&type=comment

I get results on above link

I heard this behaviour is not observed in beta11. I haven't tried it though.

Thanks,
Raj

**Comment by BE-Webdesign** [comment]
Hi Raj,

@just10minutes I am pretty sure this is the expected behavior of the API.  If an unauthorized user could filter results based on the status parameter they could retrieve comments on hold, spam, and trash status, which are all private data.  With the status parameter omitted from the request you get what you would expect, approved comments, which are available to any user.

After looking at how the posts endpoints interacts with the status param however, we would probably want to make this consistent and function as you have suggested. When using GET wp/v2/posts/?status=published you do not get a forbidden param error response if you are an unauthenticated user.  There could be some reason why it should be the way it is which I am overlooking but thank you for bringing this up.

**Comment by bobsilon** [comment]
Why you filtering the comments by `status=approved`? By default wp-api returns approved comments and unapproved comments doesn't return. As @BE-Webdesign explained, this is the expected behavior for security reasons.

**Comment by rajesh-h** [comment]
Hi As I said i am using one of the existing framework shared by someone else. Anyway now i have removed it so it is working as expected. Thanks a lot for your suggestion

**Comment by danielbachhuber** [comment]
We'll keep this open for discussion, as we should have consistent `status` query arg behavior between posts and comments.

**Comment by rajesh-h** [comment]
I hope this is not problem only at my end. All my posts are custom post type. My custom post type is Recipes. I have tried to replace post=4832 with recipe=4832 in the url, it does not return result. 

I thought it is better I let u know guys that the comment is actually from a post which is a custom post type.

**Comment by BE-Webdesign** [comment]
@just10minutes That is an different topic for this issue.  Make sure that your Recipe CPT has show_in_rest => true and it will have a controller class auto-generated for it.  Also double check that "recipe" is the name you are matching up to if show_in_rest is already set to true.  If you want to discuss this further could you open up a new issue.

**Comment by danielbachhuber** [comment]
> We'll keep this open for discussion, as we should have consistent status query arg behavior between posts and comments.

We're not going to change the behavior at this point.
