### ISSUE TITLE
Add rest_pre_insert filter for terms

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2368]
We have equivalent filters for Posts, Commands and Users, but we're missing it for terms.

**Comment by kjbenk** [comment]
Are you referring to this filter within the User endpoint? 

https://github.com/kjbenk/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L546-L605

If so, then we will need to implement the `prepare_item_for_database` function as well and call it within the `create_item` and `update_item` functions...correct?

I just want to make sure before I create a PR.

**Comment by danielbachhuber** [comment]
> Are you referring to this filter within the User endpoint?

Yes, that's the existing filter on the User endpoint.

> If so, then we will need to implement the prepare_item_for_database function as well and call it within the create_item and update_item functions...correct?

I don't see creating a `prepare_item_for_database` method as _necessary_ per say, but we could do that as well.

**Comment by kjbenk** [comment]
I think we should add the new `prepare_item_for_database` function since all other endpoints that have a `create_item` action have this function.  My initial thought is to refactor the code in these two places into the new `prepare_item_for_database` function:
1. https://github.com/kjbenk/WP-API/blob/develop/lib/endpoints/class-wp-rest-terms-controller.php#L335-L358
2. https://github.com/kjbenk/WP-API/blob/develop/lib/endpoints/class-wp-rest-terms-controller.php#L427-L450

@danielbachhuber Does this sound like the right direction?

**Comment by BE-Webdesign** [comment]
@kjbenk I would be :+1: on that so there is consistency across the controller classes.  Those two areas look like the right place to do it as well, but I will defer the decision to @WP-API/amigos.

**Comment by danielbachhuber** [comment]
> Does this sound like the right direction?

Works for me.

**Comment by kjbenk** [comment]
Is there any reason why a `create_item` call within invalid term would throw a 404 when an `update_item` call with an invalid term throws a 400?

Update Item: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-terms-controller.php#L446
Create Item: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-terms-controller.php#L354

Should they both be a 400 status? @danielbachhuber

**Comment by BE-Webdesign** [comment]
Usually you would use 404 if something doesn't exist so if a term doesn't exist send back a 404 and 400 for a bad request for like invalid params.  So if I had a term sausage that is valid but it doesn't exist hence 404.  That I believe is the logic behind that distinction but could be wrong.

**Comment by kjbenk** [comment]
@BE-Webdesign I made the decision to throw a 400 status for the invalid term error since the error is related to a mis-match rather than a missing endpoint.

However, the bigger question is that should the two status codes be the same or different?

**Comment by BE-Webdesign** [comment]
Oh, wow didn't read what you had typed and fully processed it haha.  Yes that seems like a problem to me but I imagine it has to do with the non existance of the resource so on create request the resource doesn't exist, because it failed to create it, meaning 404 and update it would exist so 400.  But idk if that is right necessarily.

**Comment by danielbachhuber** [comment]
> Is there any reason why a create_item call within invalid term would throw a 404 when an update_item call with an invalid term throws a 400?

It should be a 400 response when the `parent` doesn't exist, because using a `parent` that doesn't exist is an invalid request. The 404 is incorrect.

**Comment by danielbachhuber** [comment]
:hammer:
