### ISSUE TITLE
Explicitly distinguish between create and update in Posts::prepare_item_for_database()

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2370]
Currently, I have to infer based on whether `id` is in the `$prepared_post`, or do some deep inspection of the `$request`. It would be better if we explicitly distinguished between create and update by passing a third `$update` boolean argument to the filter.

**Comment by kjbenk** [comment]
Just to make it a little easy for new comers here is where that filter is located:
- Users: https://github.com/WP-API/WP-API/blob/abf4981f4bb7606144481aa43b51b9738aa1c452/lib/endpoints/class-wp-rest-users-controller.php#L604
- Comments: https://github.com/WP-API/WP-API/blob/5a79ce84f407f155812dfb2317fa791da8216030/lib/endpoints/class-wp-rest-comments-controller.php#L764
- Posts: https://github.com/WP-API/WP-API/blob/86f14595a176014139acb0c88bb79065fb4e3789/lib/endpoints/class-wp-rest-posts-controller.php#L855

Also here once PR https://github.com/WP-API/WP-API/pull/2377 is merged:
- Terms: https://github.com/WP-API/WP-API/pull/2377/files#diff-6a5f19de0f37a384ee52877de312ee67R534

**Comment by kadamwhite** [comment]
This was [discussed in PR scrub today](https://wordpress.slack.com/archives/core-restapi/p1473800252001139) while looking at #2396: Ryan & I do not believe this to be an issue. The presence of an ID is by definition a good indicator that a value is being updated.

Unless there are situations in which the presence of an `id` is not guaranteed (because I agree that deep inspection of the request object is less than ideal), closing this one out.
