### ISSUE TITLE
Post content issue with encoding

### ISSUE THREAD

**Issue by kaito-kaito** [WP-API/WP-API#2405]
Hi everyone. 
I have an issue with post content. It is not displayed properly. See the picture below. (Note: the content is in ARABIC) so I think there is a problem with encoding. 
http://i.imgur.com/olCd2Ig.png

**Comment by danielbachhuber** [comment]
Related #2243

**Comment by rmccue** [comment]
This seems like intentional behaviour to me?

**Comment by kadamwhite** [comment]
If WP itself stores the content HTML-encoded in the posts table, this makes sense (and anyone more familiar with WP i18n, please correct me if this isn't so). If the content is not generally stored HTML-encoded however, I do not agree with closing this out.

**Comment by rmccue** [comment]
As far as I'm aware, the field is stored fully HTML-encoded (since it's a HTML field).

**Comment by kadamwhite** [comment]
Foreign characters are valid HTML so I found that answer unsatisfying, and did some digging.

@kaito-kaito I'm not able to reproduce this issue; how are the posts being created & inserted into WordPress? I am not an Arabic speaker, but I tested first by writing one post in Japanese and then making another by copying and pasting Arabic into the post editor via WP-Admin, then POSTed the same content to the API using this Node script:

``` js
// Created "Test" through the WP-Admin, then via this script:
var jpn = site.posts().create({
    title: 'Test (API)',
    content: '閑かさや\n岩にしみ入る\n蝉の声',
    status: 'publish'
});

// Created "Test 2" through the WP-Admin, then via this script:
var ar = site.posts().create({
    title: 'Test 2 (API)',
    content: 'اتق شر الحليم اذا غضب',
    status: 'publish'
});

Promise.all([ ar, jpn ])
    .then( () => site.posts().perPage( 4 ) )
    .then( posts => console.log( posts ) )
    .catch( err => console.error( err ) );
```

Pulling the data back out looks OK:

``` js
[ { id: 1713,
  date: '2016-09-21T21:42:20',
  // ...fields removed for brevity
  title: { rendered: 'Test 2 (API)' },
  content: { rendered: '<p>اتق شر الحليم اذا غضب</p>\n' },
  excerpt: { rendered: '<p>اتق شر الحليم اذا غضب</p>\n' }
},
{ id: 1712,
  date: '2016-09-21T21:42:20',
  // ...fields removed for brevity
  title: { rendered: 'Test (API)' },
  content: { rendered: '<p>閑かさや<br />\n岩にしみ入る<br />\n蝉の声</p>\n' },
  excerpt: { rendered: '<p>閑かさや 岩にしみ入る 蝉の声</p>\n' }
},
{ id: 1708,
  date: '2016-09-21T21:37:11',
  // ...fields removed for brevity
  title: { rendered: 'Test 2' },
  content: { rendered: '<p>اتق شر الحليم اذا غضب</p>\n' },
  excerpt: { rendered: '<p>اتق شر الحليم اذا غضب</p>\n' }
},
{ id: 1688,
  date: '2016-09-21T21:31:19',
  // ...fields removed for brevity
  title: { rendered: 'Test' },
  content: { rendered: '<p>閑かさや<br />\n岩にしみ入る<br />\n蝉の声</p>\n' },
  excerpt: { rendered: '<p>閑かさや 岩にしみ入る 蝉の声</p>\n' }
} ]
```

And it looks OK in the json viewer extension too:

![image](https://cloud.githubusercontent.com/assets/442115/18734445/7c6baafe-8042-11e6-9d68-3e80721536d4.png)

so I do not believe the culprit is the API itself necessarily, there may be something about your environment from which you are making the request that is converting them into the HTML-escaped format.
