### ISSUE TITLE
Wordpress REST API DELETE request doesn't work in my WP MULTISITE

### ISSUE THREAD

**Issue by raphaelolivero** [WP-API/WP-API#2408]
I'm using the the http://wp-api.org/ plugin in a WP MULTISITE (Network mode) and I tried to delete a single user by its ID with AJAX, but instead of deleting the user, it returns the user object with a successful response "XHR finished loading: DELETE", and the user still exists. The DELETE request is the only one that doesn't work!

Code:

```
API_URI = "http://example.com/wp-json/wp/v2/users/";

function deleteUserById(credentials, userId) {
    $.ajax
    ({
        type        : 'DELETE',
        url         : API_URI + userId,
        dataType    : 'json',
        async       : true,
        beforeSend  : function(xhr) {
            xhr.setRequestHeader('Authorization', 'Basic ' + btoa(credentials['user_login'] + ':' + credentials['user_pass']));
        },
        success     : function (obj, x) {
            console.log(obj);
            console.log(x);
        },
        error       : function (xhr, ajaxOptions, thrownError) {
            console.log(xhr);
            console.log(ajaxOptions);
            console.log(thrownError);
        }
    });
}
```

Is there anyone who can give me advice? Thanks in advance!

**Comment by BE-Webdesign** [comment]
There could be a number of things at play here:

First, this probably has zero effect but type should be method in your object.

Second, does the user you are authenticating as have permissions to delete the user.  For multisite you need to be super admin or somehow have it set up so that the admin of the site can delete the appropriate user.

If you are using Basic Auth you need to make sure a cookie or nonce is not blocking your ability to authenticate.  Are you remotely executing this ajax call from another domain or calling from the same domain as your WP install?  

The way your request is currently set up you wouldn't delete the resource and would get returned a 501.  So if you aren't getting a 501 yet, then there is probably an issue with the authentication.  You would need to add a query param of force=true to successfully delete the user, once the auth bug is tracked down.

**Comment by BE-Webdesign** [comment]
Going to close this issue for now though because the functionality does work.  I would be glad to continue the discussion and help you out though.

**Comment by raphaelolivero** [comment]
Hi,

The server was blocking the external DELETE requests. I added this to the .htaccess file, and it works now:

```
<Limit GET POST PUT DELETE>
order deny,allow
allow from all
</Limit>
```

Btw, thanks for your answer!

**Comment by BE-Webdesign** [comment]
Yeah, I thought it was strange that you were getting a successful status and not some sort of error.  Now it all makes sense!  Glad you figured it out :smile:

**Comment by OpossumPetya** [comment]
@cerebrumapp thanks for figuring this out! :) just ran into the same issue, this saved me some time (probably a lot :))
