### ISSUE TITLE
Get value inside array ?!

### ISSUE THREAD

**Issue by Imaginocharme** [WP-API/WP-API#2445]
I have a problem reading a json variable trough the rest api v2

**The problem:**
my Json

```
.....
"Featured_media": 11661,
"Comment_status", "open"
"Ping_status", "open"
"Geolocation_city": [ "Oeiras"],
"_links": {
"Self": [{
"Href": "http: \ / \ / website.com \ / wp-json \ / wp \ / v2 \ / listings \ / 11660"
.....
```

I can read all variables less geolocation_city with this code

```
        $.getJSON('http://imaginocharme.com/wp-json/wp/v2/listings/11660', function (jd) {

        $('#stage').html('<p> Nome: ' + jd.featured_media + '</p>');
        console.log(jd.featured_media);
        $('#stage').append('<p>Descrição : ' + jd.comment_status + '</p>');
        console.log(jd.comment_status);
        $('#stage').append('<p>Nome : ' + jd.ping_status + '</p>');
        console.log(jd.ping_status);
        $('#stage').append('<p>Cidade : ' + jd.geolocation_city + '</p>');
        console.log(jd.geolocation_city);
        $('#stage').append('<p>Links : ' + jd._links.self[0].href + '</p>');
        console.log(jd._links.self[0].href);

           }); 
```

My console log

```
11661
index.html (29,29)
open
index.html (31,29)
open
index.html (33,29)
undefined
index.html (35,29)
http://imaginocharme.com/wp-json/wp/v2/listings/11660
index.html (37,29)
```

I've tried several ways to read the variable geolocation_city and always gives undefined

Can anyone help?
Any idea?

**Comment by BE-Webdesign** [comment]
Not exactly sure why, but your response is returned in text/html instead of application/json for the Content-Type response header.  That could potentially be a reason for the problem.

I tried using your setup and had no problem accessing response.geolocation_city once the response was converted to JSON.  I am not entirely sure what the problem is but it could be your server config, or somewhere in your code something is not being parsed correctly.

If this is your response:

> .....
> "Featured_media": 11661,
> "Comment_status", "open"
> "Ping_status", "open"
> "Geolocation_city": [ "Oeiras"],
> "_links": {
> "Self": [{
> "Href": "http: \ / \ / website.com \ / wp-json \ / wp \ / v2 \ / listings \ / 11660"
> .....

The above is invalid JSON, so that could also be a problem. However, I had no problem accessing that variable from your actual server's response, other than having to make sure the response body was JSON first.
