### ISSUE TITLE
Counting Published and Pending in a category

### ISSUE THREAD

**Issue by BrekiTomasson** [WP-API/WP-API#2485]
Hi!

Quick question. When I do a normal `/categories` call, I get an entry called `count` which shows the amount of published posts in that category. I've been trying to figure out if there's a way of counting all published _and_ pending posts. Doesn't seem to be enough to just add `?status=pending,publish` on the end of the URL as I expected.

**Comment by danielbachhuber** [comment]
> I've been trying to figure out if there's a way of counting all published and pending posts.

This isn't possible without some PHP code, because the `count` field correlates with a value stored in the database. Look at the `update_count_callback` argument for [register_taxonomy](https://codex.wordpress.org/Function_Reference/register_taxonomy) to see how you can have the count modified (although be aware of the implications of including the `pending` count too).
