### ISSUE TITLE
API with preview mode 

### ISSUE THREAD

**Issue by gpezier2** [WP-API/WP-API#2511]
Hi,

Thanks for your great plugin.

Actually we have a SPA project (Single Page Application) and we need to have a preview mode before publish a content.

Please could you tell me how we can get the draft content, with an URL like : /wp-json/wp/v2/posts/?status=draft ?

Indeed, for your information actually we use the plugin https://wordpress.org/plugins/live-drafts/ in order to have, in same time, 2 versions of a same post : published & draft

But maybe you know the better way (new filter or other plugin ... ) to have a preview mode (as simple as possible) :
- 2 versions for a post : published and draft
- get from the API a draft version of a post

Thanks by advance for your help

**Comment by BE-Webdesign** [comment]
Hi @gpezier2, thank you for using the WP REST API!

Quick question, when you use `/wp-json/wp/v2/posts/?status=draft` what do you get back in your response?

As long as you have two copies in the database, one with draft status and one with published, you should be able to get both through the API with proper authentication.  They will be unique posts. You will also want to implement some way to tell which posts match up with each other.  If you are creating a SPA outside of WordPress, I would suggest doing something other than running duplicates in the database though.

**Comment by gpezier2** [comment]
Hi @BE-Webdesign 

With URL, wp-json/wp/v2/posts/?status=draft, I have this JSON : 

{
code: "rest_invalid_param",
message: "Paramètre(s) non valide(s)&nbsp;: status",
data: {
status: 400,
params: {
status: "Status is forbidden"
}}}

And with wp-json/wp/v2/posts/?status=publish, all is  OK : I can get the post list

Could you precise your recommandation in order to have draft and publish version in the API ?

Thanks

**Comment by BE-Webdesign** [comment]
The error you are getting is an authentication error.  It is giving the wrong error code but that is another issue, which I will fix :smile:.  

You need to authenticate to the API as a user who has the privileges to see a draft post.  By having that restriction in place you aren't publicly exposing your private data.  I imagine you want the drafts to be previewed first before they are public for a reason.  [Here is a guide on authenticating with the API](http://v2.wp-api.org/guide/authentication/).  There are a number of methods you can use but if you are just getting started I recommend using the Basic Auth.

> Could you precise your recommandation in order to have draft and publish version in the API ?

If you have something that works well for you continue to use it.  You can ignore what I said because I don't know enough about your project to make comments haha.

**Comment by gpezier2** [comment]
Hi,

We have done an authentication test : 
-> with a Chrome Rest client :  JSON with error 403 "Rest_forbidden"

-> and with PHP we have a timeout.

```
require( dirname( __FILE__ ) . '/wp-blog-header.php' );

$headers = array (
'Authorization' => 'Basic ' . base64_encode( 'admin' . ':' . 'password' ),
);
$url = rest_url( '/wp-json/wp/v2/posts/471' );

$data = array();

add_filter( 'http_request_timeout', 'wp9838c_timeout_extend' );

function wp9838c_timeout_extend( $time )
{
// Default timeout is 5
return 120;
}

$response = wp_remote_post( $url, array (
'method' => 'POST',
'headers' => $headers
) );

if ( is_wp_error( $response ) ) {
$error_message = $response->get_error_message();
echo "Something went wrong: $error_message";
} else {
echo 'Response:<pre>';
print_r( $response );
echo '</pre>';
}
<?php
require_once (dirname(__FILE__) . '/wp-load.php');
require_once (dirname(__FILE__) . '/wp-config.php');

$headers = array (
'Authorization' => 'Basic ' . base64_encode( 'root' . ':' . 'Dan2016!' ),
);
$url = rest_url( '/' );

$data = array();

add_filter( 'http_request_timeout', 'wp9838c_timeout_extend' );

function wp9838c_timeout_extend( $time )
{
// Default timeout is 5
return 120;
}

$response = wp_remote_post( $url, array (
'method' => 'POST',
'headers' => $headers
) );

if ( is_wp_error( $response ) ) {
$error_message = $response->get_error_message();
echo "Something went wrong: $error_message";
} else {
echo 'Response:<pre>';
print_r( $response );
echo '</pre>';
}
```

Do you know why ?

Thanks

**Comment by BE-Webdesign** [comment]
The timeout is happening I believe because in your `rest_url()` call you are passing in /wp-json/ as part of the path which is not necessary.  So you are sending a request to the path /wp-json/wp-json/ which shouldn't exist.  For the 403, you must be authenticating as a user without proper authorization. Also there is odd placement of the <?php?> tags.

``` php
add_filter( 'rest_pre_dispatch', 'my_prefix_test_current_user', 10, 3 );

function my_prefix_test_request_headers( $result, $server, $request ) {
    $result = wp_get_current_user();
    return $result;
}
```

Put this in a plugin or an active theme's functions.php to see if you are authenticating as a user with proper privileges.

**Comment by gpezier2** [comment]
All is OK now 

Thanks a lot for your support
