### ISSUE TITLE
Provide method of flushing schema

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/WP-API#2527]
I just spent a couple hours trying to figure out why a post type wasn't generating a collection in the javascript client. I finally noticed in the docs it's warned that the schema is stored in the session, so you have to start a new tab, log out and in, or something to get it to flush. I tried making a new tab and it didn't work, but when I created an incognito window it worked... Oi.

Please consider adding a way for developers to flush the schema so we can see immediate changes take place.

**Comment by adamsilverstein** [comment]
@JasonTheAdams I assume this issue is for the JS Client @ https://github.com/WP-API/client-js? 

According to the sessionStorage docs, the session should flush automatically when you open a new tab, you may have been seeing some other caching at play? you can also flush the session cache in JavaScript using `sessionStorage.clear()` - is that what you are looking for?
