### ISSUE TITLE
Soundcloud Shortcode not working

### ISSUE THREAD

**Issue by jackreichert** [WP-API/WP-API#2550]
The Soundcloud shortcode is coming through the api call in content.rendered as-is and not rendered as a shortcode.

**Comment by AlbertGuadan** [comment]
Hi,  i am wondering 
  if you are pulling data from, Soundclouds'; API, or a WP- plugin?
 Are you making calls straight to Soundcloud from the 
WordPress API console?

if so can you post what this looks like here ?

**Comment by jackreichert** [comment]
Thanks so much for getting back to me so quickly!

Let me know if you’d like more info!

**Comment by jackreichert** [comment]
I'm using the WP-API plugin for the endpoint. I got the shortcode from the soundcloud page under share>embed then clicked "WordPress".

Best wishes,
Jack Reichert
@jackreichert

**Comment by jackreichert** [comment]
It looks like it’s not the oembed. I replaced the shortcode with the link to that page… Not sure where the shortcode si being rendered.

**Comment by AlbertGuadan** [comment]
If your using a  

> **[shortcode]**
>  from another platform to WordPress  
> and or its API,  your going to need an API key from the other site, 
> and place it where instructed.

**Comment by rmccue** [comment]
Hi! Seems like whatever plugin is registering the shortcode isn't doing so for the REST API. The API runs a little early (`parse_request`), so some hooks will never fire (`wp`, `template_redirect`, etc).

Check with the plugin author on this, as they may need to change their plugin. We run the standard `the_content` filter, which handles all the shortcode replacing, so I suspect the issue is the shortcode registration hook.

**Comment by jackreichert** [comment]
Thanks. That's the strange thing, was not using a special plugin to render it.

I switched them over to proper oembed, which is working, so you can close the ticket.

Thanks for your help!

Best wishes,
Jack Reichert
@jackreichert
