### ISSUE TITLE
Posts results order

### ISSUE THREAD

**Issue by agustina-biscayart-movile** [WP-API/WP-API#2554]
Hi there!

I'm usign the parameter "search" to get those posts that matchs with specific term. I've seen that there are this options to order the results by:

![image](https://cloud.githubusercontent.com/assets/12632582/16305990/8d35329e-3932-11e6-89b2-8f22f5e99dbb.png)

Do you know if there is a way to order the result by "**best match**"?. For example, if I look in my WordPress site by "pizza" and a I have 3 documents whit that word: one with _pizza_ in the tittle, other with _pizza_ in the subtitle and other with the word _pizza_ just as part of the text, the site returns the results exactly in that way. But using this plugin, I get the results not always in that order, it uses the default that is "date".

Do you know if there is something that I can do to change this?

Thanks!

**Comment by almirbi** [comment]
Hello there,

can you show us how are your posts being rendered on your site, without the REST API?

Cheers

**Comment by websupporter** [comment]
Hi,
sorry for answering so late. I spoke with @rmccue while WCEU. Basically, we are missing the WP build in relevance search for the orderby parameter. I tried it with such a query, and I think this is what you are looking for.

I will do a PR and hope it will be part of the WordPress REST API soon.

If it would be part of the API you could perform a request like this:
`http://local.wordpress-trunk.dev/wp-json/wp/v2/posts/?search=pizza&orderby=relevance`

**Comment by websupporter** [comment]
I was digging a bit around in the discussions around orderby, since I was not to sure, maybe I would find something which is a stopper for adding the relevance as a orderby value. So far I haven't found anything, but something else. If you do not want to wait, or if this PR will not be part of the plugin, there is a workaround, how to add `relevance` to the allowed orderby values. See here: https://github.com/WP-API/WP-API/issues/2265

**Comment by rmccue** [comment]
This was added in #2579.
