### ISSUE TITLE
Login (load cookies) for given user data

### ISSUE THREAD

**Issue by atwellpub** [WP-API/WP-API#2562]
I have an app on the same server as the wp instance. We've managed to get it to register a user on wp after signing up through the app, but we want to send people to restricted content hosted on the wp instance while they are logged into the App without them having to log in again. This means loading the correct WP Cookies inside the app, but I'm not sure how to do that or if it's possible with version 2.0 of the API. 

Any advice or leadership appreciated.

**Comment by danielbachhuber** [comment]
Can you share more details about how your app is implemented, and what you've tried already?

**Comment by atwellpub** [comment]
Sure I'm recording the progress here: 
https://wpchat.com/t/questions-about-wp-json-api-application/1537/2

**Comment by almirbi** [comment]
I have used the OAuth plugin instead of cookies for the user to login and then save the access token for each subsequent call to the API. Your situation sounds like you could use the same approach. 

I have wrote an article on SitePoint on how to achieve something similar to this, should be published any day now, I will follow up with a link, _might_ be able to help you.

Cheers

**Comment by rmccue** [comment]
Logging in via the API is intentionally not supported and won't ever be; use the regular WordPress login process if you need a user to have cookies, or use a supported authentication scheme (such as OAuth).

**Comment by almirbi** [comment]
@atwellpub There you go: https://www.sitepoint.com/angularjs-wordpress-rest-api/
