### ISSUE TITLE
How to insert image using WP REST API?

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2563]
I'm using WP REST API to post article into wordpress. How to insert image using WP REST API in the post?

I tried using`<img src="url_to_img.png" />` in the post, now the html code displayed as code but not image in my post.

**Comment by azhard4int** [comment]
@dodoflying , can you paste your code over here, it will give us better understanding and help you to solve your problem.

**Comment by ghost** [comment]
I tried using`<img src="url_to_img.png" >` directly in the post, now the html code displayed as code but not image in my post.

```
 $content='text text <img  src="url_to_img.png"> text';
         $data = array(
                'title' => $title,
                'date' => $post_date,
                'content' => $content,
                'status' => 'publish',
                'categories' => array(4),
                'tags' => array(7,6,5),
                'featured_media' => $images[$rand_key]

            );

        $response = wp_remote_post( $url, array (
            'method'  => 'POST',
            'headers' => $headers,
            'body'    =>  $data
        ) );
```

**Comment by almirbi** [comment]
Hello there,

the way you tried it is just to add HTML into the content field. It will not magically find and upload the picture you added as source. 

What you have to do is first call the [media](http://v2.wp-api.org/reference/media/) endpoint in order to upload the picture, and then pass the ID of the added media into the `featured_media` field.

Keep in mind that when doing a POST on _/wp/v2/media_, you need to specify the filename you want to upload in the header, like this:

``` php
$headers['Content-Disposition'] => 'attachment; filename=url_to_img.png'
```

Cheers

**Comment by ghost** [comment]
Thanks Almirbi! I just want to insert a picture from a picture CDN website instead of uploaded to my own website. Any suggestions to do this without upload a picture?

**Comment by almirbi** [comment]
Add a custom field where you will pass in the URL of your picture from a CDN, and then render it from that custom field instead from featured image. Keep in mind you have to make sure that WP-API knows about that custom field.

http://v2.wp-api.org/extending/modifying/

EDIT: even though since you are hosting the image elsewhere, and if you provide the full URL to the post content ( as you initially did ), it should actually work. But nonetheless I would recommend adding a custom field, it's cleaner and easier to update.

Cheers

**Comment by dleeward** [comment]
You could also use the Jetpack API from Wordpress.com to do what you want to do. See the media_urls field at https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/new/ We use it without any problem.

There was an issue here last year that discussed adding this capability, but I can't find it.

**Comment by ghost** [comment]
@almirbi , i read the documents but still don't know how to "Add a custom field " for the image. Can you give me a example?

Thanks!

**Comment by kadamwhite** [comment]
I'm actually a little confused about your desired end goal: can you clarify whether
- You have an image already available by URL on a CDN, and wish to include that image inline within a WordPress post; or
- You have an image already available by URL on a CDN, and wish to use that image as a featured image; or
- You have an image you wish to upload to the CDN?

**Comment by ghost** [comment]
Sorry about that. My question is

_I already have an image available by URL on a CDN, and wish to include
that image inline within a WordPress post;_

Regards,
Don

**Comment by kadamwhite** [comment]
If that is the case, @dodoflying, I would expect that including the `<img>` tag in the HTML of your post _should_ be working. There is no added interaction with the `/media` endpoint necessary if the image is not supposed to live within WordPress.

I made a quick test and POSTing this object:

``` json
{
  "title": "has an image",
  "status": "publish",
  "content": "<img src=\"http://path.to.a/image/file.jpg\" />"
}
```

successfully created a post with the title "has an image" and the image tag properly visible in its content. What method are you using to create your post object?

**Comment by ghost** [comment]
Thanks kadamwhite. It's working now. I guess i forgot to escape the double quote.

**Comment by kadamwhite** [comment]
@dodoflying glad to hear it!
