### ISSUE TITLE
List posts with sticky posts first

### ISSUE THREAD

**Issue by clemorphy** [WP-API/WP-API#2565]
Hi

Is there a way to list posts, ordered by date (default behaviour) but with sticky posts at the top of the list ?

Currently when I set a post as sticky, it doesn't come first in the list, its order is defined by its publication date.

And in the documentation, I can't see any `sticky` reference in the List Posts argument list.

**Comment by kadamwhite** [comment]
While I am not at a proper computer to test this, my understanding is that `/wp-json/wp/v2/posts?sticky=true` Is intended to return the collection of only sticky posts. Sticky posts are deliberately not included in the API's default response collections because they are essentially a presentational element that a designer may or may not choose to emphasize.

**Comment by kadamwhite** [comment]
(And if `sticky=true` does not work I believe that would indicate a bug)

**Comment by danielbachhuber** [comment]
> Is there a way to list posts, ordered by date (default behaviour) but with sticky posts at the top of the list ?

No, it's not possible at the moment. See https://github.com/WP-API/WP-API/issues/2210#issuecomment-178230263
