### ISSUE TITLE
Allow Objects other than post types and taxonomies to be overridden

### ISSUE THREAD

**Issue by pcfreak30** [WP-API/WP-API#2583]
Right now you can set the controller for a post type or taxonomy, but you can not set it for post statuses,  users, or comments. Right now I have to copy/paste all the routes and force an override.

**Comment by BE-Webdesign** [comment]
Hi @pcfreak30,

Thank you for using the WP REST API.  Can you elaborate a bit more on a use case for what you are trying to achieve?

**Comment by joehoyle** [comment]
The controllers for statuses and users (and any other "fixed" routes for that matter) are not meant to be over-writable, as those features are fixed in WordPress, a CPT is not fixed, as WordPress has an internally API for registering those. 

If you want to make the `users` endpoint act differently you should add a new route at `/mynamespace/v1/users` if you really want, you could probably subclass `WP_REST_Users_Controller`.
