### ISSUE TITLE
Creating themes/plugins which require v2.0+

### ISSUE THREAD

**Issue by kosso** [WP-API/WP-API#2585]
While developing a plugin or theme, is there a simple way of determining if the WP-API v2.0 or above (and WP-API/OAuth1.0a) is installed? It is a matter of seeing if `/wp-json/` etc. exists? 

And then making it impossible to install/activate if not?

Thanks.

**Comment by kadamwhite** [comment]
I am not sure about whether there is a constant or method you could call: if there is not (and the core team could weigh in on that point), you'd be limited to requesting the root endpoint data (which I believe you _can_ do through PHP, without incurring an HTTP request) and inspecting that endpoint data to see if it supports oauth. 

That said, why aren't you relying on cookie and nonce authentication if you're running a theme or plugin? If you're executing code within the same domain as the API install I believe that to be the simplest option for Auth.

**Comment by rachelbaker** [comment]
@kosso You check for the presence of a class or function like `if ( class_exists( 'WP_REST_Controller' ) )` used within the WP API v2 endpoints.  I assume you are asking about checking for the WP API v2.0 endpoints held within this plugin, since the REST API infrastructure is present in all WordPress sites versions > 4.4.  

Closing this, as it is a support question which is best addressed in the WordPress.org Support Forums (https://wordpress.org/support/) or the WordPress Stack Exchange (http://wordpress.stackexchange.com/).
