### ISSUE TITLE
retrieve all categories

### ISSUE THREAD

**Issue by frengo1970** [WP-API/WP-API#2606]
Hello. I need to retrieve all categories from a site but i can see only 10 categories.

here the code
 `///CATEGORIE----------------------------------------------
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "http://italyveritas.com/wp-json/wp/v2/categories",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_POSTFIELDS => "",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic YWRtaW46ZnJhbmNlc2NvLjEyMzQ1",
    "cache-control: no-cache",
    "content-type: application/json",
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
}

$json_output = json_decode($response, true);
for($i=0; $i<count($json_output); $i++) {
    echo $json_output[$i]['id'].": ".$json_output[$i]['name']."<br>";
}
//
`
where i do wrong?
regards
Francesco

**Comment by kadamwhite** [comment]
Hello Francesco! You didn't go wrong anywhere, categories are just paginated collection—so you can adjust the number of categories you receive with `?per_page=X`, but since that has a maximum then eventually you'll need to select the next page using `?page=2`, etcetera.

You can make requests for `categories?page=2`, `categories?page=3`, and so on until you get an empty set back; or else you can inspect the response headers to see the number of pages (`X-WP-TotalPages` header) and the total number of categories (`X-WP-Total` header), as in this example below:

![screen shot 2016-07-19 at 1 42 28 pm](https://cloud.githubusercontent.com/assets/442115/16960263/a927d5b8-4db6-11e6-8abb-01831a3af908.png)

then you can use that `X-WP-TotalPages` to loop through all pages in sequence, to get every category.

_[Edit: Updated to discuss "categories" and not "comments"; but the two work the same!]_

**Comment by BE-Webdesign** [comment]
Thank you @kadamwhite, was just about to respond but you did a much better job haha.

**Comment by frengo1970** [comment]
Hello @kadamwhite , now work :)
thank'you very much
Francesco
