### ISSUE TITLE
Access to API REST v2 with GET without access! 

### ISSUE THREAD

**Issue by uganof** [WP-API/WP-API#2621]
It 's normal access information via REST API without any authentication ? I hope not!
Last version of wordpress and rest api v2

**Comment by kadamwhite** [comment]
Hello @uganof! Since you've closed this issue it may be resolved, but just in case: yes, some information is available from WordPress through the API without authentication; but this information should match what is available publicly in HTML form in a normal WordPress site. It is possible for sites to restrict access to more or less content depending on their own requirements. Thanks!
