### ISSUE TITLE
Every post update saves a revision

### ISSUE THREAD

**Issue by ellatrix** [WP-API/WP-API#2629]
Not sure if this has been discussed before, but I couldn't find anything.

I know core does this when calling `wp_update_post()`, but for this API it seems a bit unexpected. IMHO it should be up to the application to create revisions.

Imagine an application wants saves quite often between user edits (à la Google Docs), the amount of revisions grows quickly and it becomes hard to see the differences between them as there are many with just a small edit. Maybe instead the application wants to group smaller edits into one revision or group them by session, but that's not possible at the moment.

Would love to see some discussion around this. :)

**Comment by rachelbaker** [comment]
@iseulde Thanks for filing an issue.  I think the expectation for most users of the API would be to have edits to a Post from the default post_type REST API endpoint to behave the same as wp-admin.  

I understand the use-case in your example, and saving/storing revisions for each minor change would quickly get out of hand.  
I haven't looked, but I believe there is a hook that can be used to prevent revisions from being saved in either `wp_update_post` or `wp_insert_post`.  @adamsilverstein may know off the top of his head.

**Comment by ellatrix** [comment]
Yes, if you are able to, you can do: `remove_action('post_updated', 'wp_save_post_revision', 10);`

**Comment by adamsilverstein** [comment]
@iseulde Yea, for better or worse, the API tends to do exactly what core does - in this case saving a revision for every change.

I think what you want here is 1. a way to avoid saving a revision on a per-request basis and 2. a way to avoid saving a revision when posting to a site where you may not have code running that can disable the `wp_save_post_revision` callback.  If you do have access to the destination server you can remove the filter as you suggested, or simply return false in `wp_save_post_revision_post_has_changed`

Looking at the function, one other option I see is to leverage the early exit on  `if ( 'auto-draft' == $post->post_status )` - if you can put the post into `auto-draft` status then you can send a series of changes and revisions won't be saved.

In the future, I'd love to see the internals of the revisions system switch to storing the actual changes instead of storing full revisions of each change which might make not storing revisions for every update less important.

**Comment by ellatrix** [comment]
That would be an option if the API accepted `auto-draft` as a status.

**Comment by aaronjorbin** [comment]
How are auto-drafts handled in the API right now?

**Comment by aaronjorbin** [comment]
Asked in slack, and according to @rmccue right now auto-drafts are not supported.  additionally: 

> We’re not sure we want to support them, primarily
> You could likely use filters to support them in a plugin though

I tend to think that auto drafts would be a good thing to support, but I don't think it needs to block 2.0.  In the future, being able to append `auto-draft=true` onto a save request makes the most sense to me.

**Comment by danielpunkass** [comment]
As the developer of a 3rd party WordPress client application, I can say that I like the default behavior of WordPress saving a revision. Although it's rare that customers make a "data-losing" mistake using my app, it's great that when they do I can point to the revisions and usually offer them a way to restore their data.

**Comment by kadamwhite** [comment]
Decision from [WP Dev Chat 2016-09-28](https://wordpress.slack.com/archives/core/p1475096619003188): this behavior stands, all updates through the API will save a revision by default. Auto-draft support (#2737) will likely be added to address this in the future, but auto-draft support will not block merge.
