### ISSUE TITLE
Fetch a page

### ISSUE THREAD

**Issue by lakshmiaswath** [WP-API/WP-API#2637]
I have pages in wordpress . I have installed wp rest api . when i do get call to list the pages using http://www.skinlaundry.com/wp-json/wp/v2/pages , I get only few pages .Some pages are missing . How do i add them to this list so that it can be rendered ?

PS : This is a question , not an issue.

**Comment by websupporter** [comment]
You can browse through the pages with `?page` like
`https://www.skinlaundry.com/wp-json/wp/v2/pages?page=2`

Have a look into the Headers of the response, you will find
`X-WP-Total` telling you how many pages are found and
`X-WP-TotalPages` how many pages you need to browse to read all of them.

You can use `per_page` to get more results per page:
https://www.skinlaundry.com/wp-json/wp/v2/pages?per_page=100
`100` is the maximum as far as I know.

Hope this helps :)

**Comment by kadamwhite** [comment]
the API separates collection responses out into pages, so I suspect you are only seeing the first page of "page" content results. Try https://www.skinlaundry.com/wp-json/wp/v2/pages?page=2 ?page=3 and so on: you can also pass ?per_page=x to get x pages back, but that functionality is capped at 100 items per page for performance reasons so you may need to use both ?per_page=x&page=y

Closing since this does not seem to be an issue with the library functionality, but please comment below if this solution does not work for you. Thanks for using the API!

**Comment by lakshmiaswath** [comment]
Hey @kadamwhite , @websupporter  thanks for the reply . That really helped .I'm new to rest-api , i have one more question to ask ,

When i try to render the pages using https://www.skinlaundry.com/wp-json/wp/v2/pages?per_page=100 , lists all the pages required . But i observed that for some of the pages the field "rendered" has  the base url as differently 
For ex: 
1) Object with id : 4333 has rendered field as url   "https://www.skinlaundry.com/?page_id=4333"  
2) Object with id : 507 has rendered field as url  "http://skinlaundry.wpengine.com/?page_id=507" 

 Why is it so and how can i change that ?
