### ISSUE TITLE
AngularJS Client

### ISSUE THREAD

**Issue by jeffsebring** [WP-API/WP-API#264]
I wrote a module with plugin for AngularJS apps to use the API via ngResource. It seems to be working very well.

It would be great to have some feedback, testing, etc from other AngularJS + WordPress users.

https://github.com/jeffsebring/angular-wp-api

**Comment by kadamwhite** [comment]
Closing this since there doesn't seem to be any more action to be taken—the resources page is live at http://wp-api.org/resources.html and includes the Angular client. I've seen a good handful of Angular WP-API posts over the past months, using both this and https://github.com/shprink/wp-api-angularjs

**Comment by benschac** [comment]
Hey, if you look on the docs site theres a markdown typo for where an angular client should be.
