### ISSUE TITLE
Javascript return all posts

### ISSUE THREAD

**Issue by wblaircox** [WP-API/WP-API#2640]
I'm at the end of day 2 on trying to get this to work. Starting to wonder if it it's even possible at the moment. I've been searching and reading everything possible. I have the API plugin installed, and have tried testing using HTTP and GET, but after hours, learned that my server uses CGI for php and that apparently is a bug and authentication. 

I did get the basic examples for the javascript examples working when run from a page withing my Wordpress site - perfect, that will work for me. Now, all I need to do now is return all posts for the current logged in user. I can easily return a post by id, but that's it. By id won't cut it.  

The below is as close as I have gotten. I've tried many permutations with no luck. Is this even possible and if so - how for the love of god do we get it to work?

`function getposts() {
        // Load all posts
        var postsCollection = new wp.api.collections.Posts({
            data: {
                'filter': {
                    'category-slug': 'ChartData',
                    'posts_per_page': -1
                }
            }
        });
        postsCollection.fetch();
        console.log(postsCollection);
    };`

Thanks!

**Comment by BE-Webdesign** [comment]
Hi @wblaircox,

Thank you for using the WP REST API.  The root of the problem is trying to use `posts_per_page = -1`  Using that is not a good idea for a number of reasons and API tries to prevent people from exploiting that.  What you want to do is loop through the collection.  The max `posts_per_page` is 100, using the `per_page` argument not filter.  In the response you will get a `X-WP-Total-Pages` header.  This header indicates how many pages are in the collection.  You can then loop through the pages by using the `page` parameter and push the page collection into some array, until you have gone through all of the pages.  Now you will have the complete collection.

wp-api.js already has a built in way to do it.  Once you have your `postsCollection.fetch()` you can do `postsCollection.more()` to grab the next page.

**Comment by wblaircox** [comment]
Hi @BE-Webdesign,

I'm trying to learn this as best I can, many thanks for the help. I closed this one as I figured it out that I was trying to view the draft / private posts. It shows published with no issues. I'm spending the extra time to learn this because I want to use it in lieu of making direct database queries to save user info in my app I'm running inside WP. So far WP has shocked me at it's capabilities, so I've kept going. 

As I understand it from the documentation so far, if I was able to show draft/private posts, it would do so only for the currently logged in user. This is ideal in my case as that would allow me to save and retrieve user data based on their logged in account. 

So I've been working all this week on just this one goal. Not sure how much more time I can devote to doing it this way. Seems really simple, but for some reason the filter by status just doesn't work.

**Comment by BE-Webdesign** [comment]
> for some reason the filter by status just doesn't work.

You need to authenticate to the API with a user who can view the draft/private posts.  [Read the authentication guide for the API](http://v2.wp-api.org/guide/authentication/) and it will get you moving in the right direction.

**Comment by wblaircox** [comment]
Done that. It shows in the header that the cookie is showing the logged in user. It just returns published posts only. Does this have something to do with the PHP CGI bug discussion I came across?

**Comment by BE-Webdesign** [comment]
Can you post the request and response in a gist?

**Comment by wblaircox** [comment]
Sure, it has information I'd like to keep private. How do I get it to you?

**Comment by wblaircox** [comment]
Despite the cookie info, I tried https://brewwizz.io/wp-json/wp/v2/users/me and it says I'm not logged in. I have not been able to get basic auth to work using Postman or cURL or any other method. My PHP is running on CGI. 

So I placed the following on a page within Wordpress. Same result. Do I even have the syntax correct?

function getpost() {
        // Load an existing post
        var postsCollection = new wp.api.collections.Posts({
            data: {
                'filter': {
                    'post_status': 'draft',
                    'posts_per_page': -1
                }
            }
        });
        postsCollection.fetch();
        console.log(postsCollection);
    };

**Comment by BE-Webdesign** [comment]
You can pass the Authorization header directly into the environment using the statement below in your Apache config somewhere (assuming you are running Apache).  That should solve your auth issues for the time being.  It is not recommended to use basic auth on production environments.

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by kadamwhite** [comment]
I'm not as familiar with the Backbone client, but two things stand out in your example code:
- in general usage, `posts_per_page` is superceded by the `per_page` query parameter, and `-1` is disallowed due to the risk large queries post to site performance—per_page is capped at 100;
- and `post_status` is handled by the 'status' query parameter

so, maybe also try these parameters: 

``` js
{
  status: 'draft',
  context: 'edit', // may be implied within the Backbone code?
                   // it is required when using "status" with node-wpapi
  per_page: 100
}
```
