### ISSUE TITLE
Backbone Model structure differences in fetch and save

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/WP-API#2643]
As I work more and more with the JS client, I find that it's pretty awkward how things like content/title change depending on whether they're being saved versus fetched. The title, for example, is fetched as an object with raw and rendered properties. On the other hand, when saved it's supposed to be a string.

Especially when taking advantage of collection and model events, the structure of the model isn't reliable. I'm changing the title in one area when the title updates in the model. Since the `'change:title'` event triggers both when the model is synced and when `model.set('title')` is called, I end up needing the following:

```
titleChanged: function() {
  var title = this.model.get('title');
  if ( 'string' === typeof title ) {
    this.$el.find('.lv-title').text(this.model.get('title'));
  }
},
```

Not the end of the world, but it definitely made me wonder about the importance of consistency in the model structure. Doesn't seem like a particularly reliable model if it changes depending on which way it's headed.

Thoughts?

**Comment by BE-Webdesign** [comment]
Hi @JasonTheAdams 

Can you open this issue on the [js client repo](https://github.com/WP-API/client-js)?  Going to close this out at the moment.

**Comment by JasonTheAdams** [comment]
To bring in the [discussion I opened](https://github.com/WP-API/client-js/issues/132#issuecomment-239025198) in client-js:

@adamsilverstein:

> Currently the WP REST API itself returns the title (content as well) as an object, as you described with `rendered` and `raw` data points. The API expects, however, titles as strings. So the main issue you raise is actually with the API itself and not the client js specific handling. You might try asking about why this is so in the slack room, I remember asking myself and can't recall the reason its done that way. Given that scenario, how would you expect the client to behave, should it try to help you by normalize the data sent to events? we do that a little with Dates where the API returns a timestamp and we turn that into a more useful date object (and the reverse when saving).
> 
> In regards to your issues with changes on the models, you may be able to work around the issue more cleanly (although your approach is reasonable) by not listening for change, instead listening for sync events for updates from the server and then triggering and listening for custom events when you change a property internally, eg. `model.trigger( 'title:changed')`.

Myself:

> Thanks for the feedback. Regarding the events I'm listening for, I'm listening to both `sync` in one place and `title:changed` in another. I'm using `sync` for retrieving the models from the collection, and `title:changed` for when the user changes the title in one place and I want it to be reflected in another.
> 
> But yeah, I wondered where this really belonged. I appreciate the `rendered` and `raw` distinction, but it doesn't seem right that a post can't be retrieved and the title updated without changing the structure of the model consequently. In fact, if you were to retrieve a post and immediately update it, it wouldn't work. That just doesn't seem right.

**Comment by rmccue** [comment]
> The title, for example, is fetched as an object with raw and rendered properties. On the other hand, when saved it's supposed to be a string.

This is not strictly true; we _accept_ strings when saving to make it easier for handrolled clients, but you can send back `content: { raw: "text" }` and that will be [handled correctly](https://github.com/WP-API/WP-API/blob/c661101fd4f8889a68c34105e09a39e00c2e122f/lib/endpoints/class-wp-rest-posts-controller.php#L726-L751) as well. Ditto for title and excerpt. One of the basic principles of the API is that you should be able to send back the exact same data you receive.

Per [your comment on Slack](https://wordpress.slack.com/archives/core-restapi/p1470873348000734), we originally had `title` and `title_rendered`, but as it turns out, people didn't quite understand the distinction and the API was misused. That's why we moved it to an object instead, so that you consciously have to pick one when you use it.

**Comment by BE-Webdesign** [comment]
Well that clears it up; now it makes sense.  I tried going back through logs but couldn't find anything related to this.

Sadly we can't make everyone happy and I think it makes sense to leave this as is.  No sense in potentially breaking BC because of this.

Going to close out this issue.  Feel free to continue discussion here if need be.

**Comment by JasonTheAdams** [comment]
Ah, that's good to know. I'll just work with the title.raw construct, then. Thanks, @rmccue!

**Comment by adamsilverstein** [comment]
Thanks for clarifying @rmccue good to know the api accepts the `raw` parameter and the background on the architectural decision as well.
