### ISSUE TITLE
Unable to filter posts endpoint using `?filter`

### ISSUE THREAD

**Issue by deonvisser** [WP-API/WP-API#2647]
.../posts?filter[fieldname]=xxx does not work. I have tried it on a few different fields. All post data is returned.
Is this the correct syntax? From what I can see, others seem to have the same issue.

**Comment by kadamwhite** [comment]
Are you by any chance using Nginx for your server? This issue is a frequent culprit: https://github.com/WP-API/WP-API/issues/1926#issuecomment-168090756

If not, or if it's just filter and other query parameters like ?per_page= and ?page= are working, could you share more information about what parameters you have tried, and what your server setup is? Does this still occur if you disable other plugins?

**Comment by rmccue** [comment]
Closing out, no response in a month.
