### ISSUE TITLE
Posts orderby modified

### ISSUE THREAD

**Issue by ericlbarnes** [WP-API/WP-API#2651]
In the API docs for [posts](http://v2.wp-api.org/reference/posts/) it lists available ordering of: 

_One of: `date`, `id`, `include`, `title`, `slug`_

Can the date modified be added into this? Either in the core or by hooking into the `add_action` ?

**Comment by BE-Webdesign** [comment]
Hi @ericbarnes,

Thank you for using the WP REST API.  I believe you can use the filter parameter to do additional sorting as you might in `WP_Query` instead of using what is provided in the top level parameters.  Probably the easiest solution is to do something like `wp/v2/posts?filter[orderby]=modified`; not 100% sure if that works though.

Check out WP_Query params on the WordPress codex, and experiment with the parameters that will give you the ordering you want and put that into the filter param.
