### ISSUE TITLE
Overwriting default behaviour for letting subscriber edditing comments

### ISSUE THREAD

**Issue by MaximeCulea** [WP-API/WP-API#2663]
Hi guys,

I can't tell this is a bug or whatever, but more asking you for the good thing to do.
I want subscriber to edit their own comments. In PHP I can manage this condition to show up an edit button or not and then submit with rest api with a nonce ..
My main issue is concerning the method to check rights on UPDATING comments in Comment Controller : https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-comments-controller.php#L1167.
It means, in how it is writed, that if I wanna achieve what I wanna do, I have to implement this entire controller and change the check method in "permission_callback" ?

Thx in advance for your help !
Maxime

**Comment by websupporter** [comment]
WordPress has the internal capability `edit_comment`, which is also used in the REST API to determine if someone is allowed to edit a comment. I would suggest another way to achieve what you want:

You could add this capability to the subscriber-role to tell WordPress subscribers are allowed to edit their comments. https://codex.wordpress.org/Function_Reference/add_cap

Could this solve your problem?

**Comment by MaximeCulea** [comment]
You are right about this, thx, but it doesn't change anything for me.
In fact edit cap, in how is is called from controllers check will call has_cap edit posts too. I have managed to add all the capabilities and it doesn't change. Still no right to edit. This fires when unfiltred_html cap is tested which returns do_not_allow.
I am little bit lost about all this capabilities .. :(

**Comment by websupporter** [comment]
Ah! Sorry, you are right. You get kicked out with `moderate_comments`. This is probably like WordPress core is doing it. I am not too familiar with this part of core. From how I see it: The REST API needs to replicate the permissions like they are in core. If subscribers can't edit comments in core, they shouldn't be able to do so via the REST API (This would otherwise end up in a mess). Well, probably its not a wise idea to give subscribers `manage_comments` capabilities, so I guess the best way would be indeed to go with your own controller then, which is a bit "aaaahh, just for this...", I know.

But maybe someone else has a better idea :)

# 

Edit: But I will have a look into how core is handling this. Maybe we do not get this properly.

**Comment by websupporter** [comment]
Does someone has an idea? In the `wp-admin/comment.php` it is only asked for `edit_comment`. Than I thought, maybe the menu point "Comments" wouldn't show up, but this is rather strangely constructed and relies on `edit_post` (which might change in the future, if I see this correctly: https://core.trac.wordpress.org/ticket/12104#comment:34).

Do we need the `manage_comments` to edit comments?

**Comment by MaximeCulea** [comment]
I have news about this. There was already a core track here : https://wordpress.org/support/topic/edit-comment-not-working#post-1821646

So to make this possible, I did like this thx to @petitphp : https://gist.github.com/MaximeCulea/06b3a1d99f99295cc000ff087c9e8318

**Comment by websupporter** [comment]
Hi @MaximeCulea,
thanks a ton for sharing this and working with the WordPress REST API. I've read your solution and it looks quite sound. I will have a second look by tomorrow.

Thanks again.

**Comment by MaximeCulea** [comment]
As it is a default WP behaviou, just use this snippet above or extend Rest Comment Controller.
To be closed.
