### ISSUE TITLE
How to get first image from post and how to remove img tag from post content

### ISSUE THREAD

**Issue by NesooseN** [WP-API/WP-API#2666]
Hi, can anybody tell me how to do this:
- Get first image attached to post (there is no featured image)
- How to strip img tag from post content but keep all other tags ?

**Comment by kadamwhite** [comment]
Neither of these questions are really related to the REST API itself (they relate to general API-independent response processing, if I interpret your question properly), so I'm going to close this issue because there is no support action we can take -- but I'll try to answer as best I can, as well.

The response you get for a post will have the structure

``` js
{
  id: ##,
  title: { /* ... */ },
  content: {
    rendered: '<p>Some string of HTML</p>'
  },
  // ...
}
```

Both of your questions can be answered by processing that `post.content.rendered` HTML string, probably with a regular expression. As you didn't specify the language you are using, I'll use JavaScript as an example.

Assuming the post contains the content

```
<p>Some paragraph</p>
<img src="http://my.cdn.com/image.jpg" alt="an image" />
<p>Some other paragraph</p>
```

then the process to get the first image attached to a post would be to find the first `<img>` tag in the markup, and extract its `src` attribute. **This is error-prone,** as the featured-image association will always let you get access to multiple resolutions of image, but in this case you're limited to only the size specified in the image URL within the post content.

To find that image tag, we'll use a [Regular Expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions). Regular Expressions are a [notoriously poor](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454) tool for parsing HTML, but I think they're your best bet for now.

A RegEx we can use here is `/<img[^>]+src=("[^"]+"|'[^']+')[^>]*>/i` which will match any image tags, "capturing" the `src` attribute (with quote marks). So, to get the URL of the first image, you would:

``` js
// .match will return `null` if no image is found, or else will return an array
// of the entire matched string and any captured groups. In the case of
// our example above, the result will be
//    [
//      '<img src="http://my.cdn.com/image.jpg" alt="an image" />',
//      '"http://my.cdn.com/image.jpg"'
//    ]
var content = post.content.rendered;
var imgMatch = content.match( /<img[^>]+src=("[^"]+"|'[^']+')[^>]*>/i );
var img;
if ( imgMatch ) {
  // If there was a match, get the last element and strip quotation marks
  img = imgMatch[ imgMatch.length - 1 ].replace( /['"]/g, '' );
  // img now equals http://my.cdn.com/image.jpg
} else {
  img = ''; // No image
}
```

You can use the same regular expression to strip all images, by `.replace`ing them with the empty string:

``` js
str.replace(/<img[^>]+src=("[^"]+"|'[^']+')[^>]*>/i, '')
```

Hope this helped, and thanks for using the REST API!
