### ISSUE TITLE
Capabilites to edit a comment

### ISSUE THREAD

**Issue by websupporter** [WP-API/WP-API#2667]
Based on the discussion of https://github.com/WP-API/WP-API/issues/2663

In https://github.com/WP-API/WP-API/commit/5e66d6c we introduce `check_edit_permissions()` to check if a user is allowed to edit or delete a comment.

I was comparing this to the capabilities in the `wp-admin/edit-comment.php`.

To edit/delete a comment in the admin will fail, if you do not have the `edit_comment` capability or the  `edit_posts` (I guess, this is due to comments legacy) capability.

We require `moderate_comments` and `edit_comment`.

I am not quite sure about this. As far as I understand as soon as the user has the capabilities which are required in the admin, he should be able to perform the same actions through the API. So my questions are:
1. Why do we require `moderate_comments`? Did I miss something?
2. Should we also require `edit_posts` or what is the policy on such old legacy, can we ignore it for the API?

Thank you.

**Comment by kadamwhite** [comment]
Needs @WP-API/amigos input, marking to revisit at next dev meeting

**Comment by rmccue** [comment]
Relevant core ticket: https://core.trac.wordpress.org/ticket/12104

Per [Slack](https://wordpress.slack.com/archives/core-restapi/p1475090042004295):

> rmccue: Specifically, "Why do we require `moderate_comments`? Did I miss something?"
> rachelbaker: Because we are trying to be more consistent than core
> rachelbaker: In summary my opinion is: the moderate_comment permission check makes sense to me because core is wonky. however, I don't know exactly how/why the `moderate_comment` check got added in our logic... and I won't argue removing it

Without `moderate_comments`, you can't access the comments page, but you can see the comments metabox on the post you can access.

Long-term, this should be fixed in core. For now, it makes sense for us to go for the most conservative approach, and only allow access for the intersection of the two capabilities.

> Should we also require edit_posts or what is the policy on such old legacy, can we ignore it for the API?

`moderate_comment` is mapped in `map_meta_cap` to `edit_post`, so this is already handled.
