### ISSUE TITLE
Issues with loading api data in php

### ISSUE THREAD

**Issue by neonwired** [WP-API/WP-API#2669]
I'm using the following to load data in php.

`$wp_api = new WP_REST_Posts_Controller('job');
$request = new WP_REST_Request('get');
$request->set_query_params(
    array(
        'per_page' => -1,
        'status' => array('pending', 'publish', 'future')
    )
);
$response = $wp_api->get_items($request);`

However the 'rest_api_init' action doesn't seem to called until after the first item, so the first item. I suspect there's a better way to do this?

**Comment by BE-Webdesign** [comment]
Hi @neonwired,

Thank you for using the WP REST API! Can you explain what you are trying to do? If you are trying to use the API internally, then you can do something like:

``` php
$job_controller = new WP_REST_Posts_Controller('job');
$request = new WP_REST_Request( 'GET', 'wp/v2/job' );
$request->set_query_params( array( 'per_page' => 10, 'status' => array('pending', 'publish', 'future') ) );
$response = rest_do_request( $request );
```

This would need to come after `rest_api_init`.

To view the different statuses, the user who is triggering these calls will also need the right privileges to see posts that have a status other than publish.

On a side note `per_page => -1` doesn't work and using the built in pagination instead is a best practice.

**Comment by neonwired** [comment]
If you call rest_get_server(); before a request it seems to work.
However if i do $response = rest_do_request( $request ) i get "No route was found matching the URL and request method" error but $job_controller->get_items($request) works perfectly

**Comment by BE-Webdesign** [comment]
@neonwired 

By just calling `$job_controller->get_items($request)` you are circumventing the rest server class, and you will lose out on a lot of awesome stuff by doing that.  I will revise my example above, because I missed one step; registering the routes.  You need to do this and it should work internally.

``` php
add_action( 'rest_api_init', 'prefix_create_job_routes' );

function prefix_create_job_routes() {
    $controller = new WP_REST_Posts_Controller( 'job' );
    $controller->register_routes();
}

$job_controller = new WP_REST_Posts_Controller('job');
$request = new WP_REST_Request( 'GET', 'wp/v2/job' );
$request->set_query_params(
    array(
        'per_page' => 10,
        'status'   => array( 'pending', 'publish', 'future' ),
   ),
);
$response = rest_do_request( $request );
```

If Job is a Custom Post Type you have, then you can also just add  `show_in_rest => true`, `'rest_base => 'job'`, and `rest_controller_class => 'WP_REST_Posts_Controller'` to your registration arguments for the post type and the endpoint will be autoloaded into by the API plugin and the above addition shouldn't be necessary.

On a side-note it is probably better to use jobs instead of job for your rest base though.  If you plan on doing any customization to the endpoints controller class you should also register your routes at a different namespace other than wp/.

Hopefully that helps.

**Comment by kadamwhite** [comment]
From the discussion above it looks like this may be resolved, so I am going to close; @krogsgard is going to make a note to ensure this is captured in the docs site.

If you run into further difficulty please continue the conversation below and we can keep the discussion going!
