### ISSUE TITLE
A good wordpress based web site with rest api for practicing? 

### ISSUE THREAD

**Issue by mister-giga** [WP-API/WP-API#2682]
Can anyone give me a good website to test rest api? I am willing to find a website with many linked categories (parents) and stuff like that to master the wordpress rest api.
I tried to create one on my own but free wordpress.com sites doesnt support it. And the only programming language I know is C#

**Comment by kadamwhite** [comment]
demo.wp-api.org exists, but does not have the most complex sample data. @joehoyle This may be a good opportunity to try to increase the complexity of the data on that site, so that it could serve as a better reference; thoughts?

@mister-giga I have also created https://github.com/kadamwhite/wpapi-vagrant-varietal which is a Vagrant setup to starts a WP-API enabled site with some sample data within a virtual machine. The sample data again may not be comprehensive

**Comment by mister-giga** [comment]
demo.wp-api.org? I think I didn't explain well @kadamwhite . I want a working site with full of data. So I can get the json and display it in my application.

**Comment by mister-giga** [comment]
@kadamwhite  your web site http://www.kadamwhite.com/ looks great for my testing. How can I contact with you?

**Comment by kadamwhite** [comment]
I would prefer you not use my personal site for arbitrary testing. If you
visit http://demo.wp-api.org/ you can exercise the full API; the root
endpoint is http://demo.wp-api.org/wp-json . Alternatively, I recommend
installing Virtualbox & Vagrant and using a virtual machine like the one I
linked previously; if the setup instructions don't make sense please open a
github issue on that project's repository.

Thanks, @mister-giga!
