### ISSUE TITLE
How to filer post by post format standard

### ISSUE THREAD

**Issue by danbeo95** [WP-API/WP-API#2683]
I try use http://localhost/ionic2/wp-json/wp/v2/posts?filter[post_format]=post-format-standard but it dosen't work.How i can fix this problem???

**Comment by BE-Webdesign** [comment]
Hi @danbeo95,

Thank you for using the WP REST API!

`post_format` is a post taxonomy that is not registered to be used by the API by default.  In order to filter by a post format, you would first need to enable that taxonomy to be visible by the API like this in a plugin file:

``` php
$taxonomies = get_object_taxonomies( 'post', 'objects' );
if ( isset( $taxonomies['post_format'] ) ) {
    $taxonomies['post_format']->show_in_rest = true;
    $taxonomies['post_format']->rest_base = post-format;
}
```

The above would need to fire on the after or on the `init` action.

Then you can filter the posts collection by post-format IDs.  So now the request would look like this `GET http://localhost/ionic2/wp-json/wp/v2/posts?post-format=1`. ID 1 should match up to the standard post format.

Alternatively, once `tax_query` is supported by the API, you can use `tax_query` in the filter param. The filter param supports a lot of `WP_Query` arguments, `post_format` is not a `WP_Query` argument. In both cases however, you would need to enable the taxonomy to be visible to the API.

**Comment by danbeo95** [comment]
Thanhk you,but i don't understand "ID=1" you can explain

**Comment by danbeo95** [comment]
hey.i have tested .It work well with post-format image.aside,video...but with STANDARD it still not work ?
can i fix.help me??The result return is empty array

**Comment by westonruter** [comment]
There is no `term` for the “standard” post format. A post with the standard post format merely lacks any `post_format` term associated with it. As such, you'd have to do a `NOT IN` query. Beware of performance problems. See http://wordpress.stackexchange.com/a/152888/8521

**Comment by danbeo95** [comment]
thanks.! i am using wp rest api so where i add this query?

**Comment by BE-Webdesign** [comment]
@danbeo95 It is probably better for you to query the API the normal way and on the client side filter the posts response for posts that have the format you want.

**Comment by BE-Webdesign** [comment]
Going to close out this issue as it is not a bug, but feel free to continue the discussion here.

**Comment by shaheero** [comment]
Hi @BE-Webdesign
I tried this but neither `posts?post-format=video` or `posts?post-format=2` work. Can you help?

```
function show_post_format_in_rest() {
	$taxonomies = get_object_taxonomies( 'post', 'objects' );
	if ( isset( $taxonomies['post_format'] ) ) {
	    $taxonomies['post_format']->show_in_rest = true;
	    $taxonomies['post_format']->rest_base = post-format;
	}
}
add_action( 'init', 'show_post_format_in_rest' );
```
