### ISSUE TITLE
How would I create endpoints/routes to other tables in the database

### ISSUE THREAD

**Issue by KaiP-598** [WP-API/WP-API#2687]
Hi All,

Let's say I have got a table named 'wp_table1' in the database, how would I create a route or endpoint that points to this table, therefore I can retrieve and update the data of this table?

Thanks!

**Comment by kadamwhite** [comment]
@KaiP-598 If you want to retrieve your data from a custom table, you would [register a new endpoint following this guide](http://v2.wp-api.org/extending/adding/), and access the database through PHP (however you normally would within a theme or a plugin) to query for the data to send back when the route is requested. I'm going to close this because I do not believe it to represent a bug, but please open an issue on, or submit a pull request against, [the documentation repo](https://github.com/WP-API/docs-v2) if the instructions in that guide are not clear.

Thanks for using the API!

**Comment by KaiP-598** [comment]
@kadamwhite  Hi!! Thanks for the reply.

Apart from retrieving the data, can I create/update the data of a custom table as well?

THANKS again!

**Comment by KaiP-598** [comment]
@kadamwhite I have just read the guide, should I put the code in functions.php in the theme? or in the plugin.

Also, get_endpoint_args_for_item_schema, what does this line of code do(true), there is not much reference about this line of code.

THANKS
