### ISSUE TITLE
API should send and accept `null` for undefined values

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2696]
See #2657 for the decision on `null` handling: `null` should be sent by the API whenever a value is unknown or not yet set.

A prime example of this is `post_date_gmt`, as described in #2303, which will be `0000-00-00 00:00:00` (an invalid date) for posts newly created via WP-Admin or via this API: if this value is sent to a client literally the API is providing an invalid value. `null` should be sent instead.

Correspondingly, `null` should be _accepted_ by the API for `post_date_gmt` (and other fields that display this issue), so that a client can always turn the response for a resource around and send it back without further transformation: returning the API's output JSON as unchanged input should never trigger an error.

**Comment by adamsilverstein** [comment]
I am starting to work on this issue by writing some unit tests to verify current behavior. 

This ticket should probably be broadened to "The API should accept returned values as valid for updates of the same object." For dates this means that if a null value is returned a null value should be accepted. Currently this appears to be the case. 

For dates, I think we are set for null values... Since https://github.com/WP-API/WP-API/commit/4dc05f35 the API returns null for the '0000-00-00 00:00:00' that WordPress returns for draft posts. I also tested sending in a null value (which you can only do from PHP as far as I can tell). I'm working on unit tests(s) to demonstrate this.

Another edge case I am digging into is slugs. When you create a draft post with no title, the API returns a slug of  "" (empty string). Sending back the same empty string for the slug when trying to update the draft fails because a blank string is an invalid slug value. Here similarly the API should probably return a null value for the invalid/blank slug value (as well as accepting that on input). 

I will continue to work on this issue this week.

**Comment by adamsilverstein** [comment]
After digging into this and writing a few tests, the only issue I found was slugs. When initially creating a post via the api, the slug is returned as an empty string `""`. Taking the post data returned from the API and sending it back was throwing an error because of the empty slug. I added an additional validation check for the slug value and this resolved the issue. Without this change the `test_update_draft_post_with_returned_draft_post_data` test fails.

**Comment by adamsilverstein** [comment]
After updating to to the latest develop branch, I verified that everything _is working as expected_ in terms of unset, empty or null values here - I added a few tests in https://github.com/WP-API/WP-API/pull/2763 to validate. We can address any specific cases that were missed if they arise.
