### ISSUE TITLE
filter[posts_per_page] not working on custom post types in v2 beta 14

### ISSUE THREAD

**Issue by mbillz** [WP-API/WP-API#2759]
After updating to the newest beta (through the Wordpress admin), my get request to a custom post type using a filter for posts_per_page always returns 10 posts.
Here's my request: `http://domain/wp-json/wp/v2/products?filter[posts_per_page]=-1`

I've been able to get 100 posts by using: `http://domain/wp-json/wp/v2/products?per_page=100` but it doesn't go any higher.

I've attempted this on two different sites and have tried with authenticated requests as well. I've also tried increasing the amount of posts to show in wp-admin's Reading area.

For now I've just downgraded to beta 13 and everything is working as it's supposed to.

**Comment by kadamwhite** [comment]
Hello @mbillz and thanks for using the REST API! Unfortunately the ability to set `filter[posts_per_page]=-1` was a bug (#2357), so that specific filter option was removed in beta 14; the correct way to retrieve all resources is to iteratively request multiple pages of results using `per_page` and the pagination headers.

The reason for limiting the number of records that can be returned at once is performance: `-1` is capable of generating a dangerously expensive query on large sites. While this is slightly more frustrating as a developer it's easy to write a wrapper utility method to handle batching those multiple requests, and it is significantly less impactful on the server to return multiple pages of fewer requests than one page of all requests.

It was a _major_ omission on our part that this breaking change was not called out in beta14, because this "bug" was definitely being exploited for its benefits on small sites; and for not providing a warning on that I apologize on behalf of the team. However, this is not functionality that is going to be reinstated, so I'm going to close the issue; please feel free to continue discussion below if there's any way we can help advise on how to work with the collection pagination headers.

**Comment by mbillz** [comment]
Gotcha, thanks for the quick response!
