### ISSUE TITLE
Still having issue Get attachments #806

### ISSUE THREAD

**Issue by leroygumede** [WP-API/WP-API#2761]
For some reason I can't get attachments,

when I call `http://ncevents.co.za/wp-json/wp/v2/attachment`
I get `[]` back.

I tried adding the following in my theme`Functions.php`

```
add_filter( 'query_vars', function( $vars ){
    $vars[] = 'post_parent';
    return $vars;
});
```

 but Its still not working

**Comment by kadamwhite** [comment]
@leroygumede Thanks for using the REST API! How is the `attachment` endpoint being created? It looks like you're explicitly un-registering the `/wp/v2/media` endpoints, which are the normal mechanism for retrieving the attachment for a post (_e.g._ `/wp/v2/media?post=[post_id]`). We'd need to know more about how the `/wp/v2/attachment` routes are being registered in order to help diagnose.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
