### ISSUE TITLE
REST API is still publicly available with the OAuth plugin activated

### ISSUE THREAD

**Issue by kgrvamsi** [WP-API/WP-API#2769]
Hello,

I tried installing the WP-API plugin and check with the OAUTH plugin but as I see with some general issues still which are closed but I want to know how can I render the posts details through API only for Authenticated users/Applications based upon the tokens?

Access for everyone even we have the OAUTH token dosent make sense.

So apart from "Go and write your own Authentication strategy" is there any other way that make this thing possible that the API can be rendered only to authenticated users/application over OAUTH?

Thanks,
Vamsi KGR

**Comment by joehoyle** [comment]
@kgrvamsi the OAuth plugin is meant to add the oauth1 authentication mechanism to the REST API, it's not meant to be make public things private. This just allows you to use OAuth1 as a means of making authentication requests with the API.

If you want to disable unauthenticated access to the rest api endpoints, you can make use of the `rest_authentication_errors` filter with something like:

``` php
add_filter( 'rest_authentication_errors', function() {
    if ( is_user_logged_in() )...
}, 11 );
```

However, I should stress that just because someone is authenticated with OAuth, doesn't mean that they have permission to do anything. A regular subscriber level user can authenticate with OAuth 1.

I'm going to update your title to "REST API is still publicly available with the OAuth plugin activated" as that seems to be your issue here.
