### ISSUE TITLE
how to attach media with post in WordPress REST API (Version 2)

### ISSUE THREAD

**Issue by msaashish** [WP-API/WP-API#2781]
I am trying to post data with attachment but i am not sure how to get file and attach to post when creating post using WordPress REST API (Version 2) i am confused about documentation which is not sure about media upload can any body know how to post data with attachment?

**Comment by kadamwhite** [comment]
@msaashish Thanks for trying out the REST API. We hope to expand the documentation around media handling in the coming weeks, right now all hands have been on deck working on the merge proposal; I'm going to link you to this guide which shows how the flow works in JavaScript http://wp-api.org/node-wpapi/guides/2016/08/15/create-a-post-with-featured-media.html which will hopefully be useful as an example regardless of what language you're using to make the request.

I'm closing this issue out because it is not strictly speaking a bug, but please continue to discuss below if there's any other guidance I can provide. Thanks!
