### ISSUE TITLE
Remove _links from response

### ISSUE THREAD

**Issue by MehediH** [WP-API/WP-API#2784]
Hey guys,

I am currently modifying the REST API v2 and couldn't find a way to remove the _links from the responses.

Is there anyway to remove that?

Thanks

**Comment by t-grm** [comment]
Related: https://core.trac.wordpress.org/ticket/38131

**Comment by kadamwhite** [comment]
@MehediH As you can see in the patch in that track ticket, filtering the results on `rest_post_dispatch` is the most centralized place to be able to remove `_links`; I recommend only doing so when a query parameter is passed, however, so that you don't inadvertantly block other plugins you may want to use from taking advantage of `_links`.

One of the open questions in that core ticket is how this should be handled in a standardized manner, your input would be helpful if you have any thoughts.

**Comment by kadamwhite** [comment]
I'm going to close this because any built-in change to `_links` handling would need to happen at the core infrastructure level, so it's out-of-scope for this plugin (which is for surfacing specific content types using that underlying infrastructure)
