### ISSUE TITLE
Remove the `filter` param and NEVER EVER EVER bring it back

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#2799]
Hiding WP_Query params under the `filter` key (instead of allowing them to be top-level params) was one of our biggest complaints from users of v1 of our REST API.  In Beta 15 [the WP_Query vars in the Posts Controller were moved under the `filter` param](https://github.com/WP-API/WP-API/commit/6b31826acf2ea35a8308fe8558ad76ec812d47cf), inspired by our v1 architecture. 🙍 

Now we have an inconsistent mess.  See #2192 and #2066 (and likely many other filed or unfiled tickets). 

I suggest walking back this change prior to any WP Core merge.

**Comment by rachelbaker** [comment]
Related Slack discussion: 
https://wordpress.slack.com/archives/core-restapi/p1476202307006199

**Comment by kadamwhite** [comment]
I am in favor of removing `filter`, my impression was always that it was a placeholder shim to permit certain types of queries temporarily until they could be supported on a first-party basis by the API. While we do not have full feature parity with WP_Query through first-party (non-`filter`) parameters, exposing WP_Query through `filter` has and will continue to be difficult to support.

I second that `filter` should be removed, but I also caution that it has been a part of the API since v1 and we should therefore provide a plugin option to continue to expose the parameter so that the substantial amount of code that's been written with consideration for `filter` will have a path to continue to work.

**Comment by danielbachhuber** [comment]
I'm in favor of removing `filter`, and like the idea that we can introduce a plugin to shim the existing behavior.

**Comment by mnelson4** [comment]
+1 remove it and provide a shim.

It would probably be nice to have a `doing_it_wrong` message for anyone who's still using it (and that message could point them the shim plugin), although I'm not sure if implementing that in the REST API would be as simple as it is normally (I suppose we'd need to just have a full-on error, instead of a mild notice).

**Comment by JPry** [comment]
👍 to removing `filter`.

**Comment by kadamwhite** [comment]
In the [2016-10-17 API team meeting on Slack](https://wordpress.slack.com/archives/core-restapi/p1476713039007633) this decision was confirmed: we will remove `filter` from the core plugin (this is a breaking change) prior to 4.7 merge or 2.0 plugin release, whichever comes first. A separate plugin will be created that will reinstate the filter parameter so that there is a path forward for API consumers who are depending on that functionality.

**Comment by kadamwhite** [comment]
To be handled as core patch

**Comment by websupporter** [comment]
The related ticket: https://core.trac.wordpress.org/ticket/38378
A first sketch for a "Bring 'em back" plugin: https://gist.github.com/websupporter/1008d297325e6ba6b215b446c2576723

We can't add the filter back to the `get_collection_params()` or am I wrong?

**Comment by AllaManiKumar** [comment]
how di get all posts of particular id?
