### ISSUE TITLE
Can I access draft posts from a client site without OAuth?

### ISSUE THREAD

**Issue by alanmoo** [WP-API/WP-API#2815]
I have a site built that pull posts from the WP-API and renders them in a React component. It works great (thank you for making this!)

I want authors to be able to preview their posts on that site, but I'm having trouble figuring out if that's possible without implementing OAuth on the client site (it's a React app served up by express, so I'd really rather avoid that for this one use case). I've seen the authentication parts of the documentation, but having a bit of trouble getting it working. I can dive down that rabbit hole myself, but I just want to make sure I'm trying something that's even possible.

Right now users can hit the preview button in wp-admin and it opens up the React site with query params that include the post ID and a nonce. Is it possible to use those params to access draft posts from the API? 

(I'm currently on v1, happy to upgrade sooner than planned if necessary to make this work.)

**Comment by kadamwhite** [comment]
@alanmoo Thanks for the question, and thank you for using the REST API; we're glad to hear it has been helpful!

To clarify your question, authors are writing their posts within WP-Admin? Drafts are not available from an external client without authentication, so unfortunately there is no approach I can recommend to get preview access to posts without going through OAuth or one of the other external authentication options. The nonce would only be useful should a regular WP login cookie be available, which will not be the case with requests originating on an external express server.

Apologies for not being able to help more. Because this isn't strictly speaking a bug in the API, I am going to close this; but please feel free to respond below to continue the discussion. Previewing is a very common use case and will definitely be coming under deeper scrutiny in the 4.8 cycle to see if there is a better way to handle this (but that discussion will hopefully occur within the core track ticketing system).

**Comment by alanmoo** [comment]
That's correct, posts are written within WP-Admin. The request starts when an author clicks the "preview" button in WP-Admin, hits the express server which serves up the React app, and then the client side React app would try to access the API.

I haven't really worked with cookies before, but I suspect the problem is that the client app doesn't have access to cookies written on the WP-Admin domain. Is that correct?

If that's the case, is there a way I can store an access token (maybe for a "user" with read-only access) in my server's environmental variables so that it can access preview posts? Or might that be a security concern?
