### ISSUE TITLE
posts_per_page filter not working in beta15?

### ISSUE THREAD

**Issue by jmacaluso711** [WP-API/WP-API#2890]
I'm using v2 beta15 with WordPress 4.6.1 and the posts_per_page filter does not seem to be working.

When I try to filter for all posts with `-1` I get back the default post limit that is set in Reading Settings. As well, when I try to filter for a specific amount of posts I also get the default post limit.

I'm pretty sure I'm implementing correctly:

`/wp-json/wp/v2/posts?filter[posts_per_page]=-1`

Has this been reported at all or could there be something with my setup that is causing this. I tried disabling all plugins, but that didn't resolve the issue.

**Comment by jeremyfelt** [comment]
Hi @jmacaluso711, thanks for opening a ticket. The `posts_per_page` filter was removed (see #2357) as part of the beta14 release. The `per_page` parameter can now be used to paginate through the results. See also #2759 for an explanation of the change.

**Comment by jmacaluso711** [comment]
Hi @jeremyfelt , thanks for the quick response.. 

Is there any documentation on how to return all posts with `per_page` ?

**Comment by kadamwhite** [comment]
@jmacaluso711 the maximum number of records that may be retrieved at once is capped at 100, in order to avoid overloading sites when preparing the response. It's a little less convenient but the best practice is to make several requests for the different pages and to then reassemble the complete set in the client application. For an example of doing this in a mode script, see http://wp-api.org/node-wpapi/collection-pagination/ -- this is built on top of the documented collection pagination headers, so this sort of behavior could be recreated in any client language. 

Apologies for not better documenting this change in the release notes. Hope these tips help, and thank you for using the API!
