### ISSUE TITLE
API for my design and plugins?

### ISSUE THREAD

**Issue by s-dm** [WP-API/WP-API#2892]
Been searching up and down on google for this, but I can't figure it out. I need your api to get stuff from my event site. I am using Event Builder Plugin and Eventbuider design, but as there is no api in it, I am lost in how to get data down to my app.. For now I am using screen scraping, and it works ok. But  it is not an ideal method. 

Any ideas?

**Comment by modemlooper** [comment]
This really isn't the place for this type of question. This repo is for issues with API code. You require custom Endpoint development. Ask developer of your events plugin if they have API in their roadmap. If not, visit the docs site for API, google for tutorials or hire a developer.

**Comment by kadamwhite** [comment]
@s-dm Thanks for your interest in the REST API project. As @modemlooper indicated, this plugin (and the endpoints that will be released in the next version of WordPress) represent endpoints for WordPress native content types—posts, plugins, categories and the like. In order to be able to access and manipulate event data through the API, your Event Builder plugin would need to add API support to their content types; I'd suggest opening a support issue with the plugin developer to see whether they are planning to do so.

All the best, and good luck with your project!
