### ISSUE TITLE
Do not publicly expose the schema for endpoints that require authentication

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#2895]
This came up while I was looking into using the /settings endpoints for something at work.  
With Beta 15, the api index (`/wp-json/`) publically exposes the option keys that have been enabled for API interactions.  Anyone can publicly see the option keys that are exposed for create/update because they are shown in the POST/PUT/PATCH schema args.  I find this to be concerning because typically the option key is somewhat descriptive of what information is being stored.  Has there been any discussion about this?

**Comment by rachelbaker** [comment]
Milestoned for 2.0, it at least warrants a discussion before then.

**Comment by nylen** [comment]
As a larger task around all fields that require authentication (including posts, `context=edit`, etc), I don't think this is doable for 4.7.  Arguably not as necessary because most of these are already public by reading the core code.

For the settings endpoint specifically, seems doable; this is probably the biggest concern and we wouldn't lose anything by hiding the available settings for unauthenticated discovery requests.

**Comment by nylen** [comment]
Migrated to https://core.trac.wordpress.org/ticket/38691 - this can be closed.
