### ISSUE TITLE
Plugin is activated but nothing appears under "Tools" in admin

### ISSUE THREAD

**Issue by liesislukas** [WP-API/WP-API#2896]
![image](https://cloud.githubusercontent.com/assets/2733862/19704290/d3dca5ee-9b0f-11e6-9773-f86f6b09900b.png)

WP version 4.6.1
WP REST API Version 2.0-beta15

**Comment by adamsilverstein** [comment]
@liesislukas The plugin provides API endpoints and does not create any user facing admin interface.

**Comment by liesislukas** [comment]
works great, just posted some posts with nodejs lib you provide. Great job! 

I was expecting to have some ui to adjust settings like endpoint of api.

**Comment by kadamwhite** [comment]
@liesislukas glad to hear things went well!

I believe that you can change the root endpoint with a filter -- because this is core functionality upon which future WordPress features may be built the decision not to provide a UI for changing endpoint settings and locations was a deliberate choice to make the API a more predictable foundation. 

Hope that helps clarify things!

**Comment by liesislukas** [comment]
I fully understand your point. Thanks for clarify 👍
