### ISSUE TITLE
404 for custom post type routes invoked with ajax

### ISSUE THREAD

**Issue by gui-com-pt** [WP-API/WP-API#2938]
I'm receiving 404 for endpoints like forum, topic and reply from bbpress custom post types only when invoked with ajax.

Given the code:

```
function bbp_rest_forum( $args ) {
  $args['show_in_rest'] = true;
  return $args;
}

add_filter( 'bbp_register_forum_post_type', 'bbp_rest_forum' );
```

It returns a successful response for CURL but with ajax i get 404.

This only happens to custom post types. The response headers are similar to the headers from a **/post** request.

**Comment by kadamwhite** [comment]
Can you share the Ajax code snippet you are using to make the requests?

**Comment by gui-com-pt** [comment]
The API is consumed by a ionic application.

![ajax-error](https://cloud.githubusercontent.com/assets/303894/20868475/a967d1ee-ba54-11e6-822d-55bcea5d048b.png)

As you see the response seems ok, at least i get a similar response from **/posts** and a successful 200 response. I'm using the built in $http service from AngularJS and i've also tried to get as jsonp.

About the code itself it's a simple request to **https://makeu.pt/wp-json/wp/v2/forum** without any additional header.

If get it from curl the response it returns the data, for example: https://makeu.pt/wp-json/wp/v2/forum

**Comment by kadamwhite** [comment]
@guilhermegeek From the headers you're getting back, it looks like the issue may relate to some sort of CDN issue: it's probably not a CORS issue since the request doesn't return a CORS error, but since you're not making the AJAX request against the development site where the request originates, it looks like it's going through Cloudflare and it's possible that cloudflare is causing the response to be returned as a 404. I haven't seen this exact behavior before but that's my only immediate thought; I'd recommend looking into your CDN setup as a first point of investigation.

Going to makeu.pt and making the request from the browser development console there returns the data as expected, so I don't think the issue is with the API but rather with the server configuration or the way the data is being requested.

**Comment by gui-com-pt** [comment]
~~I'm now publishing a blank WP installation to test it and one thing i noticed. I've the following for the **Content-Security-Policy**: default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'~~

~~The requests for **/forum** i'm receiving: Refused to load the script 'http://test.makeu.pt/wp-json/wp/v2/forum' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'".~~

~~Others ajax requests are working properly. Do you have any idea why this request isn't a typical XHR request? Im developer tools appears as a javascript script.~~

**Update**
@kadamwhite thank you for the help.
The above question was a dumb one, i was expecting jsonp. So you're right, the cache layer is the source of the problem. Without cloudflare it's working as expected.

I'll try to find out more. I've already purged and bypassed cache to wp-json* but it keeps returning 404.
One thing i noticed. The successful responses return the **allow** header with the HTTP method, but for **/forum** it doesn't return **allow** header. Same happens for **x-wp-total** and **x-wp-totalpages**

**Comment by gui-com-pt** [comment]
It seems the error isn't related with the cache at all. I'm using a WP theme that uses a mobile plugin called **tagDiv Mobile Theme** which is responsible for the 404 i'm getting. If i disable the plugin everything works as expected (took me a few hours to realize it).

I'm closing the issue as i don't believe it's related to WP-API at all and i'll try to debug the problem with the theme, in case i can fix it i'll edit this answer.

Thank you @kadamwhite for your help.

**Comment by kadamwhite** [comment]
Sorry to hear about the difficulties with that plugin, but I'm glad we were able to help!
