### ISSUE TITLE
Request post from order

### ISSUE THREAD

**Issue by ayadgroupe** [WP-API/WP-API#2939]
Hi, I'm using WP-REST API ver 1
I'll try to make my question clear despite my poor English.

I use this link to request 20 posts from this category : https://www.originsphotography.eu/model/wp-json/posts?filter[posts_per_page]=20&filter[category_name]=shooting

Is there a way I can request only the 15th post of the list ? 
Let me explain, assuming I create a index.html with ajax request it will automatically show 20 post, each post will have a url to another ajax request page (shoot1.html, shoot2.html, shoot3.html,...) so on shoot2.html how can I request only the second post of the page ?

Thanks

**Comment by kadamwhite** [comment]
@ayadgroupe Thank you for using the REST API. A few quick notes on changes you should be aware of: we do recommend upgrading from v1, because the v2 endpoints are going to be in WordPress 4.7 (planned to be released next week) and the v1 plugin will not see any further updates. `filter` will not be present in WordPress 4.7, either, so I recommend either switching to

```
/wp-json/wp/v2/posts?per_page=20&categories=1111111
```
where `1111111` would be replaced with the _id_ of the "shooting" category; querying by ID is more reliable than querying by slug, as slugs can change and may not match category "name" fields in predictable ways. (If you need to get the ID of that category by slug, you can request `/wp/v2/categories?slug=shooting` first and pull the ID off of that response.) Alternatively, [this plugin](https://github.com/WP-API/rest-filter) will re-enable `filter`, but I recommend the above approach!

OK, on to your question! Just as you can retrieve the 20 most-recent posts with `?per_page=20`, you can get the 15th post in two different ways:

- `/wp/v2/posts?per_page=1&page=15` - this gets one post per page, and gets the 15th page of (individual) posts, which will be equivalent to the 15th post when you query `posts?per_page=20`
- `/wp/v2/posts?per_page=1&offset=14` - this uses the `offset` property to start the query 14 posts into the collection, so the returned post (a single post, thanks to `per_page=1`) will be the 15th post

I hope this helps!

**Comment by ayadgroupe** [comment]
Hi, thanks for you're reply and you're time.

I won't upgrade Wordpress to it's latest version neither I will for WP Rest API. I only use the back-office and rest-api to remote the data of my app and website.
So I'm still on ver REST-API ver 1

I tried the offset and it doesn't work.
Maybe because of my poor English I can't make my self understandable.

So this is the link I'm using to call the 20 latest post of the "shooting" category :
https://www.originsphotography.eu/model/wp-json/posts?filter[posts_per_page]=20&filter[category_name]=shooting

<img src="http://s604712774.onlinehome.fr/1.png">

So what should I add to the link to request only the 2nd or 5th post of the list ?

<img src="http://s604712774.onlinehome.fr/2.png">

Thanks

**Comment by ayadgroupe** [comment]
Hey! I found the solution and it's very easy.

So on the post page I requested the post :
`$(document).ready(function() {
$.ajax({
type: "GET",
url: 'https://www.example.com/wp-json/posts?filter[posts_per_page]=20&filter[category_name]=shooting',
dataType: 'json',
success: function(data) {
data.forEach(function(post) {
$( '#postlist' ).append( '<div class="col-lg-8 col-lg-offset-2 text-center"><a class="blogpost" href="shoot.html#' + post.ID + '"><div style="background:url(' + post.featured_image.guid + ');padding-top:10px;padding-bottom:10px;width:100%;height:350px;background-size:cover;background-position:center;"></div></a><h2>' + post.title + '</h2><p>' + post.excerpt + '</p><a href="shoot.html#' + post.ID + '" class="btn btn-primary btn-xl page-scroll deskto0p">Voir le shoot</a><hr></div>' );
});
}
});
$.ajaxSetup ({
cache: false
});    
});`

So once click on the post it will open the shoot.html page with #the post id at the end.

And on the shoot.html I request the post like this :
`<script>
$(document).ready(function() {
var loc = window.location.href
var fileNameIndex = loc.lastIndexOf("#") + 1;
var dotIndex = loc.lastIndexOf('.');
var output = loc.substr(fileNameIndex, dotIndex < fileNameIndex ? loc.length : dotIndex);
$.ajax({
type: "GET",
url: 'https://www.originsphotography.eu/model/wp-json/posts/'+ output,
dataType: 'json',
success: function(post)  {
$( '#content1' ).append( '<div style="min-height: auto;-webkit-background-size: cover;-moz-background-size: cover;background-size: cover;-o-background-size: cover;background-position: center;background-image: url(' + post.featured_image.guid + ');color:' + post.meta.couleur_ecriture + ';position: relative;width: 100%;text-align: center;height: 100%;text-align:center;"><div class="header-content"><p class="big">' + post.title + '</p></div></div>' );
$( '#content5' ).append( '' + post.content + '' );
$( '#about' ).append( '<div class="container"><div class="row"><div class="col-lg-8 col-lg-offset-2 text-center"><h4 class="section-heading">' + post.excerpt + '</h4><div style="font-size: 18px;" id="content2" class="text-grey"></div></div></div></div>' );
}
});
$.ajaxSetup ({
cache: false
});
});
</script>`
Jquery will append the post id from the link to the request link.

It can maybe help someone.
