### ISSUE TITLE
Media end-point, description field changed with WP 4.7

### ISSUE THREAD

**Issue by PatchworkBoy** [WP-API/WP-API#2948]
Previously in the JSON response from querying wp-json/wp/v2/media, the description field contained the textual description as entered in the relevant field within WP-Admin Media Library.

`"description":"Site Banner"`

Now it returns a render.

`"description":{"rendered":"<p class=\"attachment\"><a href='http:\/\/www.accordmat.org.uk\/wp\/wp-content\/uploads\/2016\/12\/site-banner.jpg'><img width=\"300\" height=\"138\" src=\"http:\/\/www.accordmat.org.uk\/wp\/wp-content\/uploads\/2016\/12\/site-banner-300x138.jpg\" class=\"attachment-medium size-medium\" alt=\"Accord MAT Site Banner\" srcset=\"http:\/\/www.accordmat.org.uk\/wp\/wp-content\/uploads\/2016\/12\/site-banner-300x138.jpg 300w, http:\/\/www.accordmat.org.uk\/wp\/wp-content\/uploads\/2016\/12\/site-banner-768x354.jpg 768w, http:\/\/www.accordmat.org.uk\/wp\/wp-content\/uploads\/2016\/12\/site-banner-1024x472.jpg 1024w\" sizes=\"(max-width: 300px) 100vw, 300px\" \/><\/a><\/p>\n<p>Site Banner<\/p>\n”}`

**Comment by kadamwhite** [comment]
This change was made for consistency with the other endpoints, which provide the display-facing content as a `.rendered` property on a wrapper object in view mode. When authenticated you may pass `?context=edit` to a media collection or record to get back the raw value:

```
{
    raw: 'Public domain via http://www.burningwell.org/gallery2/v/Landscapes/ocean/IMG_0767.JPG.html',
    rendered: '<p class="attachment"><a href=\'http://wpapi.loc/content/uploads/2011/07/img_0767-59.jpg\'><img width="300" height="200" src="http://wpapi.loc/content/uploads/2011/07/img_0767-59-300x200.jpg" class="attachment-medium size-medium" alt="Huatulco Coastline" srcset="http://wpapi.loc/content/uploads/2011/07/img_0767-59-300x200.jpg 300w, http://wpapi.loc/content/uploads/2011/07/img_0767-59-768x512.jpg 768w, http://wpapi.loc/content/uploads/2011/07/img_0767-59.jpg 800w" sizes="(max-width: 300px) 85vw, 300px" /></a></p>\n<p>Public domain via http://www.burningwell.org/gallery2/v/Landscapes/ocean/IMG_0767.JPG.html</p>\n'
}
```
Does this help?

**Comment by kadamwhite** [comment]
Actually you're correct that it's unusual that we provide the _embedded image_ inside the rendered description, that feels misguided. Will ping the team.

**Comment by PatchworkBoy** [comment]
Thanks... I'd been using the description field split on line breaks to contain description text, target element id, and a host of other custom fields... as you can imagine, I was surprised when 40-odd sites all suddenly broke!

**Comment by nylen** [comment]
Regarding your specific task, you might want to consider storing this information in meta fields and/or custom taxonomies instead.

As a short-term fix you can throw out the first line of the rendered description if it contains `<p class="attachment">`.

The previous behavior of the media description field was incorrect because it was inconsistent with the way the API handles other post types.  Context:

- https://core.trac.wordpress.org/ticket/38679
- https://wordpress.slack.com/archives/core-restapi/p1481127257000410

Also note that development of the API has moved to WP core Trac (https://core.trac.wordpress.org/) - if you can create an issue there, that will greatly help us prioritize a fix.

**Comment by rmccue** [comment]
This has been migrated to Trac: https://core.trac.wordpress.org/ticket/39185
