### ISSUE TITLE
Post drafts do not work.

### ISSUE THREAD

**Issue by damnabit** [WP-API/WP-API#2965]
WP 4.6.1, attempting migrate functionality to use the WP-API.  We are able to pull data via curl or Postman to view the list of posts (https://oursite.org/wp-json/wp/v2/posts) and we can see an individual post (https://oursite.org/wp-json/wp/v2/posts/53903).

However we _cannot_ view a post which is in draft.  Instead we receive the message: 
{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":403}}

Published posts work fine.  You can even view the post if you publish it, but if you put it back into draft you again receive the above message.

We are currently only using the Basic Authentication for testing but it doesn't seem to matter what we put in for credentials, the message for posts in draft is the same.

**Comment by nylen** [comment]
This means that your authentication is not being recognized.  You will have to install a plugin since this is not supported in core (https://developer.wordpress.org/rest-api/authentication/#authentication-plugins).

Here are a couple of options that are preferable to basic auth:

- https://wordpress.org/plugins/rest-api-oauth1/
- https://wordpress.org/plugins/application-passwords/ (basic auth, but with revocable application passwords instead of your WP password; DO NOT USE over unencrypted HTTP)

For a more specific test of authentication, try `GET /wp-json/wp/v2/users/me`.

@WP-API/amigos #closeme

**Comment by damnabit** [comment]
Would it also be best to remove references to Basic Auth from the documentation?  If it isn't working or part of core why not remove it?
