### ISSUE TITLE
Better Filter parameter documentation

### ISSUE THREAD

**Issue by HauntedSmores** [WP-API/WP-API#2967]
Just thought I'd mention that I had to google around to find information on filter options for the api (/posts?filter[name]=whatever). Its mentioned in one brief sentence in the overview of the plugin, both on the website and github site.

I feel like it would have really sped things up for me if there were concise documentation on the syntax (im aware NOW that its standard REST api stuff) and all of the available options to filter. Its an amazing and powerful feature of the api thats very useful, so for newcomers it would be really nice to have documentation for it.

Thanks!

**Comment by BE-Webdesign** [comment]
Hi @HauntedSmores,

Thank you for using the WP REST API.  The filter param was removed in WordPress 4.7 for maintainability reasons.  The filter param does provide additionaly flexibility similar to `WP_Query`, however the WP REST API can pretty much do whatever you need it to.  If you need to use the filter param there is a [plugin that adds it back](https://github.com/WP-API/rest-filter).

To address the documentation concern, I don't believe there will be any official documentation around the filter param.  For the most part it supports what can be done using arguments for [`WP_Query`](https://developer.wordpress.org/reference/classes/wp_query/)

**Comment by HauntedSmores** [comment]
Hey, @BE-Webdesign , Thanks a lot for the info! So then, how would I go about, lets say getting a post or page via slug without using the WP_Query params? Basically, I'm just trying to avoid getting every post or page, to then search for the one I need, obviously not a good way to do things.

Also, the filter options like, /pages?slug="whatever", are working and I dont have the additional plugins installed.

**Comment by kadamwhite** [comment]
@HauntedSmores There's a meeting tomorrow to prioritize documentation for developer.wordpress.org/rest-api, and the issue you're describing is one of our top priorities: but the good news is that there's built-in support for querying by slug on almost all endpoints, just by using `?slug=` with the string of the slug to search for. So,
```
/wp/v2/posts?slug=some-post-slug
/wp/v2/categories?slug=some-category-slug
/wp/v2/tags?slug=some-tag-slug
```
etcetera. This will return an array with the matching post, tag, or category in it. (Because the query parameter is technically a search action that filters the collection down to a single result, it's returned as an array rather than a raw post.)

You can also do a broader search using `?search=`, and so on: check out the [list of accepted query parameters for the `posts` collection](https://developer.wordpress.org/rest-api/reference/posts/#arguments) in the new official REST API documentation, for example.

Hope this helps!

**Comment by HauntedSmores** [comment]
@kadamwhite This was unbelievably helpful information and I appreciate it very much. Very glad to hear that you guys are revising the documentation and am excited to take a look when its released! You guys really did great work with this plugin and I used it extensively to develop an Angular 2 application with WordPress as a headless CMS. 

Thanks for the great work
