### ISSUE TITLE
Custom endpoint - CORS problem

### ISSUE THREAD

**Issue by bakerGS** [WP-API/WP-API#2973]
Hi everybody,

We are developing an app on ionic2, consuming data from a custom endpoint on REST API for WP.

The thing is, if we use the endpoints provided for WordPress REST API plugin, there is no problem, but if we create our custom endpoint, javascript from ionic2 get 404, like a problem with CORS.

Of course, if we request the same URL by any navigator (chrome, firefox, etc) we have no problem.

Any ideas? We have tried we WP CORS for example, but nothings happens

The code for the custom endpoint is like that:

```
register_rest_route('mytheme/v1', '/postsfortag/(?P<tagid>(.*)+)', array(
        'methods' => 'GET',
        'callback' => 'get_posts_by_tag',
    ) );

function get_posts_by_tag($data){
    global $wpdb;
    $tagId = $data['tagid'];

    $args = array('tag_id' => $tagId, 'posts_per_page' => 10);

    $posts = get_posts($args);

    $resultJSON = array();
    $i = 0;
    foreach ($posts as $post){
        $postId = $post->ID;
        $resultJSON[$i]["id"] = $postId;
        $resultJSON[$i]["post_title"] = $post->post_title;
        $resultJSON[$i]["post_date"] = $post->post_date;
        $resultJSON[$i]["guid"] = get_permalink($postId);
        $resultJSON[$i]["image"] = getPostThumbnail($postId);
        $resultJSON[$i]["author"] = getPostAuthor($post);

        $i++;
    }

    return $resultJSON;
}

```

Thanks in advance!

**Comment by modemlooper** [comment]
Have you tried _jsonp ? 

http://v2.wp-api.org/reference/global.html

**Comment by rmccue** [comment]
Hi! We're no longer handling support requests on GitHub, please use the [support forums](https://wordpress.org/support/) instead.

In this specific case, you can use the built-in responses at `/wp/v2/posts?tags={id}` (replacing `{id}` with the tag ID).

To the larger question, there's no reason that CORS shouldn't work for custom endpoints. Make sure you're returning your data rather than echoing directly, and the headers should be sent properly. For any further debugging, please ask on the support forums. :)
