### ISSUE TITLE
Since filter has been removed, how to get posts by meta key and order by meta value ?

### ISSUE THREAD

**Issue by GreenSunBear** [WP-API/WP-API#2977]
I hope i'm posting this in the right place, this is a support question.
Trying to figure out what is the best approach to filter posts by meta field.
there is an issue: #https://github.com/WP-API/WP-API/issues/2308 but i can't get the suggested methods to work.
using a plugin [WP REST Routes](https://wordpress.org/plugins/rest-routes/) to create a custom route for my custom meta field works but can't order by meta_value_num order asc/desc.
greatly appreciate any help, hint, or direction on how to approach this.

Thanks in advance!
Jake

**Comment by martingreenwood** [comment]
I'm also having this issue, not so much the order by as i don't use that but meta_key is now getting ignored...

**Comment by alexthip** [comment]
I'm having a similar issue, but I was using filter[post__in] with the post id's.

**Comment by rmccue** [comment]
Since the API has been merged into core, we're no longer using this issue tracker for support requests. Post on the [WordPress forums](https://wordpress.org/support/) instead.

`filter` was removed in 4.7 final, but is available [as the `rest-filter` plugin](https://github.com/WP-API/rest-filter) for compatibility.
