### ISSUE TITLE
page duplicates itself on save

### ISSUE THREAD

**Issue by iegoshin** [WP-API/WP-API#2984]
Hello,

I am trying to use WP-API plugin for automatic updates (from another application). I am generating a slug and checking if the page with the same slug already exists. It all works great, I can find the self edit URL of the page and making a POST to URLs like this: /wp-json/wp/v2/pages/[id] where [id] is a number

However, after it's done, in the wp-admin I can see that it didn't update the existing page, but created a new one, the slug is the same only with suffix "-2"

WordPress 4.7, WP-API Version 2.0-beta15

I am adding these attributes:
title
slug
content
link
status
comment_status
ping_status
template

Am I missing some important attribute required for an update? Could you please advise why it could be happening?

Thank you!

**Comment by nylen** [comment]
Hi @iegoshin - that sounds pretty bad. The most likely explanation is that you are not passing the `id` parameter correctly in the URL.

Can you verify that, perhaps using Network Inspector in your browser?  This is definitely something that normally works correctly on other sites.

Note also that the WP-API plugin doesn't do anything under WordPress 4.7 since the content endpoints shipped with 4.7.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
