### ISSUE TITLE
How to login a user

### ISSUE THREAD

**Issue by wilburx9** [WP-API/WP-API#2986]
I understand that we can create new users with the API. Please what about old users logging in?

**Comment by nylen** [comment]
Hi @wilburt - if your application lives in wp-admin you can use the built-in cookie authentication, otherwise you will need to install a plugin for authentication. See https://developer.wordpress.org/rest-api/authentication/#authentication-plugins for more info.

There is an API console that you can use to test your authentication setup. It has some basic instructions about configuring an auth plugin also. See: https://github.com/Automattic/wp-api-console/blob/master/README.md#using-with-your-self-hosted-wordpress-site

@WP-API/amigos #closeme

**Comment by wilburx9** [comment]
@nylen, Thanks for you reply. I thought the cookie authentication is for desktop? Please do  you have any idea how can it be used for mobile? The site lives in wp-admin.

**Comment by nylen** [comment]
Where did you hear that about desktop vs mobile? That's not right, all that matters is that the application lives in wp-admin.
