### ISSUE TITLE
Get post by slug

### ISSUE THREAD

**Issue by emeaguiar** [WP-API/WP-API#456]
I've been going through the documentation and issue list and I haven't found a way to retrieve a certain post not by ID but by slug.

I have my WP installation separated from the frontend and I access the posts by reading the url e.g.

www.mysite.com/blog/my-post-slug

I should be able to read `my-post-slug` and make a request to:

www.mysite/wordpress/wp-json/posts/my-post-slug

But `posts` only accepts `<id>` as a parameter. Was this by design? Is the there a way to retrieve the id based on the slug, or would that require to extend the api?

**Comment by adamchenwei** [comment]
@emeaguiar Nice trick!

**Comment by MurhafSousli** [comment]
so how would somebody get embedded post by its slug?
`http://localhost/wptest/wp-json/wp/v2/posts?filter[name]=hello-world` this is not embedded.
and this `http://localhost/wptest/wp-json/wp/v2/posts?filter[name]=hello-world?_embed` return nothings.

**Comment by danielbachhuber** [comment]
Try:

```
http://localhost/wptest/wp-json/wp/v2/posts?filter[name]=hello-world&_embed
```

Note: `&_embed` instead of `?_embed`

**Comment by MurhafSousli** [comment]
worked... thank you

**Comment by satishgadhave** [comment]
If for some reason slug changed, will this still work with old slug? Wordpress automatically redirects URL with old slug to new. Would it do the same for API?

**Comment by danielbachhuber** [comment]
> If for some reason slug changed, will this still work with old slug? Wordpress automatically redirects URL with old slug to new. Would it do the same for API?

No, and this is one of the reasons you can't expect querying by slug to be reliable. If you know of a specific post, you should query by the id.

**Comment by ryangiglio** [comment]
So in this case, when you're trying to query a specific blog post and want to use the slug in the URL, how would you recommend getting the ID to query by? I wouldn't want my site to have to use site.com/blog/ID instead.

**Comment by danielbachhuber** [comment]
You can use `GET /wp/v2/posts slug==<slug>`, which will return a collection of zero or more items, and pull the first item from the set if it exists.

First-class support for parsing permalinks is something on our radar (see #576 and #1776), but we don't have a timeline for addressing it.

**Comment by kyxyes** [comment]
Just found it was updated to `/wp-json/wp/v2/pages?slug=about-me` according to https://github.com/WP-API/WP-API/blob/develop/README.md

**Comment by yorikworld** [comment]
WP have some hooks for WP API and for this query: `/wp-json/wp/v2/pages?slug=about-me`
I need make +1 to meta data of this post. Thanks.

**Comment by ravishakya** [comment]
This also works for custom post types

`wp-json/wp/v2/YOUR_CUSTOM_POST_TYPE/?slug=hotelica`

**Comment by bretmorris** [comment]
`?slug=my-slug` works fine most of the time. but what happens if you have two pages with the same slug? For example? 

`mysite.com/my-slug` and `mysite.com/some-parent/my-slug`

Currently, it seems that filtering by slug will return both of these pages or just the first. Surely there's a way to search by the full path using the WP API right?

**Comment by yorikworld** [comment]
You can\`t have two pages with same slug. If you try to create page/post with a same slug WP create slug like this `my-slug-2`. So it will be two different pages/posts.
When you take this slug like this `mysite.com/my-slug` and `mysite.com/some-parent/my-slug` it will be mean that you try to take `my-slug` post for two different pages/category/tags/etc.

**Comment by adampatterson** [comment]
I find this a bit confusing my self. I understand the limitation of two pieces of content sharing the same name.

But what has always bothered me about WordPress page/taxonomy hierarchical data is the relationships.

If I have a page like `services/design` and `services/development` I can easily look up services and see that it has two child pages. Possibly what order they are in. But that would only work if WordPress gave you child ids. Rather you get parent ids.

But how are you supposed to return a single post or a subpage in any kind of route based external application?

Seems silly to look up the subpage name, then the child page and attempt to match a parent ID.

It has been a while since I dug through the WP Core code, but I think most content is resolved using the guid and that identifies what the page/post is, Except we/I can't look content up that way.

I also get that using a URI or even the GUID is not ideal because that requires your application to mimic the WordPress structure ( maybe thats good or normal? ).

**Comment by christopherhuii** [comment]
`/wp-json/wp/v2/posts?slug=my-post` returns an array of objects.

is there a way to just return a single object? aren't slugs unique?

**Comment by mladenilic** [comment]
Hi @christopherhuii,

I believe you are right, slugs should be unique. However, if you think about it, it makes sense that returned result is an array. You are making a request to `/posts` endpoint and applying a filter to it. `/posts` returns an array, this way API behavior is more consistent.

Additionally, from the implementation perspective, API parameters are mapped and passed as arguments to `WP_Query`, so again, it makes sense that the response is an array.

I hope you'll get response from someone on the API team, but I believe that this behavior is intended.

Lastly, you can always take a first element of an resulting array. That will give you single post object. 

Best,
Mladen
