### ISSUE TITLE
json_upload_sideload_error should return 403 error, not 500

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#532]

**Comment by danielbachhuber** [comment]
Hmm, not sure why I filed this originally.

**Comment by rmccue** [comment]
> Hmm, not sure why I filed this originally.

There's a bunch of different things that can be returned (listed with "ideal" error codes):

* File is too large: Possibly 403, probably just 400
* File is too small (zero bytes): 400
* File was only partially uploaded: 400
* File type not permitted: Possibly 403, probably 400
* File couldn't be moved: 500
* File couldn't be written: 500

We *could* add more handling in here, but we risk attempting to be too verbose, and being brittle with regards to internal changes in WP. I wouldn't be against being more verbose here (mainly because most of the errors are actually 400 Bad Request errors), but we need to be careful.

Happy to close if we'd prefer to skip?

**Comment by danielbachhuber** [comment]
We can come back to it if it rears its head again
