### ISSUE TITLE
Non-Authenticated Create New User

### ISSUE THREAD

**Issue by royboy789** [WP-API/WP-API#538]
Referencing to a conversation with @rmccue at WCSF.. creating an issue for the pull

**Comment by al3x-edge** [comment]
@royboy789 @danielbachhuber Is this something that made it into 2.0 beta or did it die out?

**Comment by danielbachhuber** [comment]
Hasn't been implemented yet.

**Comment by rachelbaker** [comment]
@royboy789 Is this something you still want to submit a PR for using the `develop` branch?

**Comment by tinytoolbox** [comment]
@royboy789  I can't find anything in the docs about this so I assume it's not in yet.  Any update?

**Comment by danielbachhuber** [comment]
@tinytoolbox it's not yet supported by the API.

**Comment by tinytoolbox** [comment]
Thanks @danielbachhuber.  I think I know the answer but Is there a timetable for its inclusion?  @royboy789 mentions in the thread above that he has some code for this.  Does it work?  My team would happily contribute to this as we need it for our project anyway.

**Comment by danielbachhuber** [comment]
> I think I know the answer but Is there a timetable for its inclusion?

When someone creates a satisfactory pull request to address the issue :)

> mentions in the thread above that he has some code for this. Does it work?

Not sure. Given the age of the ticket, I suspect the code is quite out of date.

**Comment by royboy789** [comment]
@tinytoolbox This is some old code from a plugin I created for social login/registration but it might help you.

You'd probably need to add authentication and validation, but it works..

**Comment by tinytoolbox** [comment]
Was there supposed to be something attached?  I did get the code.  Thanks

**Comment by tinytoolbox** [comment]
*didn't

**Comment by royboy789** [comment]
@tinytoolbox sorry:
https://github.com/royboy789/wp-api-social-login/blob/master/inc/social-routes.php

**Comment by simonegiacco** [comment]
This solves the issue using register_new_user() instead of wp_insert_user(), just in case of a non-admin trying to add a user without providing the password (non-admins can only create users without providing the password indeed)

The only counter effect i found is that register_new_user() returns errors (if any) in HTML, and this is not a standard you are following on the API.
The alternative is to copy-paste most of the register_new_user() code.

@danielbachhuber This pull request follows [my messages](https://wordpress.org/support/topic/i-need-to-allow-new-users-to-create-an-account?replies=4#post-7967628) on the plugin support page.

I'm happy to help, please give me some feedbacks to let my modification suit your needs.

Thanks

**Comment by simonegiacco** [comment]
Questions:
1. How do you want to distinguish between requests to create a network user from requests to create a standard user? 
2. Shall we use `current_user_can( 'manage_network_users' )`
3. Do you want to offer admins the choice to notify or not the final user?
4. Do you want to make it automatic? (ie: if you set the password, the user doesn't get a notification; if you don't set the password, the user gets a notification)

more questions coming

**Comment by danielbachhuber** [comment]
We're not going to be including this in the core plugin at this time https://github.com/WP-API/WP-API/pull/2356#issuecomment-195234273
