### ISSUE TITLE
GET resources by slug

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#642]
A pretty common need is to be able to get a post by a slug. What if would it look like if you could get any resource by id or slug?

* `Post` - Type would need to be indicated in the route, as posts of two different types can have the same `post_name`.
* `Term` - Taxonomy would need to be indicated in the route, as two terms of different taxonomies can have the same `slug`.
* `Comment` - No such thing as a comment slug.
* `Meta` - Meta keys are sometimes unique. We can't rely on it.
* `User` - User's slug is the `user_nicename` which can be relied upon to be unique (as it's used in author URLs) and has an index in the db.

**Comment by danielbachhuber** [comment]
[This has been addressed](https://wordpress.slack.com/archives/core-restapi/p1427759082000510).

For querying by slugs, our pattern will be `/wp/posts?slug=<slug>`

Related #924

**Comment by baffleinc** [comment]
Hmm... hitting `/wp-json/posts?slug=why-us` returns my 10 most recent blog posts instead of the why us page.. Am I missing something?

**Comment by danielbachhuber** [comment]
> Am I missing something?

Not implemented in `develop` yet.

**Comment by baffleinc** [comment]
Ah ok... what's the best solution at present?

**Comment by danielbachhuber** [comment]
Use `name` instead

**Comment by baffleinc** [comment]
Yeah... 

/wp-json/posts?name=why-us - 10 most recent posts
/wp-json/posts?filter[name]=why-us - empty array

both stopped working after they used to work A-OK. Only since updating to 1.2. I'm not crazy, the page exists: https://www.dropbox.com/s/27ceykrau45de62/Screenshot%202015-04-02%2010.43.58.png?dl=0

**Comment by danielbachhuber** [comment]
> both stopped working after they used to work A-OK.

Oh. Can you open a new issue then? Might be a bug specific to 1.2

**Comment by baffleinc** [comment]
Sure. I tried downgrading, uninstalling, reinstalling, turning all plugins off again and having the same problem

As it turns out no filters are working - can you imagine any reason why? 

1. http://www2.health.com.au/wp-json/posts/?filter[name]=why-us - returns empty array
2. http://www2.health.com.au/wp-json/posts/?filter[type][]=page - returns most recent posts (not pages)
3. http://www2.health.com.au/wp-json/posts/?filter[page]=3 - returns first page of posts (same as #2)

Would really appreciate some help as it has been working fine.

**Comment by baffleinc** [comment]
Any idea when the ?slug param will be introduced? just getting empty arrays still :(

**Comment by kadamwhite** [comment]
@baffleinc Are any other query parameters (like `posts?page=2`) working? What server are you using? If it's nginx, make sure your try_files directive is [specified as described in #1926](https://github.com/WP-API/WP-API/issues/1926#issuecomment-168090756), it's possible your server can't see the query parameters.
