### ISSUE TITLE
Comments count

### ISSUE THREAD

**Issue by justvanbloom** [WP-API/WP-API#777]
add a count on /post/≤id>/ of comments plz

**Comment by rachelbaker** [comment]
@justvanbloom Good idea.  Thank you for the request.

**Comment by danielbachhuber** [comment]
Related #783, in the sense that these are additional "attributes" of a Post Resource that are some abstraction of what's stored in the database. Because a Post's Comments really represents an associated collection, maybe the best way to do this is have some `count` attribute of that link. We'll want to do the same for users, terms, etc.

cc @WP-API/amigos

**Comment by justvanbloom** [comment]
Currently i count ondevice stepping trough all comments. Sometimes its fast but if there are mite than a few comments its slows down. So a simple count serverside would be awsome

**Comment by rmccue** [comment]
Closing in favour of #848.
