### ISSUE TITLE
featured_image.attachment_meta.sizes does not include all custom sizes when included in /post request.

### ISSUE THREAD

**Issue by ericnkatz** [WP-API/WP-API#779]
I think this is a bug since the /media endpoint shows all the attachment_meta.sizes that would be missing from the /post endpoint. 

You shouldn't have to make a second request after request a post to get the extra sizes associated with the featured_image.

**Comment by ericnkatz** [comment]
So after some further investigation, it is only attaching sizes to the /post that were generated when the image was attached and not any sizes that have been generated afterwards.

**Comment by danielbachhuber** [comment]
> not any sizes that have been generated afterwards.

Meaning, you've included an additional `add_image_size()` after the attachment was uploaded? Did you regenerate all thumbnails using `wp media regenerate` or the [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) plugin?

**Comment by ericnkatz** [comment]
Yes they were regenerated, and actually I'm not sure if I was hitting an odd caching issue or something because after a couple hours it started pulling the correct image.

**Comment by rmccue** [comment]
Closing this one; sounds like an intermittent bug with the setup, as I believe we're using the same as core's APIs here.

**Comment by andyinabox** [comment]
I'm experiencing this same issue currently. To be more clear on the issue I'm experiencing:

 1. I updated one of my custom `add_image_size()` definitions, modifying the image size.
 2. I ran `wp media regenerate` using WP-CLI.
 3. For certain images, loading the specified image size using the standard WordPress API works, but it's not included in the JSON response from WP-API. Others behave as expected.

I dug deeper in here's what I found:

 * When WordPress runs regenerate images, it will only create a new image for a specified size if that size is smaller than the original (so if I have a 1200x800 image size called `"my_large_image"` but the uploaded image is 800x600, it will not generate a new image for that size).
 * When using the standard Wordpress PHP API, if you request an image size that has no separate image file (because it was smaller), it will automatically return the original size (requesting `"my_large_image"` image size will simply return the original 800x600 image).
 * In the WP-API JSON response, **if there is not a separate file for an image size, it simply isn't included in the JSON. This means if I have code on the frontend to get the `"my_large_image"` image size, I will simply come up empty-handed because there's nothing there.**

If the goal of WP-API is to mimic the behavior of the standard WP PHP API, this seems to fall short. Generally, I expect that if I set an image size in WordPress, I should be able to access that size by name no matter what (even if the actual image returned is smaller than the specified size).

**Comment by danielbachhuber** [comment]
> Generally, I expect that if I set an image size in WordPress, I should be able to access that size by name no matter what (even if the actual image returned is smaller than the specified size).

This makes sense to me. Thanks for the detailed report. I've filed it as a bug against the 2.0 milestone.

**Comment by andyinabox** [comment]
Cool, thanks! :)

**Comment by ericnkatz** [comment]
:+1:

**Comment by danielbachhuber** [comment]
> You shouldn't have to make a second request after request a post to get the extra sizes associated with the featured_image.

This was long fixed with #1667

> When using the standard Wordpress PHP API, if you request an image size that has no separate image file (because it was smaller), it will automatically return the original size (requesting "my_large_image" image size will simply return the original 800x600 image).
> [...]
> Generally, I expect that if I set an image size in WordPress, I should be able to access that size by name no matter what (even if the actual image returned is smaller than the specified size).

Looking at this a second time, I'm not sure which WordPress PHP API produces this behavior. In my opinion now, the correct behavior is to only return an image size in the response if there's an image file corresponding to the proper proportions and resolution of the image size.

Now that we include `full` in the response too (#1806), it's much easier for clients to fall back to the `full` size if they don't receive an expected size (should they choose to).
