### ISSUE TITLE
Add special handling for wp_die

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#790]
We need to add a `wp_die_handler` filter so we can return a response when WordPress evokes `wp_die`.

Reference link to how Jetpack handles this: https://github.com/Automattic/jetpack/blob/a8f890c21db29f0d4ec22734fbb19b74cfa45bb1/class.json-api.php#L554

**Comment by rachelbaker** [comment]
Once this is added we can decouple the comment_post_ID from the comment endpoints.  Related discussion: https://github.com/WP-API/WP-API/pull/693#discussion_r23181781

**Comment by rmccue** [comment]
1. Wherever possible, always try and avoid `wp_die` invocations. If it means replicating part of core to do so, it's better to do that (and file a core ticket too, obviously).
2. I would not be adverse to using exceptions here. We ideally want to return execution back to the normal API usage rather than replicating it.

**Comment by danielbachhuber** [comment]
Flagging for Discussion for an official verdict.

`WP_Test_REST_Comments_Controller::test_create_item_duplicate` is impacted by this.

**Comment by scotchfield** [comment]
Tested this locally with https://gist.github.com/scotchfield/f80e09236484b013ffd6 (thank you, Jetpack!) which is probably too general but catches the wp_die calls when creating comments in create_item (wp_allow_comment).

**Comment by joehoyle** [comment]
we should add a wp_die handler, ala jetpack api

**Comment by joehoyle** [comment]
This would be included in the server stuff / core, so tracking in https://core.trac.wordpress.org/ticket/34999
