### ISSUE TITLE
Namespace clash?

### ISSUE THREAD

**Issue by peardox** [WP-API/WP-API#796]
Is this an extension of https://wordpress.org/plugins/json-api/ or a replacement?

A site I'm working with already uses the above but can't install WP-API owing to identical function names - first one notified is json_api_init()

Oh, while I'm here - can OAuth2 be used for authentication or are we forced to use OAuth1B / Basic?

**Comment by joehoyle** [comment]
@peardox this is a replacement for the linked plugin. You'll need to deactivate the other one I'd imagine.

As for OAuth2, @rmccue can weight in more, though my understanding is the WP-API won't be shipping with an OAuth2 module due to a requirement for SSL, however it could be added via an extension plugin to the WP-API.

**Comment by rmccue** [comment]
> can OAuth2 be used for authentication or are we forced to use OAuth1B / Basic?

Despite the naming, 2 is a completely different standard to 1, and 2 doesn't obsolete or replace 1. 2 *does* require SSL right now (although this may change with some of the proposed extensions coming soon from the working group), which is why we can't support 2 for all sites.
