### ISSUE TITLE
Posts route with limited fields after json_prepare_post?

### ISSUE THREAD

**Issue by lapidus** [WP-API/WP-API#827]
First of all, what is a good practice to create a posts/ output with only 2-3 fields?
```
[
   { ID: 1, slug: "my-post", title : "My Post"},
   { ID: 2, slug: "my-post2", title : "My Post 2"},
]
```
Second, if I am using json_prepare_post to extend my "normal" posts output with a couple of extra fields, how would I create the above with one of those included? (I.e. I would ideally like to keep my json_prepare for all posts but have 2 different outputs.)

```
[
   { ID: 1, slug: "my-post", title : "My Post", custom_field: "something"},
   { ID: 2, slug: "my-post2", title : "My Post 2", custom_field: "something"},
]
```

Should I in general be looking at extending with custom routes that extend get_posts() or is there a way to change the output based on query vars? All help appreciated!

**Comment by danielbachhuber** [comment]
When 2.0 is ready, we'll have a secondary plugin where you can use `fields=id,slug,title` or similar to only get specific fields. Follow #572 to keep up to date.

Filtering the response won't be considered a best practice, because there may be a second client that needs the fields you don't need, and filtering is permanently destructive.
