### ISSUE TITLE
Finalize endpoints for core and custom taxonomies

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#829]
Our category and tag endpoints currently live at `/wp-json/wp/terms/category` and `/wp-json/wp/terms/tag` on `develop`.

I think we actually want them them to be `/wp-json/wp/categories` and `/wp-json/wp/tags`. The endpoint registration pattern should be similar to https://github.com/WP-API/WP-API/pull/820/files#diff-55d3bf5e833c76ee6e3c2f4be15fa1cdR84

Prompted by: https://github.com/WP-API/WP-API/issues/813#issuecomment-72403922

**Comment by rachelbaker** [comment]
Capturing a comment/discussion item from @rmccue here:
https://wordpress.slack.com/archives/core-restapi/p1424094487000937

> I've been thinking of that I'd like to hear your thoughts on is how we handle conflicts if we auto-register routes for post types/taxonomies. i.e. if there's a `product` post type and a `product` taxonomy

**Comment by rachelbaker** [comment]
Capturing follow-up feedback from @aaroncampbell via Slack (begins: https://wordpress.slack.com/archives/core-restapi/p1424107698000942):


> What if they want the product cpt to use the `product` base and the tax to use something else? Would that be possible?

> Mostly because I think I'd rather resolve a conflict by using `product` for the cpt and `product-tax` or something for the taxonomy

> But that's just me. Actually, if there was a conflict here, wouldn't there be a conflict in WP too?  So the tax and the cpt should really be using different slugs already?

Screenshot: https://cldup.com/E4Yh1MVNJL-3000x3000.png

**Comment by danielbachhuber** [comment]
I don't think we should auto-register custom post types because the schema for each is likely substantially different than core's. I do think we should auto-register public custom taxonomies.

**Comment by rmccue** [comment]
The problem if we auto-register either is that we're compressing two namespaces into one, so there can pretty naturally be conflicts there. If I have a post type that has the base set to `comics`, and then I activate another plugin that has a `comic` taxonomy (that will be turned into `/wp/comics`), how do we resolve it?

I think the natural way to do that is to avoid compressing them, so instead we'd have `/terms/<type>` and `/terms/<type>/<id>`. This makes it semi-inconsistent with posts (which are at `/<type>/<id>`), but I'm OK with doing so, since while "terms" is a generic term (heh) for objects with a taxonomy, "posts" is an overloaded term, so `/posts/<type>` might be more confusing. Posts would also be opt-in only via `json_base` or whatever.

We also need to consider this with the other core objects: how do we handle custom comment types, and custom user types? Auto-registration seems like an OK idea (assuming we're OK with the auto-generated naming), as long as they're namespaced.

**Comment by danielbachhuber** [comment]
I think at this point I'm :-1: for auto-registering any custom post types or taxonomies at the risk of exposing data a WordPress developer didn't intend to expose. These will likely be the edge cases, but could be disastrous edge cases. Given that custom post types and taxonomies require a WordPress developer to implement in the first place, I think we should have them opt-in to the API.

> how do we handle custom comment types, and custom user types?

What are custom user types?

**Comment by rmccue** [comment]
> What are custom user types?

Forgot to answer this; they're a theoretical type in WordPress which doesn't exist right now, but will likely in the future as the objects change (and we get things like object-to-object relations). For example, the API itself could spur adding this, as you may want API clients which operate as their own user, but shouldn't have the ability to log in via the web.

**Comment by danielbachhuber** [comment]
We're going to rename the endpoints to `/wp/v2/categories` and `/wp/v2/tags`, respectively

Conversation https://wordpress.slack.com/archives/core-restapi/p1449531577001359

Related https://github.com/WP-API/WP-API/issues/1202#issuecomment-160799448
