### ISSUE TITLE
Unable to access post meta in a CORS request with basic auth

### ISSUE THREAD

**Issue by federicovezzoli** [WP-API/WP-API#833]
I'm developing a phonegap (angular) application and I'm using wordpress as a backend.

I can do basic query, without authentication and everything works fine.
Then, I'm trying to retrieve some post meta through basic authentication and the CORS setttings are locking me out.

My GET call turns into an OPTION call and it fails miserably.
I've tried to specify the origin (which is nonsense for an App but just to try) and I still get a 400.
I've tried everything I could find but nothing seems to work, the basic auth just don't work from the browser.

If I try the same GET authenticated call in POSTMAN it works super fine, no problem at all.
Where is the difference?

Any hint?

**Comment by danielbachhuber** [comment]
Can you share some example requests and responses so I have a better sense of what you're talking about?

**Comment by federicovezzoli** [comment]
of course.

Request in the ctrl:
```
SediMeta.get({id: value.ID}, function(l,getResponseHeaders){
     console.log(l);
});
```

Factory:
```
//Sedi Meta
.factory('SediMeta',['$resource', '$base64',
	function($resource, $base64){
		return $resource('http://fonda56.com/content/wp-json/posts/:id/meta/', {}, {
			get : {
				method: 'GET',
				//params: {},
				isArray: true,
				/* Note the headers property */
				headers: {
					Authorization : 'Basic YWRtaW46cHJpbWF0ZTIwNQ=='
				},
				cache: false
			}
		});
	}
]);
```
Response
![schermata 2015-02-05 alle 08 37 46](https://cloud.githubusercontent.com/assets/404154/6056525/51d73aba-ad12-11e4-965c-e773e355bbaf.png)

the same exact request works fine in POSTMAN.
In jQuery it does the exact same behaviour, I recon is some CORS issue but cannot work it out.
Let me know if you need anything.

**Comment by danielbachhuber** [comment]
> http://fonda56.com/content/wp-json/posts/:id/meta/

`:id` needs to be replaced with an actual ID.

**Comment by federicovezzoli** [comment]
As you can see in the screenshot, the request url is correct:

```
http://fonda56.com/content/wp-json/posts/23/meta
```

if you don't know angular I can post the jquery request, it result in the same issue.

thanks

**Comment by rmccue** [comment]
> I can do basic query, without authentication and everything works fine.
> Then, I'm trying to retrieve some post meta through basic authentication and the CORS setttings are locking me out.

Honestly, I'm not sure if Basic authentication should work in the browser; it's generally a pretty terrible idea to use Basic auth, as it's meant for local testing and development only. For that reason, I've never actually tested Basic auth + CORS before. This could be because we don't whitelist the Authorization header.

That said: are you logged in on the site? There's a bug in some versions of Basic authentication (possibly the current one as well) where having cookies for the site will cause Basic authentication to be ignored.

> My GET call turns into an OPTION call and it fails miserably.

FYI: that's just the browser sending a CORS request (which is an OPTIONS request) before sending the actual GET request, so that's normal behaviour.

**Comment by federicovezzoli** [comment]
I'm trying to use the API to retrieve data on a phonegap application. 
Which method of auth you advise for that case so?

thanks
