### ISSUE TITLE
register_post_type() should fill in rest_base attribute

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#840]
From https://github.com/WP-API/WP-API/pull/836/files#r24132849

**Comment by BE-Webdesign** [comment]
@danielbachhuber , @rachelbaker , @rmccue , @joehoyle I believe this was already taken care of as well at some point in the function _add_extra_api_post_type_arguments() in plugin.php.  One note though: the `@global` in the phpdoc needs to be fixed.  Probably from copying from the taxonomy version.  Should read `@global array $wp_post_types Registered post types.` instead `@global array $wp_taxonomies Registered taxonomies.`  I will make a PR to fix that little doc bug at some point.  Let me know if this issue is still unresolved and if I don't understand it.

**Comment by BE-Webdesign** [comment]
The document thing is fixed now in #2360.

**Comment by danielbachhuber** [comment]
This is more of a "when the plugin is merged into core" placeholder. It's unnecessary to keep open at this point.
