### ISSUE TITLE
Easy flag to use to detect when a request is a WP-API request

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#926]
For WordPress developers using actions and filters to integrate with WP-API, it would be helpful to have an easy to use flag to detect when a given request is a WP-API request.

`DOING_AJAX` is the first equivalent that comes to mind. I don't think a constant is a horrible idea, but I'm open to other suggestions.

**Comment by aryanduntley** [comment]
First thing that comes to my mind is something equivalent to $query->is_main_query()... is_rest_query() or something similar.

**Comment by danielbachhuber** [comment]
I think the flag should live outside of WP_Query, as it will apply to other endpoints as well.

**Comment by aryanduntley** [comment]
$wp_query is global and is outside accessible... too bad rest api does not have it's own flag:
private function init_query_flags()  query.php  ln#1311

**Comment by rachelbaker** [comment]
@danielbachhuber we do have the constant `define( 'JSON_REQUEST', true );`  Would that work?

**Comment by danielbachhuber** [comment]
Ah, didn't realize we had that.

@aryanduntley That's the constant you should use.

**Comment by joehoyle** [comment]
IMO constants kinda suck, because you always have to do `if ( defined( 'JSON_REQUEST' ) && JSON_REQUEST )`, what about `is_api()` ala `is_admin()` etc etc.?

**Comment by danielbachhuber** [comment]
Function seems better. Probably something we can add when this gets committed to core.

**Comment by aryanduntley** [comment]
If a function can be added to core that would be great but the constant, however clunky, will work in the meantime, thanks @danielbachhuber for the catch, thanks @danielbachhuber for the persistence.

**Comment by rmccue** [comment]
So, one reason we haven't had one of these is that the API functions are intended to be used internally too. If you change behaviour on an API request, it's likely that you'll break internal use of API functionality.

Are there any specific use cases we should cover here?

**Comment by aryanduntley** [comment]
Sure, here: #324  and here: #337.  I previously asked for hooks in these locations in order to modify the query prior querying.  There are hundreds of use cases for this, but the API will be something that will eventually be used a lot with mobile correspondence.  Mobile requests will have to be short and sweet and the data gathered should also be short and sweet and the heavy lifting should be done on the site's side in regards to data manipulation.  Since hooks are not provided here, to do serious modifications to the query prior to a JSON REST API call, a developer would either have to extend the class (and just add one line of code, which would be a hook to modify the query), or use wordpress's API hooks to modify the query.  The first is simply ridiculous because this software is in dev stage and it is a reasonable request to have modification filters placed.  The second is problematic because it is difficult to tell where the request is coming from.  In the past, I had to pass in extra params to REST request and get the value in the POST or GET variables to determine that it was a REST API call, then I had to modify the query how I needed.  This is a roundabout way of doing it and should not have to be hacked, again, because this software is still in dev and it is easy to change currently.  

I still feel that hooking into wordpress' query hooks is not ideal when the modifications can take place in a custom hook in the api.  It just makes more sense to me to have it there.  You then know EXACTLY when and where the query is taking place and modification would not require possibly several lines of conditionals to make sure that the query is being called from the REST API, etc...

**Comment by rmccue** [comment]
This is not going to happen any time in the near future.

There is intentionally no constant or function for this, as the REST API parts are intended to be usable internally as well. Checking for whether something is a REST API request is `_doing_it_wrong`, as it should be done at the API layer itself, rather than deeper down.

While it's true that mobile requests want efficient requests, that's something that needs to be handled at the API layer, *not* deeper in the codebase. Doing it deeper ties the layers together and makes it much harder to use the API internally for data processing and pre-generation of data for front-end apps. If you think you need to do this, *please* rethink what you're trying to do.

**Comment by aryanduntley** [comment]
Custom endpoints has been my solution.

**Comment by mnelson4** [comment]
> There is intentionally no constant or function for this, as the REST API parts are intended to be usable internally as well.

I think the constant `REST_REQUEST` has somehow slipped through then: https://github.com/WP-API/WP-API/commit/0cf70b6e

Also, FYI about this recent post SUGGESTING the use of the `REST_REQUEST` constant: http://torquemag.io/working-with-post-meta-data-using-the-wordpress-rest-api/

So if we really want folks to NOT rely on the constant, it should probably get removed right?

**Comment by danielbachhuber** [comment]
> So if we really want folks to NOT rely on the constant, it should probably get removed right?

@rmccue @rachelbaker @joehoyle opinions?

**Comment by rmccue** [comment]
I am A-OK with removing it.

**Comment by danielbachhuber** [comment]
The constant has been committed to core, so I think that ship has sailed.

Related: https://core.trac.wordpress.org/ticket/34373

**Comment by mnelson4** [comment]
once WP core is released I totally agree, but 4.4 hasn't been quite released yet, so I think it COULD still be removed before that right? But ya once 4.4 is released, with this constant in it, I totally agree. (It sounds like some other code is starting to rely on this constant right? Ie removing it now would be awkward)

**Comment by danielbachhuber** [comment]
The `REST_REQUEST` constant is here to stay, for better or for worse.
